function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(6)=1;
    ys_(13)=1;
    ys_(7)=1;
    ys_(14)=1;
    % Auxiliary equations
ys_(25)=exo_(1);
ys_(26)=exo_(2);
ys_(27)=exo_(3);
ys_(28)=exo_(4);
end
