function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(7)=1;
    ys_(15)=1;
    ys_(8)=1;
    ys_(16)=1;
    % Auxiliary equations
ys_(32)=exo_(1);
ys_(33)=exo_(2);
ys_(34)=exo_(3);
ys_(35)=exo_(4);
end
