function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(4)=1;
    ys_(8)=1;
    XI=1;
    XI_starr=1;
    % Auxiliary equations
end
