function analyze_welfare(oo_irfs,T_irf,OBJECTIVE,POLICY,folder_name,benchmark_folder_name,BETA,SIGMA,DELTA,PHI,GAMMA,EPSILON,LAMBDA,LAMBDA_starr,h,ALPHA_bar)


%--------------------------  Quadratic Loss  -----------------------------%


% Compute the quadratic loss under for the chosen policy objective

if OBJECTIVE == "POP_WEIGHT"
     
    Loss_CU = sum(cumprod(ones(1,T_irf)*BETA).* ...
                  ( ...
                    (1-DELTA)*(SIGMA+(1-DELTA)*PHI)*oo_irfs.c_gap_cu_eps_a_starr.^2 ...
                    +h*(1-h)*ALPHA_bar*(1-DELTA)*(1+PHI*(1-DELTA))*oo_irfs.s_gap_eps_a_starr.^2 ...
                    +h*DELTA*(GAMMA+PHI*DELTA)*oo_irfs.g_gap_eps_a_starr.^2 ...
                    +h*EPSILON/LAMBDA*oo_irfs.pie_eps_a_starr.^2 ...
                    +(1-h)*DELTA*(GAMMA+PHI*DELTA)*oo_irfs.g_gap_starr_eps_a_starr.^2 ...
                    +(1-h)*EPSILON/LAMBDA_starr*oo_irfs.pie_starr_eps_a_starr.^2 ...
                    +2*(1-DELTA)*PHI*oo_irfs.c_gap_cu_eps_a_starr.*oo_irfs.g_gap_cu_eps_a_starr ...
                    +2*ALPHA_bar*h*(1-h)*(1-DELTA)*DELTA*PHI*oo_irfs.s_gap_eps_a_starr.*oo_irfs.g_gap_r_eps_a_starr ...
                 ) ...
                );
    
elseif OBJECTIVE == "EQUAL_WEIGHT"
        
    Loss_CU = sum(cumprod(ones(1,T_irf)*BETA).* ...
                  ( ...
                    (1-DELTA)*(SIGMA+(1-DELTA)*PHI)*oo_irfs.c_gap_cu_eps_a_starr.^2 ...
                    +0.5*(1-0.5)*ALPHA_bar*(1-DELTA)*(1+PHI*(1-DELTA))*oo_irfs.s_gap_eps_a_starr.^2 ...
                    +0.5*DELTA*(GAMMA+PHI*DELTA)*oo_irfs.g_gap_eps_a_starr.^2 ...
                    +0.5*EPSILON/LAMBDA*oo_irfs.pie_eps_a_starr.^2 ...
                    +(1-0.5)*DELTA*(GAMMA+PHI*DELTA)*oo_irfs.g_gap_starr_eps_a_starr.^2 ...
                    +(1-0.5)*EPSILON/LAMBDA_starr*oo_irfs.pie_starr_eps_a_starr.^2 ...
                    +2*(1-DELTA)*PHI*oo_irfs.c_gap_cu_eps_a_starr.*oo_irfs.g_gap_cu_eps_a_starr ...
                    +2*ALPHA_bar*0.5*(1-0.5)*(1-DELTA)*DELTA*PHI*oo_irfs.s_gap_eps_a_starr.*oo_irfs.g_gap_r_eps_a_starr ...
                 ) ...
                );
    
 end
    
Loss_H = sum(cumprod(ones(1,T_irf)*BETA).* ...
                  ( ...
                    (1-DELTA)*(SIGMA+(1-DELTA)*PHI)*oo_irfs.c_gap_eps_a_starr.^2 ...
                    +ALPHA_bar*(1-h)*(1-DELTA)*(1+PHI*(1-DELTA))*oo_irfs.s_gap_eps_a_starr.^2 ...
                    +DELTA*(GAMMA+PHI*DELTA)*oo_irfs.g_gap_eps_a_starr.^2 ...
                    +EPSILON/LAMBDA*oo_irfs.pie_eps_a_starr.^2 ...
                    +2*(1-DELTA)*PHI*oo_irfs.c_gap_eps_a_starr.*oo_irfs.g_gap_eps_a_starr ...
                 ) ...
                );
    
    
Loss_F = sum(cumprod(ones(1,T_irf)*BETA).* ...
                  ( ...
                    (1-DELTA)*(SIGMA+(1-DELTA)*PHI)*oo_irfs.c_gap_starr_eps_a_starr.^2 ...
                    +ALPHA_bar*h*(1-DELTA)*(1+PHI*(1-DELTA))*oo_irfs.s_gap_starr_eps_a_starr.^2 ...
                    +DELTA*(GAMMA+PHI*DELTA)*oo_irfs.g_gap_starr_eps_a_starr.^2 ...
                    +EPSILON/LAMBDA_starr*oo_irfs.pie_starr_eps_a_starr.^2 ...
                    +2*(1-DELTA)*PHI*oo_irfs.c_gap_starr_eps_a_starr.*oo_irfs.g_gap_starr_eps_a_starr ...
                 ) ...
                );


if POLICY == "RAMSEY"

    Loss_RAMSEY_table=table([Loss_CU;Loss_H;Loss_F],'VariableNames',{'Loss_RAMSEY'},'RowNames',{'Union','Home','Foreign'});

    writetable(Loss_RAMSEY_table,folder_name+"/Loss_RAMSEY.csv","WriteRowNames",true)

elseif POLICY == "OSR"
    
    % Get the benchmark loss (need to run RAMSEY before)
    Loss_RAMSEY_table=readtable(benchmark_folder_name+"/Loss_RAMSEY.csv");
    
    % Build the alternative policy loss
    Loss_OSR_table=table([Loss_CU;Loss_H;Loss_F],'VariableNames',{'Loss_OSR'});

    % Concat the two loss
    CEV_table=horzcat(Loss_RAMSEY_table,Loss_OSR_table);

    % Add CEV
    CEV_table.CEV=sign(CEV_table.Loss_OSR-CEV_table.Loss_RAMSEY).*sqrt((1-BETA)/((1-DELTA)*(SIGMA+(1-DELTA)*PHI))*abs(CEV_table.Loss_OSR-CEV_table.Loss_RAMSEY))*100;
    
    % Save CEV
    writetable(CEV_table,folder_name+"/CEV.csv","WriteRowNames",true)

end

end