%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'MODEL_MAIN_3';
M_.dynare_version = '5.0';
oo_.dynare_version = '5.0';
options_.dynare_version = '5.0';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(2,1);
M_.exo_names_tex = cell(2,1);
M_.exo_names_long = cell(2,1);
M_.exo_names(1) = {'eps_a'};
M_.exo_names_tex(1) = {'{\epsilon_a}'};
M_.exo_names_long(1) = {'Home technology shock'};
M_.exo_names(2) = {'eps_a_starr'};
M_.exo_names_tex(2) = {'{\epsilon_a^*}'};
M_.exo_names_long(2) = {'Foreign technology shock'};
M_.endo_names = cell(51,1);
M_.endo_names_tex = cell(51,1);
M_.endo_names_long = cell(51,1);
M_.endo_names(1) = {'y_gap'};
M_.endo_names_tex(1) = {'{\tilde y_t}'};
M_.endo_names_long(1) = {'Home output gap (log dev ss)'};
M_.endo_names(2) = {'g_gap'};
M_.endo_names_tex(2) = {'{\tilde g_t}'};
M_.endo_names_long(2) = {'Home government spending gap (log dev ss)'};
M_.endo_names(3) = {'c_gap'};
M_.endo_names_tex(3) = {'{\tilde c_t}'};
M_.endo_names_long(3) = {'Home consumption gap (log dev ss)'};
M_.endo_names(4) = {'f_gap'};
M_.endo_names_tex(4) = {'{\tilde f_t}'};
M_.endo_names_long(4) = {'f_gap'};
M_.endo_names(5) = {'y_gap_starr'};
M_.endo_names_tex(5) = {'{\tilde y_t^*}'};
M_.endo_names_long(5) = {'Foreign output gap (log dev ss)'};
M_.endo_names(6) = {'g_gap_starr'};
M_.endo_names_tex(6) = {'{\tilde g_t^*}'};
M_.endo_names_long(6) = {'Foreign government spending gap (log dev ss)'};
M_.endo_names(7) = {'c_gap_starr'};
M_.endo_names_tex(7) = {'{\tilde c_t^*}'};
M_.endo_names_long(7) = {'Foreign consumption gap (log dev ss)'};
M_.endo_names(8) = {'f_gap_starr'};
M_.endo_names_tex(8) = {'{\tilde f_t^*}'};
M_.endo_names_long(8) = {'f_gap_starr'};
M_.endo_names(9) = {'s_gap'};
M_.endo_names_tex(9) = {'{\tilde s_t}'};
M_.endo_names_long(9) = {'Home terms of trade gap (log dev ss)'};
M_.endo_names(10) = {'y_gap_cu'};
M_.endo_names_tex(10) = {'{\tilde y_t^{cu}}'};
M_.endo_names_long(10) = {'Union output gap (log dev ss)'};
M_.endo_names(11) = {'g_gap_cu'};
M_.endo_names_tex(11) = {'{\tilde g_t^{cu}}'};
M_.endo_names_long(11) = {'Union government spending gap (log dev ss)'};
M_.endo_names(12) = {'c_gap_cu'};
M_.endo_names_tex(12) = {'{\tilde c_t^{cu}}'};
M_.endo_names_long(12) = {'Union government spending gap (log dev ss)'};
M_.endo_names(13) = {'a'};
M_.endo_names_tex(13) = {'{a_t}'};
M_.endo_names_long(13) = {'Home productivity (log dev ss)'};
M_.endo_names(14) = {'a_starr'};
M_.endo_names_tex(14) = {'{a_t^*}'};
M_.endo_names_long(14) = {'Foreign productivity (log dev ss)'};
M_.endo_names(15) = {'y_nat'};
M_.endo_names_tex(15) = {'{\hat {\bar y}_t}'};
M_.endo_names_long(15) = {'Home natural output (log dev ss)'};
M_.endo_names(16) = {'g_nat'};
M_.endo_names_tex(16) = {'{\hat {\bar g}_t}'};
M_.endo_names_long(16) = {'Home natural government spending (log dev ss)'};
M_.endo_names(17) = {'c_nat'};
M_.endo_names_tex(17) = {'{\hat {\bar c}_t}'};
M_.endo_names_long(17) = {'Home natural consumption (log dev ss)'};
M_.endo_names(18) = {'c_H_nat'};
M_.endo_names_tex(18) = {'{\hat {\bar c}_{H,t}}'};
M_.endo_names_long(18) = {'Home natural consumption of Home-made goods (log dev ss)'};
M_.endo_names(19) = {'c_F_nat'};
M_.endo_names_tex(19) = {'{\hat {\bar c}_{F,t}}'};
M_.endo_names_long(19) = {'Home natural consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(20) = {'r_nat'};
M_.endo_names_tex(20) = {'r\_nat'};
M_.endo_names_long(20) = {'r_nat'};
M_.endo_names(21) = {'y_nat_starr'};
M_.endo_names_tex(21) = {'{\hat {\bar y}_t^*}'};
M_.endo_names_long(21) = {'Foreign natural output (log dev ss)'};
M_.endo_names(22) = {'g_nat_starr'};
M_.endo_names_tex(22) = {'{\hat {\bar g}_t^*}'};
M_.endo_names_long(22) = {'Foreign natural government spending (log dev ss)'};
M_.endo_names(23) = {'c_nat_starr'};
M_.endo_names_tex(23) = {'{\hat {\bar c}_t^*}'};
M_.endo_names_long(23) = {'Foreign natural consumption (log dev ss)'};
M_.endo_names(24) = {'c_H_nat_starr'};
M_.endo_names_tex(24) = {'{\hat {\bar c}_{H,t}^*}'};
M_.endo_names_long(24) = {'Foreign natural consumption of Home-made goods (log dev ss)'};
M_.endo_names(25) = {'c_F_nat_starr'};
M_.endo_names_tex(25) = {'{\hat {\bar c}_{F,t}^*}'};
M_.endo_names_long(25) = {'Foreign natural consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(26) = {'r_nat_starr'};
M_.endo_names_tex(26) = {'r\_nat\_starr'};
M_.endo_names_long(26) = {'r_nat_starr'};
M_.endo_names(27) = {'s_nat'};
M_.endo_names_tex(27) = {'{\bar s_t}'};
M_.endo_names_long(27) = {'Home natural terms of trade (log dev ss)'};
M_.endo_names(28) = {'y_nat_cu'};
M_.endo_names_tex(28) = {'y\_nat\_cu'};
M_.endo_names_long(28) = {'y_nat_cu'};
M_.endo_names(29) = {'g_nat_cu'};
M_.endo_names_tex(29) = {'g\_nat\_cu'};
M_.endo_names_long(29) = {'g_nat_cu'};
M_.endo_names(30) = {'r_nat_cu'};
M_.endo_names_tex(30) = {'r\_nat\_cu'};
M_.endo_names_long(30) = {'r_nat_cu'};
M_.endo_names(31) = {'y'};
M_.endo_names_tex(31) = {'{\hat y_t}'};
M_.endo_names_long(31) = {'Home output (log dev ss)'};
M_.endo_names(32) = {'pie'};
M_.endo_names_tex(32) = {'{\pi_{H,t}}'};
M_.endo_names_long(32) = {'Home inflation (log dev ss)'};
M_.endo_names(33) = {'g'};
M_.endo_names_tex(33) = {'{\hat g_t}'};
M_.endo_names_long(33) = {'Home government consumption (log dev ss)'};
M_.endo_names(34) = {'n'};
M_.endo_names_tex(34) = {'{\hat n_t}'};
M_.endo_names_long(34) = {'Home labor supply (log dev ss)'};
M_.endo_names(35) = {'c'};
M_.endo_names_tex(35) = {'{\hat c_t}'};
M_.endo_names_long(35) = {'Home consumption (log dev ss)'};
M_.endo_names(36) = {'c_H'};
M_.endo_names_tex(36) = {'{\hat c_{H,t}}'};
M_.endo_names_long(36) = {'Home consumption of Home-made goods (log dev ss)'};
M_.endo_names(37) = {'c_F'};
M_.endo_names_tex(37) = {'{\hat c_{F,t}}'};
M_.endo_names_long(37) = {'Home consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(38) = {'y_starr'};
M_.endo_names_tex(38) = {'{\hat y_t^*}'};
M_.endo_names_long(38) = {'Foreign output (log dev ss)'};
M_.endo_names(39) = {'pie_starr'};
M_.endo_names_tex(39) = {'{\pi_{F,t}^*}'};
M_.endo_names_long(39) = {'Foreign inflation (log dev ss)'};
M_.endo_names(40) = {'g_starr'};
M_.endo_names_tex(40) = {'{\hat g_t^*}'};
M_.endo_names_long(40) = {'Foreign government consumption (log dev ss)'};
M_.endo_names(41) = {'n_starr'};
M_.endo_names_tex(41) = {'{\hat n_t^*}'};
M_.endo_names_long(41) = {'Foreign labor supply (log dev ss)'};
M_.endo_names(42) = {'c_starr'};
M_.endo_names_tex(42) = {'{\hat c_t^*}'};
M_.endo_names_long(42) = {'Foreign consumption (log dev ss)'};
M_.endo_names(43) = {'c_H_starr'};
M_.endo_names_tex(43) = {'{\hat c_{H,t}^*}'};
M_.endo_names_long(43) = {'Foreign consumption of Home-made goods (log dev ss)'};
M_.endo_names(44) = {'c_F_starr'};
M_.endo_names_tex(44) = {'{\hat c_{F,t}^*}'};
M_.endo_names_long(44) = {'Foreign consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(45) = {'ii'};
M_.endo_names_tex(45) = {'{i_t}'};
M_.endo_names_long(45) = {'Home union nominal interest rate (log dev ss)'};
M_.endo_names(46) = {'ii_starr'};
M_.endo_names_tex(46) = {'{i_t^*}'};
M_.endo_names_long(46) = {'Foreign union nominal interest rate (log dev ss)'};
M_.endo_names(47) = {'s'};
M_.endo_names_tex(47) = {'{s_t}'};
M_.endo_names_long(47) = {'Home terms of trade (log dev ss)'};
M_.endo_names(48) = {'pie_cu'};
M_.endo_names_tex(48) = {'{\pi_{cu,t}}'};
M_.endo_names_long(48) = {'Union inflation (log dev ss)'};
M_.endo_names(49) = {'y_cu'};
M_.endo_names_tex(49) = {'{\hat y_t^{cu}}'};
M_.endo_names_long(49) = {'Union output (log dev ss)'};
M_.endo_names(50) = {'g_cu'};
M_.endo_names_tex(50) = {'{\hat g_t^{cu}}'};
M_.endo_names_long(50) = {'Union government spending (log dev ss)'};
M_.endo_names(51) = {'c_cu'};
M_.endo_names_tex(51) = {'{\hat c_t^{cu}}'};
M_.endo_names_long(51) = {'Union consumption (log dev ss)'};
M_.endo_partitions = struct();
M_.param_names = cell(29,1);
M_.param_names_tex = cell(29,1);
M_.param_names_long = cell(29,1);
M_.param_names(1) = {'BETA'};
M_.param_names_tex(1) = {'BETA'};
M_.param_names_long(1) = {'BETA'};
M_.param_names(2) = {'SIGMA'};
M_.param_names_tex(2) = {'SIGMA'};
M_.param_names_long(2) = {'SIGMA'};
M_.param_names(3) = {'PHI'};
M_.param_names_tex(3) = {'PHI'};
M_.param_names_long(3) = {'PHI'};
M_.param_names(4) = {'GAMMA'};
M_.param_names_tex(4) = {'GAMMA'};
M_.param_names_long(4) = {'GAMMA'};
M_.param_names(5) = {'ETA'};
M_.param_names_tex(5) = {'ETA'};
M_.param_names_long(5) = {'ETA'};
M_.param_names(6) = {'EPSILON'};
M_.param_names_tex(6) = {'EPSILON'};
M_.param_names_long(6) = {'EPSILON'};
M_.param_names(7) = {'h'};
M_.param_names_tex(7) = {'h'};
M_.param_names_long(7) = {'h'};
M_.param_names(8) = {'ALPHA_bar'};
M_.param_names_tex(8) = {'ALPHA\_bar'};
M_.param_names_long(8) = {'ALPHA_bar'};
M_.param_names(9) = {'THETA'};
M_.param_names_tex(9) = {'THETA'};
M_.param_names_long(9) = {'THETA'};
M_.param_names(10) = {'THETA_starr'};
M_.param_names_tex(10) = {'THETA\_starr'};
M_.param_names_long(10) = {'THETA_starr'};
M_.param_names(11) = {'DELTA'};
M_.param_names_tex(11) = {'DELTA'};
M_.param_names_long(11) = {'DELTA'};
M_.param_names(12) = {'CHI_C'};
M_.param_names_tex(12) = {'CHI\_C'};
M_.param_names_long(12) = {'CHI_C'};
M_.param_names(13) = {'CHI_G'};
M_.param_names_tex(13) = {'CHI\_G'};
M_.param_names_long(13) = {'CHI_G'};
M_.param_names(14) = {'ALPHA'};
M_.param_names_tex(14) = {'ALPHA'};
M_.param_names_long(14) = {'ALPHA'};
M_.param_names(15) = {'ALPHA_starr'};
M_.param_names_tex(15) = {'ALPHA\_starr'};
M_.param_names_long(15) = {'ALPHA_starr'};
M_.param_names(16) = {'LAMBDA'};
M_.param_names_tex(16) = {'LAMBDA'};
M_.param_names_long(16) = {'LAMBDA'};
M_.param_names(17) = {'LAMBDA_starr'};
M_.param_names_tex(17) = {'LAMBDA\_starr'};
M_.param_names_long(17) = {'LAMBDA_starr'};
M_.param_names(18) = {'W_ALPHA_bar'};
M_.param_names_tex(18) = {'W\_ALPHA\_bar'};
M_.param_names_long(18) = {'W_ALPHA_bar'};
M_.param_names(19) = {'SIGMA_tilde'};
M_.param_names_tex(19) = {'SIGMA\_tilde'};
M_.param_names_long(19) = {'SIGMA_tilde'};
M_.param_names(20) = {'THETA_ALPHA_bar'};
M_.param_names_tex(20) = {'THETA\_ALPHA\_bar'};
M_.param_names_long(20) = {'THETA_ALPHA_bar'};
M_.param_names(21) = {'SIGMA_tilde_ALPHA_bar'};
M_.param_names_tex(21) = {'SIGMA\_tilde\_ALPHA\_bar'};
M_.param_names_long(21) = {'SIGMA_tilde_ALPHA_bar'};
M_.param_names(22) = {'OMEGA'};
M_.param_names_tex(22) = {'OMEGA'};
M_.param_names_long(22) = {'OMEGA'};
M_.param_names(23) = {'OMEGA_starr'};
M_.param_names_tex(23) = {'OMEGA\_starr'};
M_.param_names_long(23) = {'OMEGA_starr'};
M_.param_names(24) = {'MP_pieH'};
M_.param_names_tex(24) = {'MP\_pieH'};
M_.param_names_long(24) = {'MP_pieH'};
M_.param_names(25) = {'MP_pieF'};
M_.param_names_tex(25) = {'MP\_pieF'};
M_.param_names_long(25) = {'MP_pieF'};
M_.param_names(26) = {'MP_y_gapH'};
M_.param_names_tex(26) = {'MP\_y\_gapH'};
M_.param_names_long(26) = {'MP_y_gapH'};
M_.param_names(27) = {'MP_y_gapF'};
M_.param_names_tex(27) = {'MP\_y\_gapF'};
M_.param_names_long(27) = {'MP_y_gapF'};
M_.param_names(28) = {'MP_s_gap'};
M_.param_names_tex(28) = {'MP\_s\_gap'};
M_.param_names_long(28) = {'MP_s_gap'};
M_.param_names(29) = {'RHOA'};
M_.param_names_tex(29) = {'RHOA'};
M_.param_names_long(29) = {'RHOA'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 51;
M_.param_nbr = 29;
M_.orig_endo_nbr = 51;
M_.aux_vars = [];
options_.varobs = cell(28, 1);
options_.varobs(1)  = {'y_gap'};
options_.varobs(2)  = {'y_nat'};
options_.varobs(3)  = {'g_gap'};
options_.varobs(4)  = {'g_nat'};
options_.varobs(5)  = {'c_gap'};
options_.varobs(6)  = {'c_nat'};
options_.varobs(7)  = {'pie'};
options_.varobs(8)  = {'c_F'};
options_.varobs(9)  = {'c_F_nat'};
options_.varobs(10)  = {'c_H'};
options_.varobs(11)  = {'c_H_nat'};
options_.varobs(12)  = {'y_gap_starr'};
options_.varobs(13)  = {'y_nat_starr'};
options_.varobs(14)  = {'g_gap_starr'};
options_.varobs(15)  = {'g_nat_starr'};
options_.varobs(16)  = {'c_gap_starr'};
options_.varobs(17)  = {'c_nat_starr'};
options_.varobs(18)  = {'pie_starr'};
options_.varobs(19)  = {'c_F_starr'};
options_.varobs(20)  = {'c_F_nat_starr'};
options_.varobs(21)  = {'c_H_starr'};
options_.varobs(22)  = {'c_H_nat_starr'};
options_.varobs(23)  = {'y_gap_cu'};
options_.varobs(24)  = {'g_gap_cu'};
options_.varobs(25)  = {'pie_cu'};
options_.varobs(26)  = {'s_gap'};
options_.varobs(27)  = {'s_nat'};
options_.varobs(28)  = {'ii'};
options_.varobs_id = [ 1 15 2 16 3 17 32 37 19 36 18 5 21 6 22 7 23 39 44 25 43 24 10 11 48 9 27 45  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(2, 2);
M_.Correlation_matrix = eye(2, 2);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 51;
M_.eq_nbr = 51;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 4 0;
 0 5 0;
 0 6 0;
 0 7 0;
 0 8 0;
 0 9 0;
 0 10 0;
 0 11 0;
 0 12 0;
 0 13 0;
 0 14 0;
 0 15 0;
 1 16 55;
 2 17 56;
 0 18 57;
 0 19 0;
 0 20 0;
 0 21 0;
 0 22 0;
 0 23 0;
 0 24 58;
 0 25 0;
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 0 34 59;
 0 35 60;
 0 36 61;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 62;
 0 42 63;
 0 43 64;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 0;
 0 49 0;
 3 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;]';
M_.nstatic = 40;
M_.nfwrd   = 8;
M_.npred   = 1;
M_.nboth   = 2;
M_.nsfwrd   = 10;
M_.nspred   = 3;
M_.ndynamic   = 11;
M_.dynamic_tmp_nbr = [2; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Home natural marginal cost condition' ;
  2 , 'name' , 'Foreign natural marginal cost condition' ;
  3 , 'name' , 'Home natural good-market clearing condition' ;
  4 , 'name' , 'Foreign natural good-market clearing condition' ;
  5 , 'name' , 'Natural IRS condition' ;
  6 , 'name' , 'Home natural government spending condition' ;
  7 , 'name' , 'Foreign natural government spending condition' ;
  8 , 'name' , 'Home natural consumption of Home-made goods' ;
  9 , 'name' , 'Home natural consumption of Foreign-made goods' ;
  10 , 'name' , 'Foreign natural consumption of Home-made goods' ;
  11 , 'name' , 'Foreign natural consumption of Foreign-made goods' ;
  12 , 'name' , 'Home natural rate' ;
  13 , 'name' , 'Foreign natural rate' ;
  14 , 'name' , 'y_nat_cu' ;
  15 , 'name' , 'g_nat_cu' ;
  16 , 'name' , 'r_nat_cu' ;
  17 , 'name' , 'Home Dynamic IS Curve' ;
  18 , 'name' , 'Home New Keynesian Phillips Curve' ;
  19 , 'name' , 'Foreign Dynamic IS Curve' ;
  20 , 'name' , 'Foreign New Keynesian Phillips Curve' ;
  21 , 'name' , 'IRS' ;
  22 , 'name' , 'Home production function' ;
  23 , 'name' , 'Foreign production function' ;
  24 , 'name' , 'Home good-market clearing condition' ;
  25 , 'name' , 'Home consumption of Home-made goods' ;
  26 , 'name' , 'Home consumption of Foreign-made goods' ;
  27 , 'name' , 'Foreign good-market clearing condition' ;
  28 , 'name' , 'Foreign consumption of Home-made goods' ;
  29 , 'name' , 'Foreign consumption of Foreign-made goods' ;
  30 , 'name' , 'Union inflation' ;
  31 , 'name' , 'Union output' ;
  32 , 'name' , 'Union government spending' ;
  33 , 'name' , 'Union consumption' ;
  34 , 'name' , 'Home government spending rule' ;
  35 , 'name' , 'Foreign government spending rule' ;
  36 , 'name' , 'ii' ;
  37 , 'name' , 'ii_starr' ;
  38 , 'name' , 'Home output gap definition' ;
  39 , 'name' , 'Home governmpent spending gap definition' ;
  40 , 'name' , 'Home consumption gap definition' ;
  41 , 'name' , 'f_gap' ;
  42 , 'name' , 'Foreign output gap definition' ;
  43 , 'name' , 'Foreign governmpent spending gap definition' ;
  44 , 'name' , 'Foreign consumption gap definition' ;
  45 , 'name' , 'f_gap_starr' ;
  46 , 'name' , 'Home terms of trade gap definition' ;
  47 , 'name' , 'Union output gap definition' ;
  48 , 'name' , 'Union governmpent spending gap definition' ;
  49 , 'name' , 'Union consumption gap definition' ;
  50 , 'name' , 'a' ;
  51 , 'name' , 'a_starr' ;
};
M_.mapping.y_gap.eqidx = [38 41 47 ];
M_.mapping.g_gap.eqidx = [39 41 48 ];
M_.mapping.c_gap.eqidx = [40 49 ];
M_.mapping.f_gap.eqidx = [41 ];
M_.mapping.y_gap_starr.eqidx = [42 45 47 ];
M_.mapping.g_gap_starr.eqidx = [43 45 48 ];
M_.mapping.c_gap_starr.eqidx = [44 49 ];
M_.mapping.f_gap_starr.eqidx = [45 ];
M_.mapping.s_gap.eqidx = [46 ];
M_.mapping.y_gap_cu.eqidx = [47 ];
M_.mapping.g_gap_cu.eqidx = [48 ];
M_.mapping.c_gap_cu.eqidx = [49 ];
M_.mapping.a.eqidx = [1 12 18 22 50 ];
M_.mapping.a_starr.eqidx = [2 13 20 23 51 ];
M_.mapping.eps_a.eqidx = [50 ];
M_.mapping.eps_a_starr.eqidx = [51 ];
M_.mapping.y_nat.eqidx = [1 3 5 12 14 38 ];
M_.mapping.g_nat.eqidx = [3 5 6 15 39 ];
M_.mapping.c_nat.eqidx = [1 3 6 8 9 40 ];
M_.mapping.c_H_nat.eqidx = [8 ];
M_.mapping.c_F_nat.eqidx = [9 ];
M_.mapping.r_nat.eqidx = [12 16 ];
M_.mapping.y_nat_starr.eqidx = [2 4 5 13 14 42 ];
M_.mapping.g_nat_starr.eqidx = [4 5 7 15 43 ];
M_.mapping.c_nat_starr.eqidx = [2 4 7 10 11 44 ];
M_.mapping.c_H_nat_starr.eqidx = [10 ];
M_.mapping.c_F_nat_starr.eqidx = [11 ];
M_.mapping.r_nat_starr.eqidx = [13 16 ];
M_.mapping.s_nat.eqidx = [1 2 3 4 5 6 7 8 9 10 11 46 ];
M_.mapping.y_nat_cu.eqidx = [14 ];
M_.mapping.g_nat_cu.eqidx = [15 ];
M_.mapping.r_nat_cu.eqidx = [16 36 ];
M_.mapping.y.eqidx = [17 18 19 20 21 22 24 31 38 ];
M_.mapping.pie.eqidx = [17 18 30 ];
M_.mapping.g.eqidx = [17 18 19 20 21 24 32 34 39 ];
M_.mapping.n.eqidx = [22 ];
M_.mapping.c.eqidx = [24 25 26 33 34 40 ];
M_.mapping.c_H.eqidx = [25 ];
M_.mapping.c_F.eqidx = [26 ];
M_.mapping.y_starr.eqidx = [17 18 19 20 21 23 27 31 42 ];
M_.mapping.pie_starr.eqidx = [19 20 ];
M_.mapping.g_starr.eqidx = [17 18 19 20 21 27 32 35 43 ];
M_.mapping.n_starr.eqidx = [23 ];
M_.mapping.c_starr.eqidx = [27 28 29 33 35 44 ];
M_.mapping.c_H_starr.eqidx = [28 ];
M_.mapping.c_F_starr.eqidx = [29 ];
M_.mapping.ii.eqidx = [17 36 37 ];
M_.mapping.ii_starr.eqidx = [19 37 ];
M_.mapping.s.eqidx = [21 24 25 26 27 28 29 30 34 35 46 ];
M_.mapping.pie_cu.eqidx = [30 ];
M_.mapping.y_cu.eqidx = [31 ];
M_.mapping.g_cu.eqidx = [32 ];
M_.mapping.c_cu.eqidx = [33 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [13 14 47 ];
M_.exo_names_orig_ord = [1:2];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(51, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = NaN(29, 1);
M_.endo_trends = struct('deflator', cell(51, 1), 'log_deflator', cell(51, 1), 'growth_factor', cell(51, 1), 'log_growth_factor', cell(51, 1));
M_.NNZDerivatives = [188; 0; -1; ];
M_.static_tmp_nbr = [0; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
M_.Sigma_e(2, 2) = 1;
M_.params(1) = 0.98;
BETA = M_.params(1);
M_.params(2) = 3;
SIGMA = M_.params(2);
M_.params(3) = 1;
PHI = M_.params(3);
M_.params(4) = 1;
GAMMA = M_.params(4);
M_.params(5) = 4.5;
ETA = M_.params(5);
M_.params(6) = 6;
EPSILON = M_.params(6);
M_.params(7) = 0.5;
h = M_.params(7);
M_.params(8) = 0.1;
ALPHA_bar = M_.params(8);
M_.params(9) = 0.75;
THETA = M_.params(9);
M_.params(10) = 0.75;
THETA_starr = M_.params(10);
M_.params(11) = 0.1;
DELTA = M_.params(11);
M_.params(12) = (1-M_.params(11))^M_.params(2);
CHI_C = M_.params(12);
M_.params(13) = M_.params(11)^M_.params(4);
CHI_G = M_.params(13);
M_.params(14) = M_.params(8)*(1-M_.params(7));
ALPHA = M_.params(14);
M_.params(15) = M_.params(8)*M_.params(7);
ALPHA_starr = M_.params(15);
M_.params(16) = (1-M_.params(9))*(1-M_.params(9)*M_.params(1))/M_.params(9);
LAMBDA = M_.params(16);
M_.params(17) = (1-M_.params(10))*(1-M_.params(1)*M_.params(10))/M_.params(10);
LAMBDA_starr = M_.params(17);
M_.params(18) = 1+(2-M_.params(8))*(M_.params(2)*M_.params(5)-1);
W_ALPHA_bar = M_.params(18);
M_.params(19) = M_.params(2)/(1-M_.params(11));
SIGMA_tilde = M_.params(19);
M_.params(20) = M_.params(18)-1;
THETA_ALPHA_bar = M_.params(20);
M_.params(21) = M_.params(19)/(1+M_.params(8)*M_.params(20));
SIGMA_tilde_ALPHA_bar = M_.params(21);
M_.params(22) = 1+M_.params(8)*M_.params(7)*M_.params(20);
OMEGA = M_.params(22);
M_.params(23) = 1+M_.params(8)*(1-M_.params(7))*M_.params(20);
OMEGA_starr = M_.params(23);
M_.params(29) = 0.85;
RHOA = M_.params(29);
M_.params(24) = 1.5;
MP_pieH = M_.params(24);
M_.params(25) = 1.5;
MP_pieF = M_.params(25);
M_.params(26) = 0.5;
MP_y_gapH = M_.params(26);
M_.params(27) = 0.5;
MP_y_gapF = M_.params(27);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 24, 1.5, (-10), 10, 0, NaN, NaN, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 25, 1.5, (-10), 10, 0, NaN, NaN, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 26, 0.5, (-10), 10, 0, NaN, NaN, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 27, 0.5, (-10), 10, 0, NaN, NaN, NaN, NaN, NaN ];
options_.varobs = M_.endo_names; 
options_gsa = struct();
dynare_sensitivity(options_gsa);
%
% OPTIM_WEIGHTS
%
M_.osr.variable_weights = sparse(M_.endo_nbr,M_.endo_nbr);
M_.osr.variable_indices = [];

M_.osr.variable_weights(3,3) = (1-M_.params(11))*M_.params(2);
M_.osr.variable_indices = [M_.osr.variable_indices; 3];
M_.osr.variable_weights(7,7) = (1-M_.params(11))*M_.params(2);
M_.osr.variable_indices = [M_.osr.variable_indices; 7];
M_.osr.variable_weights(2,2) = M_.params(11)*M_.params(4);
M_.osr.variable_indices = [M_.osr.variable_indices; 2];
M_.osr.variable_weights(6,6) = M_.params(11)*M_.params(4);
M_.osr.variable_indices = [M_.osr.variable_indices; 6];
M_.osr.variable_weights(32,32) = M_.params(6)/M_.params(16);
M_.osr.variable_indices = [M_.osr.variable_indices; 32];
M_.osr.variable_weights(39,39) = M_.params(6)/M_.params(16);
M_.osr.variable_indices = [M_.osr.variable_indices; 39];
M_.osr.variable_weights(1,1) = M_.params(3);
M_.osr.variable_indices = [M_.osr.variable_indices; 1];
M_.osr.variable_weights(5,5) = M_.params(3);
M_.osr.variable_indices = [M_.osr.variable_indices; 5];
M_.osr.param_names = {'MP_pieH';'MP_pieF';'MP_y_gapH';'MP_y_gapF'};
M_.osr.param_names = cellstr(M_.osr.param_names);
M_.osr.param_indices = zeros(length(M_.osr.param_names), 1);
M_.osr.param_indices(1) = 24;
M_.osr.param_indices(2) = 25;
M_.osr.param_indices(3) = 26;
M_.osr.param_indices(4) = 27;
options_.TeX = true;
options_.irf = 30;
options_.osr.opt_algo = 9;
var_list_ = {'y_gap';'y_nat';'g_gap';'g_nat';'c_gap';'c_nat';'pie';'c_F';'c_H';'y_gap_starr';'y_nat_starr';'g_gap_starr';'g_nat_starr';'c_gap_starr';'c_nat_starr';'pie_starr';'c_F_starr';'c_H_starr';'y_gap_cu';'g_gap_cu';'pie_cu';'s_gap';'s_nat';'ii'};
oo_.osr = osr(var_list_,M_.osr.param_names,M_.osr.variable_indices,M_.osr.variable_weights);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_3_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_3_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_3_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_3_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_3_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_3_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_3_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
