%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'MODEL_MAIN';
M_.dynare_version = '5.0';
oo_.dynare_version = '5.0';
options_.dynare_version = '5.0';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(4,1);
M_.exo_names_tex = cell(4,1);
M_.exo_names_long = cell(4,1);
M_.exo_names(1) = {'eps_a'};
M_.exo_names_tex(1) = {'{\varepsilon_a}'};
M_.exo_names_long(1) = {'technology shock'};
M_.exo_names(2) = {'eps_xi'};
M_.exo_names_tex(2) = {'{\varepsilon_xi}'};
M_.exo_names_long(2) = {'labor disutility shock'};
M_.exo_names(3) = {'eps_a_starr'};
M_.exo_names_tex(3) = {'eps\_a\_starr'};
M_.exo_names_long(3) = {'eps_a_starr'};
M_.exo_names(4) = {'eps_xi_starr'};
M_.exo_names_tex(4) = {'eps\_xi\_starr'};
M_.exo_names_long(4) = {'eps_xi_starr'};
M_.endo_names = cell(83,1);
M_.endo_names_tex = cell(83,1);
M_.endo_names_long = cell(83,1);
M_.endo_names(1) = {'y_gap'};
M_.endo_names_tex(1) = {'{\tilde y_t}'};
M_.endo_names_long(1) = {'Home output gap (log dev ss)'};
M_.endo_names(2) = {'g_gap'};
M_.endo_names_tex(2) = {'{\tilde g_t}'};
M_.endo_names_long(2) = {'Home government spending gap (log dev ss)'};
M_.endo_names(3) = {'c_gap'};
M_.endo_names_tex(3) = {'{\tilde c_t}'};
M_.endo_names_long(3) = {'Home consumption gap (log dev ss)'};
M_.endo_names(4) = {'y_gap_starr'};
M_.endo_names_tex(4) = {'{\tilde y_t^*}'};
M_.endo_names_long(4) = {'Foreign output gap (log dev ss)'};
M_.endo_names(5) = {'g_gap_starr'};
M_.endo_names_tex(5) = {'{\tilde g_t^*}'};
M_.endo_names_long(5) = {'Foreign government spending gap (log dev ss)'};
M_.endo_names(6) = {'c_gap_starr'};
M_.endo_names_tex(6) = {'{\tilde c_t^*}'};
M_.endo_names_long(6) = {'Foreign consumption gap (log dev ss)'};
M_.endo_names(7) = {'s_gap'};
M_.endo_names_tex(7) = {'{\tilde s_t}'};
M_.endo_names_long(7) = {'Home terms of trade gap (log dev ss)'};
M_.endo_names(8) = {'y_gap_cu'};
M_.endo_names_tex(8) = {'{\tilde y_{cu,t}}'};
M_.endo_names_long(8) = {'Currency union output gap (log dev ss)'};
M_.endo_names(9) = {'g_gap_cu'};
M_.endo_names_tex(9) = {'{\tilde g_{cu,t}}'};
M_.endo_names_long(9) = {'Currency government spending gap (log dev ss)'};
M_.endo_names(10) = {'a'};
M_.endo_names_tex(10) = {'{a_t}'};
M_.endo_names_long(10) = {'Home productivity (log dev ss)'};
M_.endo_names(11) = {'xi'};
M_.endo_names_tex(11) = {'{\xi_t}'};
M_.endo_names_long(11) = {'Home labor disutility (log dev ss)'};
M_.endo_names(12) = {'a_starr'};
M_.endo_names_tex(12) = {'{a_t^*}'};
M_.endo_names_long(12) = {'Foreign productivity (log dev ss)'};
M_.endo_names(13) = {'xi_starr'};
M_.endo_names_tex(13) = {'{\xi_t^*}'};
M_.endo_names_long(13) = {'Foreign labor disutility (log dev ss)'};
M_.endo_names(14) = {'y_nat'};
M_.endo_names_tex(14) = {'{\hat {\bar y}_t}'};
M_.endo_names_long(14) = {'Home natural output (log dev ss)'};
M_.endo_names(15) = {'g_nat'};
M_.endo_names_tex(15) = {'{\hat {\bar g}_t}'};
M_.endo_names_long(15) = {'Home natural government spending (log dev ss)'};
M_.endo_names(16) = {'c_nat'};
M_.endo_names_tex(16) = {'{\hat {\bar c}_t}'};
M_.endo_names_long(16) = {'Home natural consumption (log dev ss)'};
M_.endo_names(17) = {'c_H_nat'};
M_.endo_names_tex(17) = {'{\hat {\bar c}_{H,t}}'};
M_.endo_names_long(17) = {'Home natural consumption of Home-made goods (log dev ss)'};
M_.endo_names(18) = {'c_F_nat'};
M_.endo_names_tex(18) = {'{\hat {\bar c}_{F,t}}'};
M_.endo_names_long(18) = {'Home natural consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(19) = {'y_nat_starr'};
M_.endo_names_tex(19) = {'{\hat {\bar y}_t^*}'};
M_.endo_names_long(19) = {'Foreign natural output (log dev ss)'};
M_.endo_names(20) = {'g_nat_starr'};
M_.endo_names_tex(20) = {'{\hat {\bar g}_t^*}'};
M_.endo_names_long(20) = {'Foreign natural government spending (log dev ss)'};
M_.endo_names(21) = {'c_nat_starr'};
M_.endo_names_tex(21) = {'{\hat {\bar c}_t^*}'};
M_.endo_names_long(21) = {'Foreign natural consumption (log dev ss)'};
M_.endo_names(22) = {'c_H_nat_starr'};
M_.endo_names_tex(22) = {'{\hat {\bar c}_{H,t}^*}'};
M_.endo_names_long(22) = {'Foreign natural consumption of Home-made goods (log dev ss)'};
M_.endo_names(23) = {'c_F_nat_starr'};
M_.endo_names_tex(23) = {'{\hat {\bar c}_{F,t}^*}'};
M_.endo_names_long(23) = {'Foreign natural consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(24) = {'s_nat'};
M_.endo_names_tex(24) = {'{\bar s_t}'};
M_.endo_names_long(24) = {'Home natural terms of trade (log dev ss)'};
M_.endo_names(25) = {'y'};
M_.endo_names_tex(25) = {'{\hat y_t}'};
M_.endo_names_long(25) = {'Home output (log dev ss)'};
M_.endo_names(26) = {'pie'};
M_.endo_names_tex(26) = {'{\pi_t}'};
M_.endo_names_long(26) = {'Home inflation (log dev ss)'};
M_.endo_names(27) = {'g'};
M_.endo_names_tex(27) = {'{\hat g_t}'};
M_.endo_names_long(27) = {'Home government consumption (log dev ss)'};
M_.endo_names(28) = {'n'};
M_.endo_names_tex(28) = {'{\hat n_t}'};
M_.endo_names_long(28) = {'Home labor supply (log dev ss)'};
M_.endo_names(29) = {'c'};
M_.endo_names_tex(29) = {'{\hat c_t}'};
M_.endo_names_long(29) = {'Home consumption (log dev ss)'};
M_.endo_names(30) = {'c_H'};
M_.endo_names_tex(30) = {'{\hat c_{H,t}}'};
M_.endo_names_long(30) = {'Home consumption of Home-made goods (log dev ss)'};
M_.endo_names(31) = {'c_F'};
M_.endo_names_tex(31) = {'{\hat c_{F,t}}'};
M_.endo_names_long(31) = {'Home consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(32) = {'y_starr'};
M_.endo_names_tex(32) = {'{\hat y_t^*}'};
M_.endo_names_long(32) = {'Foreign output (log dev ss)'};
M_.endo_names(33) = {'pie_starr'};
M_.endo_names_tex(33) = {'{\pi_t^*}'};
M_.endo_names_long(33) = {'Foreign inflation (log dev ss)'};
M_.endo_names(34) = {'g_starr'};
M_.endo_names_tex(34) = {'{\hat g_t^*}'};
M_.endo_names_long(34) = {'Foreign government consumption (log dev ss)'};
M_.endo_names(35) = {'n_starr'};
M_.endo_names_tex(35) = {'{\hat n_t^*}'};
M_.endo_names_long(35) = {'Foreign labor supply (log dev ss)'};
M_.endo_names(36) = {'c_starr'};
M_.endo_names_tex(36) = {'{\hat c_t^*}'};
M_.endo_names_long(36) = {'Foreign consumption (log dev ss)'};
M_.endo_names(37) = {'c_H_starr'};
M_.endo_names_tex(37) = {'{\hat c_{H,t}^*}'};
M_.endo_names_long(37) = {'Foreign consumption of Home-made goods (log dev ss)'};
M_.endo_names(38) = {'c_F_starr'};
M_.endo_names_tex(38) = {'{\hat c_{F,t}^*}'};
M_.endo_names_long(38) = {'Foreign consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(39) = {'ii'};
M_.endo_names_tex(39) = {'{i_t}'};
M_.endo_names_long(39) = {'Currency union nominal interest rate (log dev ss)'};
M_.endo_names(40) = {'s'};
M_.endo_names_tex(40) = {'{s_t}'};
M_.endo_names_long(40) = {'Home terms of trade (log dev ss)'};
M_.endo_names(41) = {'pie_cu'};
M_.endo_names_tex(41) = {'{\pi_{cu,t}}'};
M_.endo_names_long(41) = {'Currency union inflation (log dev ss)'};
M_.endo_names(42) = {'y_cu'};
M_.endo_names_tex(42) = {'{\hat y_{cu,t}}'};
M_.endo_names_long(42) = {'Currency union output (log dev ss)'};
M_.endo_names(43) = {'g_cu'};
M_.endo_names_tex(43) = {'{\hat g_{cu,t}}'};
M_.endo_names_long(43) = {'Currency union government spending (log dev ss)'};
M_.endo_names(44) = {'MULT_1'};
M_.endo_names_tex(44) = {'MULT\_1'};
M_.endo_names_long(44) = {'MULT_1'};
M_.endo_names(45) = {'MULT_2'};
M_.endo_names_tex(45) = {'MULT\_2'};
M_.endo_names_long(45) = {'MULT_2'};
M_.endo_names(46) = {'MULT_3'};
M_.endo_names_tex(46) = {'MULT\_3'};
M_.endo_names_long(46) = {'MULT_3'};
M_.endo_names(47) = {'MULT_4'};
M_.endo_names_tex(47) = {'MULT\_4'};
M_.endo_names_long(47) = {'MULT_4'};
M_.endo_names(48) = {'MULT_5'};
M_.endo_names_tex(48) = {'MULT\_5'};
M_.endo_names_long(48) = {'MULT_5'};
M_.endo_names(49) = {'MULT_6'};
M_.endo_names_tex(49) = {'MULT\_6'};
M_.endo_names_long(49) = {'MULT_6'};
M_.endo_names(50) = {'MULT_7'};
M_.endo_names_tex(50) = {'MULT\_7'};
M_.endo_names_long(50) = {'MULT_7'};
M_.endo_names(51) = {'MULT_8'};
M_.endo_names_tex(51) = {'MULT\_8'};
M_.endo_names_long(51) = {'MULT_8'};
M_.endo_names(52) = {'MULT_9'};
M_.endo_names_tex(52) = {'MULT\_9'};
M_.endo_names_long(52) = {'MULT_9'};
M_.endo_names(53) = {'MULT_10'};
M_.endo_names_tex(53) = {'MULT\_10'};
M_.endo_names_long(53) = {'MULT_10'};
M_.endo_names(54) = {'MULT_11'};
M_.endo_names_tex(54) = {'MULT\_11'};
M_.endo_names_long(54) = {'MULT_11'};
M_.endo_names(55) = {'MULT_12'};
M_.endo_names_tex(55) = {'MULT\_12'};
M_.endo_names_long(55) = {'MULT_12'};
M_.endo_names(56) = {'MULT_13'};
M_.endo_names_tex(56) = {'MULT\_13'};
M_.endo_names_long(56) = {'MULT_13'};
M_.endo_names(57) = {'MULT_14'};
M_.endo_names_tex(57) = {'MULT\_14'};
M_.endo_names_long(57) = {'MULT_14'};
M_.endo_names(58) = {'MULT_15'};
M_.endo_names_tex(58) = {'MULT\_15'};
M_.endo_names_long(58) = {'MULT_15'};
M_.endo_names(59) = {'MULT_16'};
M_.endo_names_tex(59) = {'MULT\_16'};
M_.endo_names_long(59) = {'MULT_16'};
M_.endo_names(60) = {'MULT_17'};
M_.endo_names_tex(60) = {'MULT\_17'};
M_.endo_names_long(60) = {'MULT_17'};
M_.endo_names(61) = {'MULT_18'};
M_.endo_names_tex(61) = {'MULT\_18'};
M_.endo_names_long(61) = {'MULT_18'};
M_.endo_names(62) = {'MULT_19'};
M_.endo_names_tex(62) = {'MULT\_19'};
M_.endo_names_long(62) = {'MULT_19'};
M_.endo_names(63) = {'MULT_20'};
M_.endo_names_tex(63) = {'MULT\_20'};
M_.endo_names_long(63) = {'MULT_20'};
M_.endo_names(64) = {'MULT_21'};
M_.endo_names_tex(64) = {'MULT\_21'};
M_.endo_names_long(64) = {'MULT_21'};
M_.endo_names(65) = {'MULT_22'};
M_.endo_names_tex(65) = {'MULT\_22'};
M_.endo_names_long(65) = {'MULT_22'};
M_.endo_names(66) = {'MULT_23'};
M_.endo_names_tex(66) = {'MULT\_23'};
M_.endo_names_long(66) = {'MULT_23'};
M_.endo_names(67) = {'MULT_24'};
M_.endo_names_tex(67) = {'MULT\_24'};
M_.endo_names_long(67) = {'MULT_24'};
M_.endo_names(68) = {'MULT_25'};
M_.endo_names_tex(68) = {'MULT\_25'};
M_.endo_names_long(68) = {'MULT_25'};
M_.endo_names(69) = {'MULT_26'};
M_.endo_names_tex(69) = {'MULT\_26'};
M_.endo_names_long(69) = {'MULT_26'};
M_.endo_names(70) = {'MULT_27'};
M_.endo_names_tex(70) = {'MULT\_27'};
M_.endo_names_long(70) = {'MULT_27'};
M_.endo_names(71) = {'MULT_28'};
M_.endo_names_tex(71) = {'MULT\_28'};
M_.endo_names_long(71) = {'MULT_28'};
M_.endo_names(72) = {'MULT_29'};
M_.endo_names_tex(72) = {'MULT\_29'};
M_.endo_names_long(72) = {'MULT_29'};
M_.endo_names(73) = {'MULT_30'};
M_.endo_names_tex(73) = {'MULT\_30'};
M_.endo_names_long(73) = {'MULT_30'};
M_.endo_names(74) = {'MULT_31'};
M_.endo_names_tex(74) = {'MULT\_31'};
M_.endo_names_long(74) = {'MULT_31'};
M_.endo_names(75) = {'MULT_32'};
M_.endo_names_tex(75) = {'MULT\_32'};
M_.endo_names_long(75) = {'MULT_32'};
M_.endo_names(76) = {'MULT_33'};
M_.endo_names_tex(76) = {'MULT\_33'};
M_.endo_names_long(76) = {'MULT_33'};
M_.endo_names(77) = {'MULT_34'};
M_.endo_names_tex(77) = {'MULT\_34'};
M_.endo_names_long(77) = {'MULT_34'};
M_.endo_names(78) = {'MULT_35'};
M_.endo_names_tex(78) = {'MULT\_35'};
M_.endo_names_long(78) = {'MULT_35'};
M_.endo_names(79) = {'MULT_36'};
M_.endo_names_tex(79) = {'MULT\_36'};
M_.endo_names_long(79) = {'MULT_36'};
M_.endo_names(80) = {'MULT_37'};
M_.endo_names_tex(80) = {'MULT\_37'};
M_.endo_names_long(80) = {'MULT_37'};
M_.endo_names(81) = {'MULT_38'};
M_.endo_names_tex(81) = {'MULT\_38'};
M_.endo_names_long(81) = {'MULT_38'};
M_.endo_names(82) = {'MULT_39'};
M_.endo_names_tex(82) = {'MULT\_39'};
M_.endo_names_long(82) = {'MULT_39'};
M_.endo_names(83) = {'MULT_40'};
M_.endo_names_tex(83) = {'MULT\_40'};
M_.endo_names_long(83) = {'MULT_40'};
M_.endo_partitions = struct();
M_.param_names = cell(23,1);
M_.param_names_tex = cell(23,1);
M_.param_names_long = cell(23,1);
M_.param_names(1) = {'BETA'};
M_.param_names_tex(1) = {'BETA'};
M_.param_names_long(1) = {'BETA'};
M_.param_names(2) = {'SIGMA'};
M_.param_names_tex(2) = {'SIGMA'};
M_.param_names_long(2) = {'SIGMA'};
M_.param_names(3) = {'PHI'};
M_.param_names_tex(3) = {'PHI'};
M_.param_names_long(3) = {'PHI'};
M_.param_names(4) = {'GAMMA'};
M_.param_names_tex(4) = {'GAMMA'};
M_.param_names_long(4) = {'GAMMA'};
M_.param_names(5) = {'ETA'};
M_.param_names_tex(5) = {'ETA'};
M_.param_names_long(5) = {'ETA'};
M_.param_names(6) = {'EPSILON'};
M_.param_names_tex(6) = {'EPSILON'};
M_.param_names_long(6) = {'EPSILON'};
M_.param_names(7) = {'h'};
M_.param_names_tex(7) = {'h'};
M_.param_names_long(7) = {'h'};
M_.param_names(8) = {'ALPHA_bar'};
M_.param_names_tex(8) = {'ALPHA\_bar'};
M_.param_names_long(8) = {'ALPHA_bar'};
M_.param_names(9) = {'THETA'};
M_.param_names_tex(9) = {'THETA'};
M_.param_names_long(9) = {'THETA'};
M_.param_names(10) = {'THETA_starr'};
M_.param_names_tex(10) = {'THETA\_starr'};
M_.param_names_long(10) = {'THETA_starr'};
M_.param_names(11) = {'DELTA'};
M_.param_names_tex(11) = {'DELTA'};
M_.param_names_long(11) = {'DELTA'};
M_.param_names(12) = {'CHI_C'};
M_.param_names_tex(12) = {'CHI\_C'};
M_.param_names_long(12) = {'CHI_C'};
M_.param_names(13) = {'CHI_G'};
M_.param_names_tex(13) = {'CHI\_G'};
M_.param_names_long(13) = {'CHI_G'};
M_.param_names(14) = {'ALPHA'};
M_.param_names_tex(14) = {'ALPHA'};
M_.param_names_long(14) = {'ALPHA'};
M_.param_names(15) = {'ALPHA_starr'};
M_.param_names_tex(15) = {'ALPHA\_starr'};
M_.param_names_long(15) = {'ALPHA_starr'};
M_.param_names(16) = {'LAMBDA'};
M_.param_names_tex(16) = {'LAMBDA'};
M_.param_names_long(16) = {'LAMBDA'};
M_.param_names(17) = {'LAMBDA_starr'};
M_.param_names_tex(17) = {'LAMBDA\_starr'};
M_.param_names_long(17) = {'LAMBDA_starr'};
M_.param_names(18) = {'W_ALPHA_bar'};
M_.param_names_tex(18) = {'W\_ALPHA\_bar'};
M_.param_names_long(18) = {'W_ALPHA_bar'};
M_.param_names(19) = {'SIGMA_tilde'};
M_.param_names_tex(19) = {'SIGMA\_tilde'};
M_.param_names_long(19) = {'SIGMA_tilde'};
M_.param_names(20) = {'GAMMA_tilde'};
M_.param_names_tex(20) = {'GAMMA\_tilde'};
M_.param_names_long(20) = {'GAMMA_tilde'};
M_.param_names(21) = {'RHOA'};
M_.param_names_tex(21) = {'RHOA'};
M_.param_names_long(21) = {'RHOA'};
M_.param_names(22) = {'RHOXI'};
M_.param_names_tex(22) = {'RHOXI'};
M_.param_names_long(22) = {'RHOXI'};
M_.param_names(23) = {'optimal_policy_discount_factor'};
M_.param_names_tex(23) = {'optimal\_policy\_discount\_factor'};
M_.param_names_long(23) = {'optimal_policy_discount_factor'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 83;
M_.param_nbr = 23;
M_.orig_endo_nbr = 43;
M_.aux_vars(1).endo_index = 44;
M_.aux_vars(1).type = 6;
M_.aux_vars(1).eq_nbr = 1;
M_.aux_vars(2).endo_index = 45;
M_.aux_vars(2).type = 6;
M_.aux_vars(2).eq_nbr = 2;
M_.aux_vars(3).endo_index = 46;
M_.aux_vars(3).type = 6;
M_.aux_vars(3).eq_nbr = 3;
M_.aux_vars(4).endo_index = 47;
M_.aux_vars(4).type = 6;
M_.aux_vars(4).eq_nbr = 4;
M_.aux_vars(5).endo_index = 48;
M_.aux_vars(5).type = 6;
M_.aux_vars(5).eq_nbr = 5;
M_.aux_vars(6).endo_index = 49;
M_.aux_vars(6).type = 6;
M_.aux_vars(6).eq_nbr = 6;
M_.aux_vars(7).endo_index = 50;
M_.aux_vars(7).type = 6;
M_.aux_vars(7).eq_nbr = 7;
M_.aux_vars(8).endo_index = 51;
M_.aux_vars(8).type = 6;
M_.aux_vars(8).eq_nbr = 8;
M_.aux_vars(9).endo_index = 52;
M_.aux_vars(9).type = 6;
M_.aux_vars(9).eq_nbr = 9;
M_.aux_vars(10).endo_index = 53;
M_.aux_vars(10).type = 6;
M_.aux_vars(10).eq_nbr = 10;
M_.aux_vars(11).endo_index = 54;
M_.aux_vars(11).type = 6;
M_.aux_vars(11).eq_nbr = 11;
M_.aux_vars(12).endo_index = 55;
M_.aux_vars(12).type = 6;
M_.aux_vars(12).eq_nbr = 12;
M_.aux_vars(13).endo_index = 56;
M_.aux_vars(13).type = 6;
M_.aux_vars(13).eq_nbr = 13;
M_.aux_vars(14).endo_index = 57;
M_.aux_vars(14).type = 6;
M_.aux_vars(14).eq_nbr = 14;
M_.aux_vars(15).endo_index = 58;
M_.aux_vars(15).type = 6;
M_.aux_vars(15).eq_nbr = 15;
M_.aux_vars(16).endo_index = 59;
M_.aux_vars(16).type = 6;
M_.aux_vars(16).eq_nbr = 16;
M_.aux_vars(17).endo_index = 60;
M_.aux_vars(17).type = 6;
M_.aux_vars(17).eq_nbr = 17;
M_.aux_vars(18).endo_index = 61;
M_.aux_vars(18).type = 6;
M_.aux_vars(18).eq_nbr = 18;
M_.aux_vars(19).endo_index = 62;
M_.aux_vars(19).type = 6;
M_.aux_vars(19).eq_nbr = 19;
M_.aux_vars(20).endo_index = 63;
M_.aux_vars(20).type = 6;
M_.aux_vars(20).eq_nbr = 20;
M_.aux_vars(21).endo_index = 64;
M_.aux_vars(21).type = 6;
M_.aux_vars(21).eq_nbr = 21;
M_.aux_vars(22).endo_index = 65;
M_.aux_vars(22).type = 6;
M_.aux_vars(22).eq_nbr = 22;
M_.aux_vars(23).endo_index = 66;
M_.aux_vars(23).type = 6;
M_.aux_vars(23).eq_nbr = 23;
M_.aux_vars(24).endo_index = 67;
M_.aux_vars(24).type = 6;
M_.aux_vars(24).eq_nbr = 24;
M_.aux_vars(25).endo_index = 68;
M_.aux_vars(25).type = 6;
M_.aux_vars(25).eq_nbr = 25;
M_.aux_vars(26).endo_index = 69;
M_.aux_vars(26).type = 6;
M_.aux_vars(26).eq_nbr = 26;
M_.aux_vars(27).endo_index = 70;
M_.aux_vars(27).type = 6;
M_.aux_vars(27).eq_nbr = 27;
M_.aux_vars(28).endo_index = 71;
M_.aux_vars(28).type = 6;
M_.aux_vars(28).eq_nbr = 28;
M_.aux_vars(29).endo_index = 72;
M_.aux_vars(29).type = 6;
M_.aux_vars(29).eq_nbr = 29;
M_.aux_vars(30).endo_index = 73;
M_.aux_vars(30).type = 6;
M_.aux_vars(30).eq_nbr = 30;
M_.aux_vars(31).endo_index = 74;
M_.aux_vars(31).type = 6;
M_.aux_vars(31).eq_nbr = 31;
M_.aux_vars(32).endo_index = 75;
M_.aux_vars(32).type = 6;
M_.aux_vars(32).eq_nbr = 32;
M_.aux_vars(33).endo_index = 76;
M_.aux_vars(33).type = 6;
M_.aux_vars(33).eq_nbr = 33;
M_.aux_vars(34).endo_index = 77;
M_.aux_vars(34).type = 6;
M_.aux_vars(34).eq_nbr = 34;
M_.aux_vars(35).endo_index = 78;
M_.aux_vars(35).type = 6;
M_.aux_vars(35).eq_nbr = 35;
M_.aux_vars(36).endo_index = 79;
M_.aux_vars(36).type = 6;
M_.aux_vars(36).eq_nbr = 36;
M_.aux_vars(37).endo_index = 80;
M_.aux_vars(37).type = 6;
M_.aux_vars(37).eq_nbr = 37;
M_.aux_vars(38).endo_index = 81;
M_.aux_vars(38).type = 6;
M_.aux_vars(38).eq_nbr = 38;
M_.aux_vars(39).endo_index = 82;
M_.aux_vars(39).type = 6;
M_.aux_vars(39).eq_nbr = 39;
M_.aux_vars(40).endo_index = 83;
M_.aux_vars(40).type = 6;
M_.aux_vars(40).eq_nbr = 40;
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 40;
M_.eq_nbr = 83;
M_.ramsey_eq_nbr = 43;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 9 0;
 0 10 0;
 0 11 0;
 0 12 0;
 0 13 0;
 0 14 0;
 0 15 0;
 0 16 0;
 0 17 0;
 1 18 0;
 2 19 0;
 3 20 0;
 4 21 0;
 0 22 0;
 0 23 0;
 0 24 0;
 0 25 0;
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 92;
 0 34 93;
 0 35 94;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 95;
 0 41 96;
 0 42 97;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 98;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 5 63 0;
 6 64 0;
 7 65 0;
 8 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 0 86 0;
 0 87 0;
 0 88 99;
 0 89 100;
 0 90 101;
 0 91 102;]';
M_.nstatic = 64;
M_.nfwrd   = 11;
M_.npred   = 8;
M_.nboth   = 0;
M_.nsfwrd   = 11;
M_.nspred   = 8;
M_.ndynamic   = 19;
M_.dynamic_tmp_nbr = [5; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  44 , 'name' , 'c_H_nat' ;
  45 , 'name' , 'c_F_nat' ;
  46 , 'name' , 'c_F_nat_starr' ;
  47 , 'name' , 'c_H_nat_starr' ;
  48 , 'name' , '5' ;
  49 , 'name' , '6' ;
  50 , 'name' , '7' ;
  51 , 'name' , '8' ;
  52 , 'name' , 's_nat' ;
  53 , 'name' , '10' ;
  54 , 'name' , '11' ;
  55 , 'name' , 'Home Dynamic IS Curve' ;
  56 , 'name' , 'Home New Keynesian Phillips Curve' ;
  57 , 'name' , 'Foreign Dynamic IS Curve' ;
  58 , 'name' , 'Foreign New Keynesian Phillips Curve' ;
  59 , 'name' , 'IRS' ;
  60 , 'name' , 'Home production function' ;
  61 , 'name' , 'Home good market clearing condition' ;
  62 , 'name' , 'c_H' ;
  63 , 'name' , 'c_F' ;
  64 , 'name' , 'n_starr' ;
  65 , 'name' , '22' ;
  66 , 'name' , 'c_H_starr' ;
  67 , 'name' , 'c_F_starr' ;
  68 , 'name' , 'pie_cu' ;
  69 , 'name' , 'y_cu' ;
  70 , 'name' , 'g_cu' ;
  71 , 'name' , 'y_gap' ;
  72 , 'name' , 'g_gap' ;
  73 , 'name' , 'c_gap' ;
  74 , 'name' , 'y_gap_starr' ;
  75 , 'name' , 'g_gap_starr' ;
  76 , 'name' , 'c_gap_starr' ;
  77 , 'name' , 's_gap' ;
  78 , 'name' , 'y_gap_cu' ;
  79 , 'name' , 'g_gap_cu' ;
  80 , 'name' , 'a' ;
  81 , 'name' , 'xi' ;
  82 , 'name' , 'a_starr' ;
  83 , 'name' , 'xi_starr' ;
};
M_.mapping.y_gap.eqidx = [1 71 78 ];
M_.mapping.g_gap.eqidx = [2 72 79 ];
M_.mapping.c_gap.eqidx = [3 73 ];
M_.mapping.y_gap_starr.eqidx = [4 74 78 ];
M_.mapping.g_gap_starr.eqidx = [5 75 79 ];
M_.mapping.c_gap_starr.eqidx = [6 76 ];
M_.mapping.s_gap.eqidx = [77 ];
M_.mapping.y_gap_cu.eqidx = [78 ];
M_.mapping.g_gap_cu.eqidx = [79 ];
M_.mapping.a.eqidx = [48 56 60 80 ];
M_.mapping.xi.eqidx = [81 ];
M_.mapping.a_starr.eqidx = [49 58 64 82 ];
M_.mapping.xi_starr.eqidx = [83 ];
M_.mapping.eps_a.eqidx = [80 ];
M_.mapping.eps_xi.eqidx = [81 ];
M_.mapping.eps_a_starr.eqidx = [82 ];
M_.mapping.eps_xi_starr.eqidx = [83 ];
M_.mapping.y_nat.eqidx = [48 50 53 71 ];
M_.mapping.g_nat.eqidx = [44 47 48 50 52 53 72 ];
M_.mapping.c_nat.eqidx = [44 45 53 73 ];
M_.mapping.c_H_nat.eqidx = [44 ];
M_.mapping.c_F_nat.eqidx = [45 ];
M_.mapping.y_nat_starr.eqidx = [49 51 54 74 ];
M_.mapping.g_nat_starr.eqidx = [45 46 49 51 52 54 75 ];
M_.mapping.c_nat_starr.eqidx = [46 47 54 76 ];
M_.mapping.c_H_nat_starr.eqidx = [47 ];
M_.mapping.c_F_nat_starr.eqidx = [46 ];
M_.mapping.s_nat.eqidx = [50 51 52 53 54 77 ];
M_.mapping.y.eqidx = [55 56 59 60 61 69 71 ];
M_.mapping.pie.eqidx = [26 55 56 68 ];
M_.mapping.g.eqidx = [55 56 59 61 70 72 ];
M_.mapping.n.eqidx = [60 ];
M_.mapping.c.eqidx = [61 62 63 73 ];
M_.mapping.c_H.eqidx = [62 ];
M_.mapping.c_F.eqidx = [63 ];
M_.mapping.y_starr.eqidx = [57 58 59 64 65 69 74 ];
M_.mapping.pie_starr.eqidx = [33 57 58 68 ];
M_.mapping.g_starr.eqidx = [57 58 59 65 70 75 ];
M_.mapping.n_starr.eqidx = [64 ];
M_.mapping.c_starr.eqidx = [65 66 67 76 ];
M_.mapping.c_H_starr.eqidx = [66 ];
M_.mapping.c_F_starr.eqidx = [67 ];
M_.mapping.ii.eqidx = [55 57 ];
M_.mapping.s.eqidx = [55 56 57 58 59 61 62 63 65 66 67 77 ];
M_.mapping.pie_cu.eqidx = [68 ];
M_.mapping.y_cu.eqidx = [69 ];
M_.mapping.g_cu.eqidx = [70 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [10 11 12 13 55 56 57 58 ];
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(83, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(23, 1);
M_.endo_trends = struct('deflator', cell(83, 1), 'log_deflator', cell(83, 1), 'growth_factor', cell(83, 1), 'log_growth_factor', cell(83, 1));
M_.NNZDerivatives = [288; 0; -1; ];
M_.static_tmp_nbr = [4; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0;
M_.Sigma_e(2, 2) = 0;
M_.Sigma_e(3, 3) = 1;
M_.Sigma_e(4, 4) = 0;
M_.params(1) = 0.98;
BETA = M_.params(1);
M_.params(2) = 3;
SIGMA = M_.params(2);
M_.params(3) = 1;
PHI = M_.params(3);
M_.params(4) = 2;
GAMMA = M_.params(4);
M_.params(5) = 4.5;
ETA = M_.params(5);
M_.params(6) = 6;
EPSILON = M_.params(6);
M_.params(7) = 0.5;
h = M_.params(7);
M_.params(8) = 0.2;
ALPHA_bar = M_.params(8);
M_.params(9) = 0.75;
THETA = M_.params(9);
M_.params(10) = 0.75;
THETA_starr = M_.params(10);
M_.params(11) = 0.3;
DELTA = M_.params(11);
M_.params(12) = (1-M_.params(11))^M_.params(2);
CHI_C = M_.params(12);
M_.params(13) = M_.params(11)^M_.params(4);
CHI_G = M_.params(13);
M_.params(14) = M_.params(8)*(1-M_.params(7));
ALPHA = M_.params(14);
M_.params(15) = M_.params(8)*M_.params(7);
ALPHA_starr = M_.params(15);
M_.params(16) = (1-M_.params(9))*(1-M_.params(9)*M_.params(1))/M_.params(9);
LAMBDA = M_.params(16);
M_.params(17) = (1-M_.params(10))*(1-M_.params(1)*M_.params(10))/M_.params(10);
LAMBDA_starr = M_.params(17);
M_.params(18) = (2-M_.params(8))*(M_.params(2)*M_.params(5)-1);
W_ALPHA_bar = M_.params(18);
M_.params(19) = M_.params(2)/(1-M_.params(11));
SIGMA_tilde = M_.params(19);
M_.params(20) = M_.params(4)/M_.params(11);
GAMMA_tilde = M_.params(20);
M_.params(21) = 0.85;
RHOA = M_.params(21);
M_.params(22) = 0.85;
RHOXI = M_.params(22);
M_.NNZDerivatives_objective = [8;8;0;];
M_.objective_tmp_nbr = [0; 0; 0; 0; ];
M_.params(23) = M_.params(1);
optimal_policy_discount_factor = M_.params(23);
options_.ramsey_policy = true;
options_.instruments = {'ii';'g_gap';'g_gap_starr'};
steady;
options_.TeX = true;
options_.impulse_responses.plot_threshold = 1e-100;
options_.irf = 30;
options_.order = 1;
options_.irf_shocks = {'eps_a_starr'};
var_list_ = {'y_gap';'y_nat';'g_gap';'g_nat';'c_gap';'c_nat';'pie';'c_F';'c_H';'y_gap_starr';'y_nat_starr';'g_gap_starr';'g_nat_starr';'c_gap_starr';'c_nat_starr';'pie_starr';'c_F_starr';'c_H_starr';'y_gap_cu';'g_gap_cu';'pie_cu';'s_gap';'s_nat';'ii'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
oo_.planner_objective_value = evaluate_planner_objective(M_, options_, oo_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
