%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'MODEL_MAIN';
M_.dynare_version = '5.0';
oo_.dynare_version = '5.0';
options_.dynare_version = '5.0';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(4,1);
M_.exo_names_tex = cell(4,1);
M_.exo_names_long = cell(4,1);
M_.exo_names(1) = {'eps_a'};
M_.exo_names_tex(1) = {'{\varepsilon_a}'};
M_.exo_names_long(1) = {'technology shock'};
M_.exo_names(2) = {'eps_xi'};
M_.exo_names_tex(2) = {'{\varepsilon_xi}'};
M_.exo_names_long(2) = {'labor disutility shock'};
M_.exo_names(3) = {'eps_a_starr'};
M_.exo_names_tex(3) = {'eps\_a\_starr'};
M_.exo_names_long(3) = {'eps_a_starr'};
M_.exo_names(4) = {'eps_xi_starr'};
M_.exo_names_tex(4) = {'eps\_xi\_starr'};
M_.exo_names_long(4) = {'eps_xi_starr'};
M_.endo_names = cell(77,1);
M_.endo_names_tex = cell(77,1);
M_.endo_names_long = cell(77,1);
M_.endo_names(1) = {'y_gap'};
M_.endo_names_tex(1) = {'{\tilde y_t}'};
M_.endo_names_long(1) = {'Home output gap (log dev ss)'};
M_.endo_names(2) = {'g_gap'};
M_.endo_names_tex(2) = {'{\tilde g_t}'};
M_.endo_names_long(2) = {'Home government spending gap (log dev ss)'};
M_.endo_names(3) = {'c_gap'};
M_.endo_names_tex(3) = {'{\tilde c_t}'};
M_.endo_names_long(3) = {'Home consumption gap (log dev ss)'};
M_.endo_names(4) = {'y_gap_starr'};
M_.endo_names_tex(4) = {'{\tilde y_t^*}'};
M_.endo_names_long(4) = {'Foreign output gap (log dev ss)'};
M_.endo_names(5) = {'g_gap_starr'};
M_.endo_names_tex(5) = {'{\tilde g_t^*}'};
M_.endo_names_long(5) = {'Foreign government spending gap (log dev ss)'};
M_.endo_names(6) = {'c_gap_starr'};
M_.endo_names_tex(6) = {'{\tilde c_t^*}'};
M_.endo_names_long(6) = {'Foreign consumption gap (log dev ss)'};
M_.endo_names(7) = {'s_gap'};
M_.endo_names_tex(7) = {'{\tilde s_t}'};
M_.endo_names_long(7) = {'Home terms of trade gap (log dev ss)'};
M_.endo_names(8) = {'y_gap_cu'};
M_.endo_names_tex(8) = {'{\tilde y_{cu,t}}'};
M_.endo_names_long(8) = {'Currency union output gap (log dev ss)'};
M_.endo_names(9) = {'g_gap_cu'};
M_.endo_names_tex(9) = {'{\tilde g_{cu,t}}'};
M_.endo_names_long(9) = {'Currency government spending gap (log dev ss)'};
M_.endo_names(10) = {'a'};
M_.endo_names_tex(10) = {'{a_t}'};
M_.endo_names_long(10) = {'Home productivity (log dev ss)'};
M_.endo_names(11) = {'xi'};
M_.endo_names_tex(11) = {'{\xi_t}'};
M_.endo_names_long(11) = {'Home labor disutility (log dev ss)'};
M_.endo_names(12) = {'a_starr'};
M_.endo_names_tex(12) = {'{a_t^*}'};
M_.endo_names_long(12) = {'Foreign productivity (log dev ss)'};
M_.endo_names(13) = {'xi_starr'};
M_.endo_names_tex(13) = {'{\xi_t^*}'};
M_.endo_names_long(13) = {'Foreign labor disutility (log dev ss)'};
M_.endo_names(14) = {'y_nat'};
M_.endo_names_tex(14) = {'{\hat {\bar y}_t}'};
M_.endo_names_long(14) = {'Home natural output (log dev ss)'};
M_.endo_names(15) = {'g_nat'};
M_.endo_names_tex(15) = {'{\hat {\bar g}_t}'};
M_.endo_names_long(15) = {'Home natural government spending (log dev ss)'};
M_.endo_names(16) = {'c_nat'};
M_.endo_names_tex(16) = {'{\hat {\bar c}_t}'};
M_.endo_names_long(16) = {'Home natural consumption (log dev ss)'};
M_.endo_names(17) = {'y_nat_starr'};
M_.endo_names_tex(17) = {'{\hat {\bar y}_t^*}'};
M_.endo_names_long(17) = {'Foreign natural output (log dev ss)'};
M_.endo_names(18) = {'g_nat_starr'};
M_.endo_names_tex(18) = {'{\hat {\bar g}_t^*}'};
M_.endo_names_long(18) = {'Foreign natural government spending (log dev ss)'};
M_.endo_names(19) = {'c_nat_starr'};
M_.endo_names_tex(19) = {'{\hat {\bar c}_t^*}'};
M_.endo_names_long(19) = {'Foreign natural consumption (log dev ss)'};
M_.endo_names(20) = {'s_nat'};
M_.endo_names_tex(20) = {'{\bar s_t}'};
M_.endo_names_long(20) = {'Home natural terms of trade (log dev ss)'};
M_.endo_names(21) = {'y'};
M_.endo_names_tex(21) = {'{\hat y_t}'};
M_.endo_names_long(21) = {'Home output (log dev ss)'};
M_.endo_names(22) = {'pie'};
M_.endo_names_tex(22) = {'{\pi_t}'};
M_.endo_names_long(22) = {'Home inflation (log dev ss)'};
M_.endo_names(23) = {'g'};
M_.endo_names_tex(23) = {'{\hat g_t}'};
M_.endo_names_long(23) = {'Home government consumption (log dev ss)'};
M_.endo_names(24) = {'n'};
M_.endo_names_tex(24) = {'{\hat n_t}'};
M_.endo_names_long(24) = {'Home labor supply (log dev ss)'};
M_.endo_names(25) = {'c'};
M_.endo_names_tex(25) = {'{\hat c_t}'};
M_.endo_names_long(25) = {'Home consumption (log dev ss)'};
M_.endo_names(26) = {'c_F'};
M_.endo_names_tex(26) = {'{\hat c_{F,t}}'};
M_.endo_names_long(26) = {'Home consumption of Home-made goods (log dev ss)'};
M_.endo_names(27) = {'c_H'};
M_.endo_names_tex(27) = {'{\hat c_{H,t}}'};
M_.endo_names_long(27) = {'Home consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(28) = {'y_starr'};
M_.endo_names_tex(28) = {'{\hat y_t^*}'};
M_.endo_names_long(28) = {'Foreign output (log dev ss)'};
M_.endo_names(29) = {'pie_starr'};
M_.endo_names_tex(29) = {'{\pi_t^*}'};
M_.endo_names_long(29) = {'Foreign inflation (log dev ss)'};
M_.endo_names(30) = {'g_starr'};
M_.endo_names_tex(30) = {'{\hat g_t^*}'};
M_.endo_names_long(30) = {'Foreign government consumption (log dev ss)'};
M_.endo_names(31) = {'n_starr'};
M_.endo_names_tex(31) = {'{\hat n_t^*}'};
M_.endo_names_long(31) = {'Foreign labor supply (log dev ss)'};
M_.endo_names(32) = {'c_starr'};
M_.endo_names_tex(32) = {'{\hat c_t^*}'};
M_.endo_names_long(32) = {'Foreign consumption (log dev ss)'};
M_.endo_names(33) = {'c_F_starr'};
M_.endo_names_tex(33) = {'{\hat c_{F,t}^*}'};
M_.endo_names_long(33) = {'Foreign consumption of Home-made goods (log dev ss)'};
M_.endo_names(34) = {'c_H_starr'};
M_.endo_names_tex(34) = {'{\hat c_{H,t}^*}'};
M_.endo_names_long(34) = {'Foreign consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(35) = {'ii'};
M_.endo_names_tex(35) = {'{i_t}'};
M_.endo_names_long(35) = {'Currency union nominal interest rate (log dev ss)'};
M_.endo_names(36) = {'s'};
M_.endo_names_tex(36) = {'{s_t}'};
M_.endo_names_long(36) = {'Home terms of trade (log dev ss)'};
M_.endo_names(37) = {'pie_cu'};
M_.endo_names_tex(37) = {'{\pi_{cu,t}}'};
M_.endo_names_long(37) = {'Currency union inflation (log dev ss)'};
M_.endo_names(38) = {'y_cu'};
M_.endo_names_tex(38) = {'{\hat y_{cu,t}}'};
M_.endo_names_long(38) = {'Currency union output (log dev ss)'};
M_.endo_names(39) = {'g_cu'};
M_.endo_names_tex(39) = {'{\hat g_{cu,t}}'};
M_.endo_names_long(39) = {'Currency union government spending (log dev ss)'};
M_.endo_names(40) = {'MULT_1'};
M_.endo_names_tex(40) = {'MULT\_1'};
M_.endo_names_long(40) = {'MULT_1'};
M_.endo_names(41) = {'MULT_2'};
M_.endo_names_tex(41) = {'MULT\_2'};
M_.endo_names_long(41) = {'MULT_2'};
M_.endo_names(42) = {'MULT_3'};
M_.endo_names_tex(42) = {'MULT\_3'};
M_.endo_names_long(42) = {'MULT_3'};
M_.endo_names(43) = {'MULT_4'};
M_.endo_names_tex(43) = {'MULT\_4'};
M_.endo_names_long(43) = {'MULT_4'};
M_.endo_names(44) = {'MULT_5'};
M_.endo_names_tex(44) = {'MULT\_5'};
M_.endo_names_long(44) = {'MULT_5'};
M_.endo_names(45) = {'MULT_6'};
M_.endo_names_tex(45) = {'MULT\_6'};
M_.endo_names_long(45) = {'MULT_6'};
M_.endo_names(46) = {'MULT_7'};
M_.endo_names_tex(46) = {'MULT\_7'};
M_.endo_names_long(46) = {'MULT_7'};
M_.endo_names(47) = {'MULT_8'};
M_.endo_names_tex(47) = {'MULT\_8'};
M_.endo_names_long(47) = {'MULT_8'};
M_.endo_names(48) = {'MULT_9'};
M_.endo_names_tex(48) = {'MULT\_9'};
M_.endo_names_long(48) = {'MULT_9'};
M_.endo_names(49) = {'MULT_10'};
M_.endo_names_tex(49) = {'MULT\_10'};
M_.endo_names_long(49) = {'MULT_10'};
M_.endo_names(50) = {'MULT_11'};
M_.endo_names_tex(50) = {'MULT\_11'};
M_.endo_names_long(50) = {'MULT_11'};
M_.endo_names(51) = {'MULT_12'};
M_.endo_names_tex(51) = {'MULT\_12'};
M_.endo_names_long(51) = {'MULT_12'};
M_.endo_names(52) = {'MULT_13'};
M_.endo_names_tex(52) = {'MULT\_13'};
M_.endo_names_long(52) = {'MULT_13'};
M_.endo_names(53) = {'MULT_14'};
M_.endo_names_tex(53) = {'MULT\_14'};
M_.endo_names_long(53) = {'MULT_14'};
M_.endo_names(54) = {'MULT_15'};
M_.endo_names_tex(54) = {'MULT\_15'};
M_.endo_names_long(54) = {'MULT_15'};
M_.endo_names(55) = {'MULT_16'};
M_.endo_names_tex(55) = {'MULT\_16'};
M_.endo_names_long(55) = {'MULT_16'};
M_.endo_names(56) = {'MULT_17'};
M_.endo_names_tex(56) = {'MULT\_17'};
M_.endo_names_long(56) = {'MULT_17'};
M_.endo_names(57) = {'MULT_18'};
M_.endo_names_tex(57) = {'MULT\_18'};
M_.endo_names_long(57) = {'MULT_18'};
M_.endo_names(58) = {'MULT_19'};
M_.endo_names_tex(58) = {'MULT\_19'};
M_.endo_names_long(58) = {'MULT_19'};
M_.endo_names(59) = {'MULT_20'};
M_.endo_names_tex(59) = {'MULT\_20'};
M_.endo_names_long(59) = {'MULT_20'};
M_.endo_names(60) = {'MULT_21'};
M_.endo_names_tex(60) = {'MULT\_21'};
M_.endo_names_long(60) = {'MULT_21'};
M_.endo_names(61) = {'MULT_22'};
M_.endo_names_tex(61) = {'MULT\_22'};
M_.endo_names_long(61) = {'MULT_22'};
M_.endo_names(62) = {'MULT_23'};
M_.endo_names_tex(62) = {'MULT\_23'};
M_.endo_names_long(62) = {'MULT_23'};
M_.endo_names(63) = {'MULT_24'};
M_.endo_names_tex(63) = {'MULT\_24'};
M_.endo_names_long(63) = {'MULT_24'};
M_.endo_names(64) = {'MULT_25'};
M_.endo_names_tex(64) = {'MULT\_25'};
M_.endo_names_long(64) = {'MULT_25'};
M_.endo_names(65) = {'MULT_26'};
M_.endo_names_tex(65) = {'MULT\_26'};
M_.endo_names_long(65) = {'MULT_26'};
M_.endo_names(66) = {'MULT_27'};
M_.endo_names_tex(66) = {'MULT\_27'};
M_.endo_names_long(66) = {'MULT_27'};
M_.endo_names(67) = {'MULT_28'};
M_.endo_names_tex(67) = {'MULT\_28'};
M_.endo_names_long(67) = {'MULT_28'};
M_.endo_names(68) = {'MULT_29'};
M_.endo_names_tex(68) = {'MULT\_29'};
M_.endo_names_long(68) = {'MULT_29'};
M_.endo_names(69) = {'MULT_30'};
M_.endo_names_tex(69) = {'MULT\_30'};
M_.endo_names_long(69) = {'MULT_30'};
M_.endo_names(70) = {'MULT_31'};
M_.endo_names_tex(70) = {'MULT\_31'};
M_.endo_names_long(70) = {'MULT_31'};
M_.endo_names(71) = {'MULT_32'};
M_.endo_names_tex(71) = {'MULT\_32'};
M_.endo_names_long(71) = {'MULT_32'};
M_.endo_names(72) = {'MULT_33'};
M_.endo_names_tex(72) = {'MULT\_33'};
M_.endo_names_long(72) = {'MULT_33'};
M_.endo_names(73) = {'MULT_34'};
M_.endo_names_tex(73) = {'MULT\_34'};
M_.endo_names_long(73) = {'MULT_34'};
M_.endo_names(74) = {'MULT_35'};
M_.endo_names_tex(74) = {'MULT\_35'};
M_.endo_names_long(74) = {'MULT_35'};
M_.endo_names(75) = {'MULT_36'};
M_.endo_names_tex(75) = {'MULT\_36'};
M_.endo_names_long(75) = {'MULT_36'};
M_.endo_names(76) = {'MULT_37'};
M_.endo_names_tex(76) = {'MULT\_37'};
M_.endo_names_long(76) = {'MULT_37'};
M_.endo_names(77) = {'MULT_38'};
M_.endo_names_tex(77) = {'MULT\_38'};
M_.endo_names_long(77) = {'MULT_38'};
M_.endo_partitions = struct();
M_.param_names = cell(48,1);
M_.param_names_tex = cell(48,1);
M_.param_names_long = cell(48,1);
M_.param_names(1) = {'SIGMA'};
M_.param_names_tex(1) = {'SIGMA'};
M_.param_names_long(1) = {'SIGMA'};
M_.param_names(2) = {'ALPHA_bar'};
M_.param_names_tex(2) = {'ALPHA\_bar'};
M_.param_names_long(2) = {'ALPHA_bar'};
M_.param_names(3) = {'DELTA'};
M_.param_names_tex(3) = {'DELTA'};
M_.param_names_long(3) = {'DELTA'};
M_.param_names(4) = {'BETA'};
M_.param_names_tex(4) = {'BETA'};
M_.param_names_long(4) = {'BETA'};
M_.param_names(5) = {'PHI'};
M_.param_names_tex(5) = {'PHI'};
M_.param_names_long(5) = {'PHI'};
M_.param_names(6) = {'h'};
M_.param_names_tex(6) = {'h'};
M_.param_names_long(6) = {'h'};
M_.param_names(7) = {'CHI'};
M_.param_names_tex(7) = {'CHI'};
M_.param_names_long(7) = {'CHI'};
M_.param_names(8) = {'GAMMA'};
M_.param_names_tex(8) = {'GAMMA'};
M_.param_names_long(8) = {'GAMMA'};
M_.param_names(9) = {'THETA'};
M_.param_names_tex(9) = {'THETA'};
M_.param_names_long(9) = {'THETA'};
M_.param_names(10) = {'THETA_starr'};
M_.param_names_tex(10) = {'THETA\_starr'};
M_.param_names_long(10) = {'THETA_starr'};
M_.param_names(11) = {'W_ALPHA_bar'};
M_.param_names_tex(11) = {'W\_ALPHA\_bar'};
M_.param_names_long(11) = {'W_ALPHA_bar'};
M_.param_names(12) = {'LAMBDA'};
M_.param_names_tex(12) = {'LAMBDA'};
M_.param_names_long(12) = {'LAMBDA'};
M_.param_names(13) = {'W_ALPHA_bar_starr'};
M_.param_names_tex(13) = {'W\_ALPHA\_bar\_starr'};
M_.param_names_long(13) = {'W_ALPHA_bar_starr'};
M_.param_names(14) = {'LAMBDA_starr'};
M_.param_names_tex(14) = {'LAMBDA\_starr'};
M_.param_names_long(14) = {'LAMBDA_starr'};
M_.param_names(15) = {'ETA'};
M_.param_names_tex(15) = {'ETA'};
M_.param_names_long(15) = {'ETA'};
M_.param_names(16) = {'RHOA'};
M_.param_names_tex(16) = {'RHOA'};
M_.param_names_long(16) = {'RHOA'};
M_.param_names(17) = {'RHOXI'};
M_.param_names_tex(17) = {'RHOXI'};
M_.param_names_long(17) = {'RHOXI'};
M_.param_names(18) = {'ALPHA'};
M_.param_names_tex(18) = {'ALPHA'};
M_.param_names_long(18) = {'ALPHA'};
M_.param_names(19) = {'ALPHA_starr'};
M_.param_names_tex(19) = {'ALPHA\_starr'};
M_.param_names_long(19) = {'ALPHA_starr'};
M_.param_names(20) = {'EPSILON'};
M_.param_names_tex(20) = {'EPSILON'};
M_.param_names_long(20) = {'EPSILON'};
M_.param_names(21) = {'SIGMA_tilde'};
M_.param_names_tex(21) = {'SIGMA\_tilde'};
M_.param_names_long(21) = {'SIGMA_tilde'};
M_.param_names(22) = {'COEF_y_gapH'};
M_.param_names_tex(22) = {'COEF\_y\_gapH'};
M_.param_names_long(22) = {'COEF_y_gapH'};
M_.param_names(23) = {'COEF_y_gapF'};
M_.param_names_tex(23) = {'COEF\_y\_gapF'};
M_.param_names_long(23) = {'COEF_y_gapF'};
M_.param_names(24) = {'COEF_pieH'};
M_.param_names_tex(24) = {'COEF\_pieH'};
M_.param_names_long(24) = {'COEF_pieH'};
M_.param_names(25) = {'COEF_pieF'};
M_.param_names_tex(25) = {'COEF\_pieF'};
M_.param_names_long(25) = {'COEF_pieF'};
M_.param_names(26) = {'COEF_y_gapH_starr'};
M_.param_names_tex(26) = {'COEF\_y\_gapH\_starr'};
M_.param_names_long(26) = {'COEF_y_gapH_starr'};
M_.param_names(27) = {'COEF_y_gapF_starr'};
M_.param_names_tex(27) = {'COEF\_y\_gapF\_starr'};
M_.param_names_long(27) = {'COEF_y_gapF_starr'};
M_.param_names(28) = {'COEF_pieH_starr'};
M_.param_names_tex(28) = {'COEF\_pieH\_starr'};
M_.param_names_long(28) = {'COEF_pieH_starr'};
M_.param_names(29) = {'COEF_pieF_starr'};
M_.param_names_tex(29) = {'COEF\_pieF\_starr'};
M_.param_names_long(29) = {'COEF_pieF_starr'};
M_.param_names(30) = {'COEF_y_natH'};
M_.param_names_tex(30) = {'COEF\_y\_natH'};
M_.param_names_long(30) = {'COEF_y_natH'};
M_.param_names(31) = {'COEF_y_natF'};
M_.param_names_tex(31) = {'COEF\_y\_natF'};
M_.param_names_long(31) = {'COEF_y_natF'};
M_.param_names(32) = {'COEF_c_natH'};
M_.param_names_tex(32) = {'COEF\_c\_natH'};
M_.param_names_long(32) = {'COEF_c_natH'};
M_.param_names(33) = {'COEF_c_natF'};
M_.param_names_tex(33) = {'COEF\_c\_natF'};
M_.param_names_long(33) = {'COEF_c_natF'};
M_.param_names(34) = {'COEF_aH'};
M_.param_names_tex(34) = {'COEF\_aH'};
M_.param_names_long(34) = {'COEF_aH'};
M_.param_names(35) = {'COEF_aF'};
M_.param_names_tex(35) = {'COEF\_aF'};
M_.param_names_long(35) = {'COEF_aF'};
M_.param_names(36) = {'COEF_xiH'};
M_.param_names_tex(36) = {'COEF\_xiH'};
M_.param_names_long(36) = {'COEF_xiH'};
M_.param_names(37) = {'COEF_xiF'};
M_.param_names_tex(37) = {'COEF\_xiF'};
M_.param_names_long(37) = {'COEF_xiF'};
M_.param_names(38) = {'COEF_s_nat'};
M_.param_names_tex(38) = {'COEF\_s\_nat'};
M_.param_names_long(38) = {'COEF_s_nat'};
M_.param_names(39) = {'COEF_y_natH_starr'};
M_.param_names_tex(39) = {'COEF\_y\_natH\_starr'};
M_.param_names_long(39) = {'COEF_y_natH_starr'};
M_.param_names(40) = {'COEF_y_natF_starr'};
M_.param_names_tex(40) = {'COEF\_y\_natF\_starr'};
M_.param_names_long(40) = {'COEF_y_natF_starr'};
M_.param_names(41) = {'COEF_c_natH_starr'};
M_.param_names_tex(41) = {'COEF\_c\_natH\_starr'};
M_.param_names_long(41) = {'COEF_c_natH_starr'};
M_.param_names(42) = {'COEF_c_natF_starr'};
M_.param_names_tex(42) = {'COEF\_c\_natF\_starr'};
M_.param_names_long(42) = {'COEF_c_natF_starr'};
M_.param_names(43) = {'COEF_aH_starr'};
M_.param_names_tex(43) = {'COEF\_aH\_starr'};
M_.param_names_long(43) = {'COEF_aH_starr'};
M_.param_names(44) = {'COEF_aF_starr'};
M_.param_names_tex(44) = {'COEF\_aF\_starr'};
M_.param_names_long(44) = {'COEF_aF_starr'};
M_.param_names(45) = {'COEF_xiH_starr'};
M_.param_names_tex(45) = {'COEF\_xiH\_starr'};
M_.param_names_long(45) = {'COEF_xiH_starr'};
M_.param_names(46) = {'COEF_xiF_starr'};
M_.param_names_tex(46) = {'COEF\_xiF\_starr'};
M_.param_names_long(46) = {'COEF_xiF_starr'};
M_.param_names(47) = {'COEF_s_nat_starr'};
M_.param_names_tex(47) = {'COEF\_s\_nat\_starr'};
M_.param_names_long(47) = {'COEF_s_nat_starr'};
M_.param_names(48) = {'optimal_policy_discount_factor'};
M_.param_names_tex(48) = {'optimal\_policy\_discount\_factor'};
M_.param_names_long(48) = {'optimal_policy_discount_factor'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 77;
M_.param_nbr = 48;
M_.orig_endo_nbr = 39;
M_.aux_vars(1).endo_index = 40;
M_.aux_vars(1).type = 6;
M_.aux_vars(1).eq_nbr = 1;
M_.aux_vars(2).endo_index = 41;
M_.aux_vars(2).type = 6;
M_.aux_vars(2).eq_nbr = 2;
M_.aux_vars(3).endo_index = 42;
M_.aux_vars(3).type = 6;
M_.aux_vars(3).eq_nbr = 3;
M_.aux_vars(4).endo_index = 43;
M_.aux_vars(4).type = 6;
M_.aux_vars(4).eq_nbr = 4;
M_.aux_vars(5).endo_index = 44;
M_.aux_vars(5).type = 6;
M_.aux_vars(5).eq_nbr = 5;
M_.aux_vars(6).endo_index = 45;
M_.aux_vars(6).type = 6;
M_.aux_vars(6).eq_nbr = 6;
M_.aux_vars(7).endo_index = 46;
M_.aux_vars(7).type = 6;
M_.aux_vars(7).eq_nbr = 7;
M_.aux_vars(8).endo_index = 47;
M_.aux_vars(8).type = 6;
M_.aux_vars(8).eq_nbr = 8;
M_.aux_vars(9).endo_index = 48;
M_.aux_vars(9).type = 6;
M_.aux_vars(9).eq_nbr = 9;
M_.aux_vars(10).endo_index = 49;
M_.aux_vars(10).type = 6;
M_.aux_vars(10).eq_nbr = 10;
M_.aux_vars(11).endo_index = 50;
M_.aux_vars(11).type = 6;
M_.aux_vars(11).eq_nbr = 11;
M_.aux_vars(12).endo_index = 51;
M_.aux_vars(12).type = 6;
M_.aux_vars(12).eq_nbr = 12;
M_.aux_vars(13).endo_index = 52;
M_.aux_vars(13).type = 6;
M_.aux_vars(13).eq_nbr = 13;
M_.aux_vars(14).endo_index = 53;
M_.aux_vars(14).type = 6;
M_.aux_vars(14).eq_nbr = 14;
M_.aux_vars(15).endo_index = 54;
M_.aux_vars(15).type = 6;
M_.aux_vars(15).eq_nbr = 15;
M_.aux_vars(16).endo_index = 55;
M_.aux_vars(16).type = 6;
M_.aux_vars(16).eq_nbr = 16;
M_.aux_vars(17).endo_index = 56;
M_.aux_vars(17).type = 6;
M_.aux_vars(17).eq_nbr = 17;
M_.aux_vars(18).endo_index = 57;
M_.aux_vars(18).type = 6;
M_.aux_vars(18).eq_nbr = 18;
M_.aux_vars(19).endo_index = 58;
M_.aux_vars(19).type = 6;
M_.aux_vars(19).eq_nbr = 19;
M_.aux_vars(20).endo_index = 59;
M_.aux_vars(20).type = 6;
M_.aux_vars(20).eq_nbr = 20;
M_.aux_vars(21).endo_index = 60;
M_.aux_vars(21).type = 6;
M_.aux_vars(21).eq_nbr = 21;
M_.aux_vars(22).endo_index = 61;
M_.aux_vars(22).type = 6;
M_.aux_vars(22).eq_nbr = 22;
M_.aux_vars(23).endo_index = 62;
M_.aux_vars(23).type = 6;
M_.aux_vars(23).eq_nbr = 23;
M_.aux_vars(24).endo_index = 63;
M_.aux_vars(24).type = 6;
M_.aux_vars(24).eq_nbr = 24;
M_.aux_vars(25).endo_index = 64;
M_.aux_vars(25).type = 6;
M_.aux_vars(25).eq_nbr = 25;
M_.aux_vars(26).endo_index = 65;
M_.aux_vars(26).type = 6;
M_.aux_vars(26).eq_nbr = 26;
M_.aux_vars(27).endo_index = 66;
M_.aux_vars(27).type = 6;
M_.aux_vars(27).eq_nbr = 27;
M_.aux_vars(28).endo_index = 67;
M_.aux_vars(28).type = 6;
M_.aux_vars(28).eq_nbr = 28;
M_.aux_vars(29).endo_index = 68;
M_.aux_vars(29).type = 6;
M_.aux_vars(29).eq_nbr = 29;
M_.aux_vars(30).endo_index = 69;
M_.aux_vars(30).type = 6;
M_.aux_vars(30).eq_nbr = 30;
M_.aux_vars(31).endo_index = 70;
M_.aux_vars(31).type = 6;
M_.aux_vars(31).eq_nbr = 31;
M_.aux_vars(32).endo_index = 71;
M_.aux_vars(32).type = 6;
M_.aux_vars(32).eq_nbr = 32;
M_.aux_vars(33).endo_index = 72;
M_.aux_vars(33).type = 6;
M_.aux_vars(33).eq_nbr = 33;
M_.aux_vars(34).endo_index = 73;
M_.aux_vars(34).type = 6;
M_.aux_vars(34).eq_nbr = 34;
M_.aux_vars(35).endo_index = 74;
M_.aux_vars(35).type = 6;
M_.aux_vars(35).eq_nbr = 35;
M_.aux_vars(36).endo_index = 75;
M_.aux_vars(36).type = 6;
M_.aux_vars(36).eq_nbr = 36;
M_.aux_vars(37).endo_index = 76;
M_.aux_vars(37).type = 6;
M_.aux_vars(37).eq_nbr = 37;
M_.aux_vars(38).endo_index = 77;
M_.aux_vars(38).type = 6;
M_.aux_vars(38).eq_nbr = 38;
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 38;
M_.eq_nbr = 77;
M_.ramsey_eq_nbr = 39;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 1 13 0;
 0 14 0;
 0 15 0;
 2 16 0;
 0 17 0;
 0 18 0;
 0 19 0;
 0 20 0;
 0 21 0;
 3 22 0;
 4 23 0;
 5 24 0;
 6 25 0;
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 90;
 7 34 91;
 0 35 92;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 93;
 8 41 94;
 0 42 95;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 96;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 0 57 0;
 0 58 0;
 9 59 0;
 10 60 0;
 11 61 0;
 12 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 97;
 0 76 98;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 0 86 99;
 0 87 100;
 0 88 101;
 0 89 102;]';
M_.nstatic = 54;
M_.nfwrd   = 11;
M_.npred   = 10;
M_.nboth   = 2;
M_.nsfwrd   = 13;
M_.nspred   = 12;
M_.ndynamic   = 23;
M_.dynamic_tmp_nbr = [13; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  40 , 'name' , '1' ;
  41 , 'name' , '2' ;
  42 , 'name' , '3' ;
  43 , 'name' , '4' ;
  44 , 'name' , 'c_nat' ;
  45 , 'name' , 'c_nat_starr' ;
  46 , 'name' , '7' ;
  47 , 'name' , 'Home Dynamic IS Curve' ;
  48 , 'name' , 'Home New Keynesian Phillips Curve' ;
  49 , 'name' , 'Foreign Dynamic IS Curve' ;
  50 , 'name' , 'Foreign New Keynesian Phillips Curve' ;
  51 , 'name' , 'IRS' ;
  52 , 'name' , 'n' ;
  53 , 'name' , 'c' ;
  54 , 'name' , 'c_H' ;
  55 , 'name' , 'c_F' ;
  56 , 'name' , 'n_starr' ;
  57 , 'name' , 'c_starr' ;
  58 , 'name' , 'c_H_starr' ;
  59 , 'name' , 'c_F_starr' ;
  60 , 'name' , 'pie_cu' ;
  61 , 'name' , 'y_cu' ;
  62 , 'name' , 'g_cu' ;
  63 , 'name' , 'g' ;
  64 , 'name' , 'g_starr' ;
  65 , 'name' , 'y_gap' ;
  66 , 'name' , 'g_gap' ;
  67 , 'name' , 'c_gap' ;
  68 , 'name' , 'y_gap_starr' ;
  69 , 'name' , 'g_gap_starr' ;
  70 , 'name' , 'c_gap_starr' ;
  71 , 'name' , 's_gap' ;
  72 , 'name' , 'y_gap_cu' ;
  73 , 'name' , 'g_gap_cu' ;
  74 , 'name' , 'a' ;
  75 , 'name' , 'xi' ;
  76 , 'name' , 'a_starr' ;
  77 , 'name' , 'xi_starr' ;
};
M_.mapping.y_gap.eqidx = [1 63 64 65 72 ];
M_.mapping.g_gap.eqidx = [66 73 ];
M_.mapping.c_gap.eqidx = [3 67 ];
M_.mapping.y_gap_starr.eqidx = [4 63 64 68 72 ];
M_.mapping.g_gap_starr.eqidx = [69 73 ];
M_.mapping.c_gap_starr.eqidx = [6 70 ];
M_.mapping.s_gap.eqidx = [71 ];
M_.mapping.y_gap_cu.eqidx = [72 ];
M_.mapping.g_gap_cu.eqidx = [73 ];
M_.mapping.a.eqidx = [42 48 52 74 ];
M_.mapping.xi.eqidx = [42 48 75 ];
M_.mapping.a_starr.eqidx = [43 50 56 76 ];
M_.mapping.xi_starr.eqidx = [43 50 77 ];
M_.mapping.eps_a.eqidx = [74 ];
M_.mapping.eps_xi.eqidx = [75 ];
M_.mapping.eps_a_starr.eqidx = [76 ];
M_.mapping.eps_xi_starr.eqidx = [77 ];
M_.mapping.y_nat.eqidx = [42 44 65 ];
M_.mapping.g_nat.eqidx = [40 41 42 44 66 ];
M_.mapping.c_nat.eqidx = [40 44 46 67 ];
M_.mapping.y_nat_starr.eqidx = [43 45 68 ];
M_.mapping.g_nat_starr.eqidx = [40 41 43 45 69 ];
M_.mapping.c_nat_starr.eqidx = [41 45 46 70 ];
M_.mapping.s_nat.eqidx = [44 45 46 71 ];
M_.mapping.y.eqidx = [47 48 51 52 53 61 65 ];
M_.mapping.pie.eqidx = [22 47 48 60 63 64 ];
M_.mapping.g.eqidx = [47 48 51 53 62 63 66 ];
M_.mapping.n.eqidx = [52 ];
M_.mapping.c.eqidx = [53 54 55 67 ];
M_.mapping.c_F.eqidx = [55 ];
M_.mapping.c_H.eqidx = [54 ];
M_.mapping.y_starr.eqidx = [49 50 51 56 57 61 68 ];
M_.mapping.pie_starr.eqidx = [29 49 50 60 63 64 ];
M_.mapping.g_starr.eqidx = [49 50 51 57 62 64 69 ];
M_.mapping.n_starr.eqidx = [56 ];
M_.mapping.c_starr.eqidx = [57 58 59 70 ];
M_.mapping.c_F_starr.eqidx = [59 ];
M_.mapping.c_H_starr.eqidx = [58 ];
M_.mapping.ii.eqidx = [47 49 ];
M_.mapping.s.eqidx = [47 48 49 50 51 53 54 55 57 58 59 71 ];
M_.mapping.pie_cu.eqidx = [60 ];
M_.mapping.y_cu.eqidx = [61 ];
M_.mapping.g_cu.eqidx = [62 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [1 4 10 11 12 13 22 29 47 48 49 50 ];
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(77, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(48, 1);
M_.endo_trends = struct('deflator', cell(77, 1), 'log_deflator', cell(77, 1), 'growth_factor', cell(77, 1), 'log_growth_factor', cell(77, 1));
M_.NNZDerivatives = [290; 0; -1; ];
M_.static_tmp_nbr = [12; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0;
M_.Sigma_e(2, 2) = 0;
M_.Sigma_e(3, 3) = 1;
M_.Sigma_e(4, 4) = 0;
M_.params(1) = 1;
SIGMA = M_.params(1);
M_.params(2) = 0.5;
ALPHA_bar = M_.params(2);
M_.params(7) = 0.03;
CHI = M_.params(7);
M_.params(3) = M_.params(7);
DELTA = M_.params(3);
M_.params(4) = 0.99;
BETA = M_.params(4);
M_.params(5) = 1;
PHI = M_.params(5);
M_.params(6) = 0.5;
h = M_.params(6);
M_.params(9) = 0.75;
THETA = M_.params(9);
M_.params(10) = 0.75;
THETA_starr = M_.params(10);
M_.params(15) = 4.5;
ETA = M_.params(15);
M_.params(8) = 1;
GAMMA = M_.params(8);
M_.params(20) = 1;
EPSILON = M_.params(20);
M_.params(18) = M_.params(2)*(1-M_.params(6));
ALPHA = M_.params(18);
M_.params(19) = M_.params(2)*M_.params(6);
ALPHA_starr = M_.params(19);
M_.params(11) = 1-M_.params(2)*M_.params(6)+M_.params(2)*(1-M_.params(6))*(2-M_.params(2))*(M_.params(1)*M_.params(15)-1);
W_ALPHA_bar = M_.params(11);
M_.params(12) = (1-M_.params(9))*(1-M_.params(9)*M_.params(4))/M_.params(9);
LAMBDA = M_.params(12);
M_.params(13) = M_.params(2)*M_.params(6)*(1+(2-M_.params(2))*(M_.params(1)*M_.params(15)-1));
W_ALPHA_bar_starr = M_.params(13);
M_.params(14) = (1-M_.params(10))*(1-M_.params(4)*M_.params(10))/M_.params(10);
LAMBDA_starr = M_.params(14);
M_.params(21) = M_.params(1)/(1-M_.params(3));
SIGMA_tilde = M_.params(21);
M_.params(16) = 0.9;
RHOA = M_.params(16);
M_.params(17) = 0.9;
RHOXI = M_.params(17);
M_.params(30) = 0.2274;
COEF_y_natH = M_.params(30);
M_.params(31) = (-0.0287);
COEF_y_natF = M_.params(31);
M_.params(32) = 2.6806;
COEF_c_natH = M_.params(32);
M_.params(33) = 0.1319;
COEF_c_natF = M_.params(33);
M_.params(34) = (-3.0120);
COEF_aH = M_.params(34);
M_.params(35) = (-0.0391);
COEF_aF = M_.params(35);
M_.params(36) = 1.5061;
COEF_xiH = M_.params(36);
M_.params(37) = 0.0195;
COEF_xiF = M_.params(37);
M_.params(38) = 1.8958;
COEF_s_nat = M_.params(38);
M_.params(39) = (-3.5187);
COEF_y_natH_starr = M_.params(39);
M_.params(40) = 0.2097;
COEF_y_natF_starr = M_.params(40);
M_.params(41) = 0.7751;
COEF_c_natH_starr = M_.params(41);
M_.params(42) = (-0.4006);
COEF_c_natF_starr = M_.params(42);
M_.params(43) = 3.0047;
COEF_aH_starr = M_.params(43);
M_.params(44) = (-0.1264);
COEF_aF_starr = M_.params(44);
M_.params(45) = (-1.5024);
COEF_xiH_starr = M_.params(45);
M_.params(46) = 0.0631;
COEF_xiF_starr = M_.params(46);
M_.params(47) = 3.0627;
COEF_s_nat_starr = M_.params(47);
M_.params(22) = 1;
COEF_y_gapH = M_.params(22);
M_.params(23) = 1;
COEF_y_gapF = M_.params(23);
M_.params(24) = 1;
COEF_pieH = M_.params(24);
M_.params(25) = 1;
COEF_pieF = M_.params(25);
M_.params(26) = 1;
COEF_y_gapH_starr = M_.params(26);
M_.params(27) = 1;
COEF_y_gapF_starr = M_.params(27);
M_.params(28) = 1;
COEF_pieH_starr = M_.params(28);
M_.params(29) = 1;
COEF_pieF_starr = M_.params(29);
M_.NNZDerivatives_objective = [6;6;0;];
M_.objective_tmp_nbr = [0; 0; 0; 0; ];
M_.params(48) = M_.params(4);
optimal_policy_discount_factor = M_.params(48);
options_.ramsey_policy = true;
options_.instruments = {'ii'};
%
% OPTIM_WEIGHTS
%
M_.osr.variable_weights = sparse(M_.endo_nbr,M_.endo_nbr);
M_.osr.variable_indices = [];

M_.osr.variable_weights(22,22) = M_.params(6);
M_.osr.variable_indices = [M_.osr.variable_indices; 22];
M_.osr.variable_weights(29,29) = 1-M_.params(6);
M_.osr.variable_indices = [M_.osr.variable_indices; 29];
M_.osr.param_names = {'COEF_y_gapH';'COEF_y_gapF';'COEF_pieH';'COEF_pieF';'COEF_y_gapH_starr';'COEF_y_gapF_starr';'COEF_pieH_starr';'COEF_pieF_starr'};
M_.osr.param_names = cellstr(M_.osr.param_names);
M_.osr.param_indices = zeros(length(M_.osr.param_names), 1);
M_.osr.param_indices(1) = 22;
M_.osr.param_indices(2) = 23;
M_.osr.param_indices(3) = 24;
M_.osr.param_indices(4) = 25;
M_.osr.param_indices(5) = 26;
M_.osr.param_indices(6) = 27;
M_.osr.param_indices(7) = 28;
M_.osr.param_indices(8) = 29;
steady;
options_.TeX = true;
options_.irf = 30;
options_.osr.opt_algo = 9;
var_list_ = {'y_gap';'y_nat';'g_gap';'g_nat';'c_gap';'c_nat';'pie';'c_F';'c_H';'y_gap_starr';'y_nat_starr';'g_gap_starr';'g_nat_starr';'c_gap_starr';'c_nat_starr';'pie_starr';'c_F_starr';'c_H_starr';'y_gap_cu';'g_gap_cu';'pie_cu';'s_gap';'s_nat';'ii'};
oo_.osr = osr(var_list_,M_.osr.param_names,M_.osr.variable_indices,M_.osr.variable_weights);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
