%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'MODEL_MAIN_4';
M_.dynare_version = '5.0';
oo_.dynare_version = '5.0';
options_.dynare_version = '5.0';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(2,1);
M_.exo_names_tex = cell(2,1);
M_.exo_names_long = cell(2,1);
M_.exo_names(1) = {'eps_a'};
M_.exo_names_tex(1) = {'{\epsilon_a}'};
M_.exo_names_long(1) = {'Home technology shock'};
M_.exo_names(2) = {'eps_a_starr'};
M_.exo_names_tex(2) = {'{\epsilon_a^*}'};
M_.exo_names_long(2) = {'Foreign technology shock'};
M_.endo_names = cell(123,1);
M_.endo_names_tex = cell(123,1);
M_.endo_names_long = cell(123,1);
M_.endo_names(1) = {'y_gap'};
M_.endo_names_tex(1) = {'{\tilde y_t}'};
M_.endo_names_long(1) = {'Home output gap (log dev ss)'};
M_.endo_names(2) = {'g_gap'};
M_.endo_names_tex(2) = {'{\tilde g_t}'};
M_.endo_names_long(2) = {'Home government spending gap (log dev ss)'};
M_.endo_names(3) = {'c_gap'};
M_.endo_names_tex(3) = {'{\tilde c_t}'};
M_.endo_names_long(3) = {'Home consumption gap (log dev ss)'};
M_.endo_names(4) = {'f_gap'};
M_.endo_names_tex(4) = {'{\tilde f_t}'};
M_.endo_names_long(4) = {'Home fiscal stance gap (log dev ss)'};
M_.endo_names(5) = {'n_gap'};
M_.endo_names_tex(5) = {'{\tilde n_t}'};
M_.endo_names_long(5) = {'Home labor gap (log dev ss)'};
M_.endo_names(6) = {'ii_gap'};
M_.endo_names_tex(6) = {'ii\_gap'};
M_.endo_names_long(6) = {'ii_gap'};
M_.endo_names(7) = {'y_gap_starr'};
M_.endo_names_tex(7) = {'{\tilde y_t^*}'};
M_.endo_names_long(7) = {'Foreign output gap (log dev ss)'};
M_.endo_names(8) = {'g_gap_starr'};
M_.endo_names_tex(8) = {'{\tilde g_t^*}'};
M_.endo_names_long(8) = {'Foreign government spending gap (log dev ss)'};
M_.endo_names(9) = {'c_gap_starr'};
M_.endo_names_tex(9) = {'{\tilde c_t^*}'};
M_.endo_names_long(9) = {'Foreign consumption gap (log dev ss)'};
M_.endo_names(10) = {'f_gap_starr'};
M_.endo_names_tex(10) = {'{\tilde f_t^*}'};
M_.endo_names_long(10) = {'Foreign fiscal stance gap (log dev ss)'};
M_.endo_names(11) = {'n_gap_starr'};
M_.endo_names_tex(11) = {'{\tilde n_t^*}'};
M_.endo_names_long(11) = {'Foreign labor gap (log dev ss)'};
M_.endo_names(12) = {'ii_gap_starr'};
M_.endo_names_tex(12) = {'ii\_gap\_starr'};
M_.endo_names_long(12) = {'ii_gap_starr'};
M_.endo_names(13) = {'s_gap'};
M_.endo_names_tex(13) = {'{\tilde s_t}'};
M_.endo_names_long(13) = {'Home terms of trade gap (log dev ss)'};
M_.endo_names(14) = {'y_gap_cu'};
M_.endo_names_tex(14) = {'{\tilde y_t^{cu}}'};
M_.endo_names_long(14) = {'Union output gap (log dev ss)'};
M_.endo_names(15) = {'g_gap_cu'};
M_.endo_names_tex(15) = {'{\tilde g_t^{cu}}'};
M_.endo_names_long(15) = {'Union government spending gap (log dev ss)'};
M_.endo_names(16) = {'c_gap_cu'};
M_.endo_names_tex(16) = {'{\tilde c_t^{cu}}'};
M_.endo_names_long(16) = {'Union government spending gap (log dev ss)'};
M_.endo_names(17) = {'ii_gap_cu'};
M_.endo_names_tex(17) = {'ii\_gap\_cu'};
M_.endo_names_long(17) = {'ii_gap_cu'};
M_.endo_names(18) = {'a'};
M_.endo_names_tex(18) = {'{a_t}'};
M_.endo_names_long(18) = {'Home productivity (log dev ss)'};
M_.endo_names(19) = {'a_starr'};
M_.endo_names_tex(19) = {'{a_t^*}'};
M_.endo_names_long(19) = {'Foreign productivity (log dev ss)'};
M_.endo_names(20) = {'y_nat'};
M_.endo_names_tex(20) = {'{\hat {\bar y}_t}'};
M_.endo_names_long(20) = {'Home natural output (log dev ss)'};
M_.endo_names(21) = {'g_nat'};
M_.endo_names_tex(21) = {'{\hat {\bar g}_t}'};
M_.endo_names_long(21) = {'Home natural government spending (log dev ss)'};
M_.endo_names(22) = {'c_nat'};
M_.endo_names_tex(22) = {'{\hat {\bar c}_t}'};
M_.endo_names_long(22) = {'Home natural consumption (log dev ss)'};
M_.endo_names(23) = {'n_nat'};
M_.endo_names_tex(23) = {'{\hat {\bar n}_t}'};
M_.endo_names_long(23) = {'Home natural labor (log dev ss)'};
M_.endo_names(24) = {'c_H_nat'};
M_.endo_names_tex(24) = {'{\hat {\bar c}_{H,t}}'};
M_.endo_names_long(24) = {'Home natural consumption of Home-made goods (log dev ss)'};
M_.endo_names(25) = {'c_F_nat'};
M_.endo_names_tex(25) = {'{\hat {\bar c}_{F,t}}'};
M_.endo_names_long(25) = {'Home natural consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(26) = {'r_nat'};
M_.endo_names_tex(26) = {'r\_nat'};
M_.endo_names_long(26) = {'r_nat'};
M_.endo_names(27) = {'f_nat'};
M_.endo_names_tex(27) = {'{\hat {\bar f}_t}'};
M_.endo_names_long(27) = {'Home natural fiscal stance (log dev ss)'};
M_.endo_names(28) = {'y_nat_starr'};
M_.endo_names_tex(28) = {'{\hat {\bar y}_t^*}'};
M_.endo_names_long(28) = {'Foreign natural output (log dev ss)'};
M_.endo_names(29) = {'g_nat_starr'};
M_.endo_names_tex(29) = {'{\hat {\bar g}_t^*}'};
M_.endo_names_long(29) = {'Foreign natural government spending (log dev ss)'};
M_.endo_names(30) = {'c_nat_starr'};
M_.endo_names_tex(30) = {'{\hat {\bar c}_t^*}'};
M_.endo_names_long(30) = {'Foreign natural consumption (log dev ss)'};
M_.endo_names(31) = {'c_H_nat_starr'};
M_.endo_names_tex(31) = {'{\hat {\bar c}_{H,t}^*}'};
M_.endo_names_long(31) = {'Foreign natural consumption of Home-made goods (log dev ss)'};
M_.endo_names(32) = {'c_F_nat_starr'};
M_.endo_names_tex(32) = {'{\hat {\bar c}_{F,t}^*}'};
M_.endo_names_long(32) = {'Foreign natural consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(33) = {'n_nat_starr'};
M_.endo_names_tex(33) = {'{\hat {\bar n}_t^*}'};
M_.endo_names_long(33) = {'Foreign natural labor (log dev ss)'};
M_.endo_names(34) = {'r_nat_starr'};
M_.endo_names_tex(34) = {'r\_nat\_starr'};
M_.endo_names_long(34) = {'r_nat_starr'};
M_.endo_names(35) = {'f_nat_starr'};
M_.endo_names_tex(35) = {'{\hat {\bar f}_t^*}'};
M_.endo_names_long(35) = {'Foreign natural fiscal stance (log dev ss)'};
M_.endo_names(36) = {'s_nat'};
M_.endo_names_tex(36) = {'{\bar s_t}'};
M_.endo_names_long(36) = {'Home natural terms of trade (log dev ss)'};
M_.endo_names(37) = {'y_nat_cu'};
M_.endo_names_tex(37) = {'y\_nat\_cu'};
M_.endo_names_long(37) = {'y_nat_cu'};
M_.endo_names(38) = {'g_nat_cu'};
M_.endo_names_tex(38) = {'g\_nat\_cu'};
M_.endo_names_long(38) = {'g_nat_cu'};
M_.endo_names(39) = {'r_nat_cu'};
M_.endo_names_tex(39) = {'r\_nat\_cu'};
M_.endo_names_long(39) = {'r_nat_cu'};
M_.endo_names(40) = {'y'};
M_.endo_names_tex(40) = {'{\hat y_t}'};
M_.endo_names_long(40) = {'Home output (log dev ss)'};
M_.endo_names(41) = {'pie'};
M_.endo_names_tex(41) = {'{\pi_{H,t}}'};
M_.endo_names_long(41) = {'Home inflation (log dev ss)'};
M_.endo_names(42) = {'g'};
M_.endo_names_tex(42) = {'{\hat g_t}'};
M_.endo_names_long(42) = {'Home government consumption (log dev ss)'};
M_.endo_names(43) = {'n'};
M_.endo_names_tex(43) = {'{\hat n_t}'};
M_.endo_names_long(43) = {'Home labor (log dev ss)'};
M_.endo_names(44) = {'c'};
M_.endo_names_tex(44) = {'{\hat c_t}'};
M_.endo_names_long(44) = {'Home consumption (log dev ss)'};
M_.endo_names(45) = {'c_H'};
M_.endo_names_tex(45) = {'{\hat c_{H,t}}'};
M_.endo_names_long(45) = {'Home consumption of Home-made goods (log dev ss)'};
M_.endo_names(46) = {'c_F'};
M_.endo_names_tex(46) = {'{\hat c_{F,t}}'};
M_.endo_names_long(46) = {'Home consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(47) = {'f'};
M_.endo_names_tex(47) = {'{\hat f_t}'};
M_.endo_names_long(47) = {'Home fiscal stance (log dev ss)'};
M_.endo_names(48) = {'y_starr'};
M_.endo_names_tex(48) = {'{\hat y_t^*}'};
M_.endo_names_long(48) = {'Foreign output (log dev ss)'};
M_.endo_names(49) = {'pie_starr'};
M_.endo_names_tex(49) = {'{\pi_{F,t}^*}'};
M_.endo_names_long(49) = {'Foreign inflation (log dev ss)'};
M_.endo_names(50) = {'g_starr'};
M_.endo_names_tex(50) = {'{\hat g_t^*}'};
M_.endo_names_long(50) = {'Foreign government consumption (log dev ss)'};
M_.endo_names(51) = {'n_starr'};
M_.endo_names_tex(51) = {'{\hat n_t^*}'};
M_.endo_names_long(51) = {'Foreign labor (log dev ss)'};
M_.endo_names(52) = {'c_starr'};
M_.endo_names_tex(52) = {'{\hat c_t^*}'};
M_.endo_names_long(52) = {'Foreign consumption (log dev ss)'};
M_.endo_names(53) = {'c_H_starr'};
M_.endo_names_tex(53) = {'{\hat c_{H,t}^*}'};
M_.endo_names_long(53) = {'Foreign consumption of Home-made goods (log dev ss)'};
M_.endo_names(54) = {'c_F_starr'};
M_.endo_names_tex(54) = {'{\hat c_{F,t}^*}'};
M_.endo_names_long(54) = {'Foreign consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(55) = {'f_starr'};
M_.endo_names_tex(55) = {'{\hat f_t^*}'};
M_.endo_names_long(55) = {'Foreign fiscal stance (log dev ss)'};
M_.endo_names(56) = {'ii'};
M_.endo_names_tex(56) = {'{i_t}'};
M_.endo_names_long(56) = {'Home nominal interest rate (log dev ss)'};
M_.endo_names(57) = {'ii_starr'};
M_.endo_names_tex(57) = {'{i_t^*}'};
M_.endo_names_long(57) = {'Foreign nominal interest rate (log dev ss)'};
M_.endo_names(58) = {'ii_cu'};
M_.endo_names_tex(58) = {'{i_t}'};
M_.endo_names_long(58) = {'Union nominal interest rate (log dev ss)'};
M_.endo_names(59) = {'s'};
M_.endo_names_tex(59) = {'{s_t}'};
M_.endo_names_long(59) = {'Home terms of trade (log dev ss)'};
M_.endo_names(60) = {'pie_cu'};
M_.endo_names_tex(60) = {'{\pi_{cu,t}}'};
M_.endo_names_long(60) = {'Union inflation (log dev ss)'};
M_.endo_names(61) = {'y_cu'};
M_.endo_names_tex(61) = {'{\hat y_t^{cu}}'};
M_.endo_names_long(61) = {'Union output (log dev ss)'};
M_.endo_names(62) = {'g_cu'};
M_.endo_names_tex(62) = {'{\hat g_t^{cu}}'};
M_.endo_names_long(62) = {'Union government spending (log dev ss)'};
M_.endo_names(63) = {'c_cu'};
M_.endo_names_tex(63) = {'{\hat c_t^{cu}}'};
M_.endo_names_long(63) = {'Union consumption (log dev ss)'};
M_.endo_names(64) = {'MULT_1'};
M_.endo_names_tex(64) = {'MULT\_1'};
M_.endo_names_long(64) = {'MULT_1'};
M_.endo_names(65) = {'MULT_2'};
M_.endo_names_tex(65) = {'MULT\_2'};
M_.endo_names_long(65) = {'MULT_2'};
M_.endo_names(66) = {'MULT_3'};
M_.endo_names_tex(66) = {'MULT\_3'};
M_.endo_names_long(66) = {'MULT_3'};
M_.endo_names(67) = {'MULT_4'};
M_.endo_names_tex(67) = {'MULT\_4'};
M_.endo_names_long(67) = {'MULT_4'};
M_.endo_names(68) = {'MULT_5'};
M_.endo_names_tex(68) = {'MULT\_5'};
M_.endo_names_long(68) = {'MULT_5'};
M_.endo_names(69) = {'MULT_6'};
M_.endo_names_tex(69) = {'MULT\_6'};
M_.endo_names_long(69) = {'MULT_6'};
M_.endo_names(70) = {'MULT_7'};
M_.endo_names_tex(70) = {'MULT\_7'};
M_.endo_names_long(70) = {'MULT_7'};
M_.endo_names(71) = {'MULT_8'};
M_.endo_names_tex(71) = {'MULT\_8'};
M_.endo_names_long(71) = {'MULT_8'};
M_.endo_names(72) = {'MULT_9'};
M_.endo_names_tex(72) = {'MULT\_9'};
M_.endo_names_long(72) = {'MULT_9'};
M_.endo_names(73) = {'MULT_10'};
M_.endo_names_tex(73) = {'MULT\_10'};
M_.endo_names_long(73) = {'MULT_10'};
M_.endo_names(74) = {'MULT_11'};
M_.endo_names_tex(74) = {'MULT\_11'};
M_.endo_names_long(74) = {'MULT_11'};
M_.endo_names(75) = {'MULT_12'};
M_.endo_names_tex(75) = {'MULT\_12'};
M_.endo_names_long(75) = {'MULT_12'};
M_.endo_names(76) = {'MULT_13'};
M_.endo_names_tex(76) = {'MULT\_13'};
M_.endo_names_long(76) = {'MULT_13'};
M_.endo_names(77) = {'MULT_14'};
M_.endo_names_tex(77) = {'MULT\_14'};
M_.endo_names_long(77) = {'MULT_14'};
M_.endo_names(78) = {'MULT_15'};
M_.endo_names_tex(78) = {'MULT\_15'};
M_.endo_names_long(78) = {'MULT_15'};
M_.endo_names(79) = {'MULT_16'};
M_.endo_names_tex(79) = {'MULT\_16'};
M_.endo_names_long(79) = {'MULT_16'};
M_.endo_names(80) = {'MULT_17'};
M_.endo_names_tex(80) = {'MULT\_17'};
M_.endo_names_long(80) = {'MULT_17'};
M_.endo_names(81) = {'MULT_18'};
M_.endo_names_tex(81) = {'MULT\_18'};
M_.endo_names_long(81) = {'MULT_18'};
M_.endo_names(82) = {'MULT_19'};
M_.endo_names_tex(82) = {'MULT\_19'};
M_.endo_names_long(82) = {'MULT_19'};
M_.endo_names(83) = {'MULT_20'};
M_.endo_names_tex(83) = {'MULT\_20'};
M_.endo_names_long(83) = {'MULT_20'};
M_.endo_names(84) = {'MULT_21'};
M_.endo_names_tex(84) = {'MULT\_21'};
M_.endo_names_long(84) = {'MULT_21'};
M_.endo_names(85) = {'MULT_22'};
M_.endo_names_tex(85) = {'MULT\_22'};
M_.endo_names_long(85) = {'MULT_22'};
M_.endo_names(86) = {'MULT_23'};
M_.endo_names_tex(86) = {'MULT\_23'};
M_.endo_names_long(86) = {'MULT_23'};
M_.endo_names(87) = {'MULT_24'};
M_.endo_names_tex(87) = {'MULT\_24'};
M_.endo_names_long(87) = {'MULT_24'};
M_.endo_names(88) = {'MULT_25'};
M_.endo_names_tex(88) = {'MULT\_25'};
M_.endo_names_long(88) = {'MULT_25'};
M_.endo_names(89) = {'MULT_26'};
M_.endo_names_tex(89) = {'MULT\_26'};
M_.endo_names_long(89) = {'MULT_26'};
M_.endo_names(90) = {'MULT_27'};
M_.endo_names_tex(90) = {'MULT\_27'};
M_.endo_names_long(90) = {'MULT_27'};
M_.endo_names(91) = {'MULT_28'};
M_.endo_names_tex(91) = {'MULT\_28'};
M_.endo_names_long(91) = {'MULT_28'};
M_.endo_names(92) = {'MULT_29'};
M_.endo_names_tex(92) = {'MULT\_29'};
M_.endo_names_long(92) = {'MULT_29'};
M_.endo_names(93) = {'MULT_30'};
M_.endo_names_tex(93) = {'MULT\_30'};
M_.endo_names_long(93) = {'MULT_30'};
M_.endo_names(94) = {'MULT_31'};
M_.endo_names_tex(94) = {'MULT\_31'};
M_.endo_names_long(94) = {'MULT_31'};
M_.endo_names(95) = {'MULT_32'};
M_.endo_names_tex(95) = {'MULT\_32'};
M_.endo_names_long(95) = {'MULT_32'};
M_.endo_names(96) = {'MULT_33'};
M_.endo_names_tex(96) = {'MULT\_33'};
M_.endo_names_long(96) = {'MULT_33'};
M_.endo_names(97) = {'MULT_34'};
M_.endo_names_tex(97) = {'MULT\_34'};
M_.endo_names_long(97) = {'MULT_34'};
M_.endo_names(98) = {'MULT_35'};
M_.endo_names_tex(98) = {'MULT\_35'};
M_.endo_names_long(98) = {'MULT_35'};
M_.endo_names(99) = {'MULT_36'};
M_.endo_names_tex(99) = {'MULT\_36'};
M_.endo_names_long(99) = {'MULT_36'};
M_.endo_names(100) = {'MULT_37'};
M_.endo_names_tex(100) = {'MULT\_37'};
M_.endo_names_long(100) = {'MULT_37'};
M_.endo_names(101) = {'MULT_38'};
M_.endo_names_tex(101) = {'MULT\_38'};
M_.endo_names_long(101) = {'MULT_38'};
M_.endo_names(102) = {'MULT_39'};
M_.endo_names_tex(102) = {'MULT\_39'};
M_.endo_names_long(102) = {'MULT_39'};
M_.endo_names(103) = {'MULT_40'};
M_.endo_names_tex(103) = {'MULT\_40'};
M_.endo_names_long(103) = {'MULT_40'};
M_.endo_names(104) = {'MULT_41'};
M_.endo_names_tex(104) = {'MULT\_41'};
M_.endo_names_long(104) = {'MULT_41'};
M_.endo_names(105) = {'MULT_42'};
M_.endo_names_tex(105) = {'MULT\_42'};
M_.endo_names_long(105) = {'MULT_42'};
M_.endo_names(106) = {'MULT_43'};
M_.endo_names_tex(106) = {'MULT\_43'};
M_.endo_names_long(106) = {'MULT_43'};
M_.endo_names(107) = {'MULT_44'};
M_.endo_names_tex(107) = {'MULT\_44'};
M_.endo_names_long(107) = {'MULT_44'};
M_.endo_names(108) = {'MULT_45'};
M_.endo_names_tex(108) = {'MULT\_45'};
M_.endo_names_long(108) = {'MULT_45'};
M_.endo_names(109) = {'MULT_46'};
M_.endo_names_tex(109) = {'MULT\_46'};
M_.endo_names_long(109) = {'MULT_46'};
M_.endo_names(110) = {'MULT_47'};
M_.endo_names_tex(110) = {'MULT\_47'};
M_.endo_names_long(110) = {'MULT_47'};
M_.endo_names(111) = {'MULT_48'};
M_.endo_names_tex(111) = {'MULT\_48'};
M_.endo_names_long(111) = {'MULT_48'};
M_.endo_names(112) = {'MULT_49'};
M_.endo_names_tex(112) = {'MULT\_49'};
M_.endo_names_long(112) = {'MULT_49'};
M_.endo_names(113) = {'MULT_50'};
M_.endo_names_tex(113) = {'MULT\_50'};
M_.endo_names_long(113) = {'MULT_50'};
M_.endo_names(114) = {'MULT_51'};
M_.endo_names_tex(114) = {'MULT\_51'};
M_.endo_names_long(114) = {'MULT_51'};
M_.endo_names(115) = {'MULT_52'};
M_.endo_names_tex(115) = {'MULT\_52'};
M_.endo_names_long(115) = {'MULT_52'};
M_.endo_names(116) = {'MULT_53'};
M_.endo_names_tex(116) = {'MULT\_53'};
M_.endo_names_long(116) = {'MULT_53'};
M_.endo_names(117) = {'MULT_54'};
M_.endo_names_tex(117) = {'MULT\_54'};
M_.endo_names_long(117) = {'MULT_54'};
M_.endo_names(118) = {'MULT_55'};
M_.endo_names_tex(118) = {'MULT\_55'};
M_.endo_names_long(118) = {'MULT_55'};
M_.endo_names(119) = {'MULT_56'};
M_.endo_names_tex(119) = {'MULT\_56'};
M_.endo_names_long(119) = {'MULT_56'};
M_.endo_names(120) = {'MULT_57'};
M_.endo_names_tex(120) = {'MULT\_57'};
M_.endo_names_long(120) = {'MULT_57'};
M_.endo_names(121) = {'MULT_58'};
M_.endo_names_tex(121) = {'MULT\_58'};
M_.endo_names_long(121) = {'MULT_58'};
M_.endo_names(122) = {'MULT_59'};
M_.endo_names_tex(122) = {'MULT\_59'};
M_.endo_names_long(122) = {'MULT_59'};
M_.endo_names(123) = {'MULT_60'};
M_.endo_names_tex(123) = {'MULT\_60'};
M_.endo_names_long(123) = {'MULT_60'};
M_.endo_partitions = struct();
M_.param_names = cell(31,1);
M_.param_names_tex = cell(31,1);
M_.param_names_long = cell(31,1);
M_.param_names(1) = {'BETA'};
M_.param_names_tex(1) = {'BETA'};
M_.param_names_long(1) = {'BETA'};
M_.param_names(2) = {'SIGMA'};
M_.param_names_tex(2) = {'SIGMA'};
M_.param_names_long(2) = {'SIGMA'};
M_.param_names(3) = {'PHI'};
M_.param_names_tex(3) = {'PHI'};
M_.param_names_long(3) = {'PHI'};
M_.param_names(4) = {'GAMMA'};
M_.param_names_tex(4) = {'GAMMA'};
M_.param_names_long(4) = {'GAMMA'};
M_.param_names(5) = {'ETA'};
M_.param_names_tex(5) = {'ETA'};
M_.param_names_long(5) = {'ETA'};
M_.param_names(6) = {'EPSILON'};
M_.param_names_tex(6) = {'EPSILON'};
M_.param_names_long(6) = {'EPSILON'};
M_.param_names(7) = {'h'};
M_.param_names_tex(7) = {'h'};
M_.param_names_long(7) = {'h'};
M_.param_names(8) = {'ALPHA_bar'};
M_.param_names_tex(8) = {'ALPHA\_bar'};
M_.param_names_long(8) = {'ALPHA_bar'};
M_.param_names(9) = {'THETA'};
M_.param_names_tex(9) = {'THETA'};
M_.param_names_long(9) = {'THETA'};
M_.param_names(10) = {'THETA_starr'};
M_.param_names_tex(10) = {'THETA\_starr'};
M_.param_names_long(10) = {'THETA_starr'};
M_.param_names(11) = {'DELTA'};
M_.param_names_tex(11) = {'DELTA'};
M_.param_names_long(11) = {'DELTA'};
M_.param_names(12) = {'CHI_C'};
M_.param_names_tex(12) = {'CHI\_C'};
M_.param_names_long(12) = {'CHI_C'};
M_.param_names(13) = {'CHI_G'};
M_.param_names_tex(13) = {'CHI\_G'};
M_.param_names_long(13) = {'CHI_G'};
M_.param_names(14) = {'N0'};
M_.param_names_tex(14) = {'N0'};
M_.param_names_long(14) = {'N0'};
M_.param_names(15) = {'N0_starr'};
M_.param_names_tex(15) = {'N0\_starr'};
M_.param_names_long(15) = {'N0_starr'};
M_.param_names(16) = {'C0'};
M_.param_names_tex(16) = {'C0'};
M_.param_names_long(16) = {'C0'};
M_.param_names(17) = {'C0_starr'};
M_.param_names_tex(17) = {'C0\_starr'};
M_.param_names_long(17) = {'C0_starr'};
M_.param_names(18) = {'G0'};
M_.param_names_tex(18) = {'G0'};
M_.param_names_long(18) = {'G0'};
M_.param_names(19) = {'G0_starr'};
M_.param_names_tex(19) = {'G0\_starr'};
M_.param_names_long(19) = {'G0_starr'};
M_.param_names(20) = {'ALPHA'};
M_.param_names_tex(20) = {'ALPHA'};
M_.param_names_long(20) = {'ALPHA'};
M_.param_names(21) = {'ALPHA_starr'};
M_.param_names_tex(21) = {'ALPHA\_starr'};
M_.param_names_long(21) = {'ALPHA_starr'};
M_.param_names(22) = {'LAMBDA'};
M_.param_names_tex(22) = {'LAMBDA'};
M_.param_names_long(22) = {'LAMBDA'};
M_.param_names(23) = {'LAMBDA_starr'};
M_.param_names_tex(23) = {'LAMBDA\_starr'};
M_.param_names_long(23) = {'LAMBDA_starr'};
M_.param_names(24) = {'W_ALPHA_bar'};
M_.param_names_tex(24) = {'W\_ALPHA\_bar'};
M_.param_names_long(24) = {'W_ALPHA_bar'};
M_.param_names(25) = {'SIGMA_tilde'};
M_.param_names_tex(25) = {'SIGMA\_tilde'};
M_.param_names_long(25) = {'SIGMA_tilde'};
M_.param_names(26) = {'THETA_ALPHA_bar'};
M_.param_names_tex(26) = {'THETA\_ALPHA\_bar'};
M_.param_names_long(26) = {'THETA_ALPHA_bar'};
M_.param_names(27) = {'SIGMA_tilde_ALPHA_bar'};
M_.param_names_tex(27) = {'SIGMA\_tilde\_ALPHA\_bar'};
M_.param_names_long(27) = {'SIGMA_tilde_ALPHA_bar'};
M_.param_names(28) = {'OMEGA'};
M_.param_names_tex(28) = {'OMEGA'};
M_.param_names_long(28) = {'OMEGA'};
M_.param_names(29) = {'OMEGA_starr'};
M_.param_names_tex(29) = {'OMEGA\_starr'};
M_.param_names_long(29) = {'OMEGA_starr'};
M_.param_names(30) = {'RHOA'};
M_.param_names_tex(30) = {'RHOA'};
M_.param_names_long(30) = {'RHOA'};
M_.param_names(31) = {'optimal_policy_discount_factor'};
M_.param_names_tex(31) = {'optimal\_policy\_discount\_factor'};
M_.param_names_long(31) = {'optimal_policy_discount_factor'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 123;
M_.param_nbr = 31;
M_.orig_endo_nbr = 63;
M_.aux_vars(1).endo_index = 64;
M_.aux_vars(1).type = 6;
M_.aux_vars(1).eq_nbr = 1;
M_.aux_vars(2).endo_index = 65;
M_.aux_vars(2).type = 6;
M_.aux_vars(2).eq_nbr = 2;
M_.aux_vars(3).endo_index = 66;
M_.aux_vars(3).type = 6;
M_.aux_vars(3).eq_nbr = 3;
M_.aux_vars(4).endo_index = 67;
M_.aux_vars(4).type = 6;
M_.aux_vars(4).eq_nbr = 4;
M_.aux_vars(5).endo_index = 68;
M_.aux_vars(5).type = 6;
M_.aux_vars(5).eq_nbr = 5;
M_.aux_vars(6).endo_index = 69;
M_.aux_vars(6).type = 6;
M_.aux_vars(6).eq_nbr = 6;
M_.aux_vars(7).endo_index = 70;
M_.aux_vars(7).type = 6;
M_.aux_vars(7).eq_nbr = 7;
M_.aux_vars(8).endo_index = 71;
M_.aux_vars(8).type = 6;
M_.aux_vars(8).eq_nbr = 8;
M_.aux_vars(9).endo_index = 72;
M_.aux_vars(9).type = 6;
M_.aux_vars(9).eq_nbr = 9;
M_.aux_vars(10).endo_index = 73;
M_.aux_vars(10).type = 6;
M_.aux_vars(10).eq_nbr = 10;
M_.aux_vars(11).endo_index = 74;
M_.aux_vars(11).type = 6;
M_.aux_vars(11).eq_nbr = 11;
M_.aux_vars(12).endo_index = 75;
M_.aux_vars(12).type = 6;
M_.aux_vars(12).eq_nbr = 12;
M_.aux_vars(13).endo_index = 76;
M_.aux_vars(13).type = 6;
M_.aux_vars(13).eq_nbr = 13;
M_.aux_vars(14).endo_index = 77;
M_.aux_vars(14).type = 6;
M_.aux_vars(14).eq_nbr = 14;
M_.aux_vars(15).endo_index = 78;
M_.aux_vars(15).type = 6;
M_.aux_vars(15).eq_nbr = 15;
M_.aux_vars(16).endo_index = 79;
M_.aux_vars(16).type = 6;
M_.aux_vars(16).eq_nbr = 16;
M_.aux_vars(17).endo_index = 80;
M_.aux_vars(17).type = 6;
M_.aux_vars(17).eq_nbr = 17;
M_.aux_vars(18).endo_index = 81;
M_.aux_vars(18).type = 6;
M_.aux_vars(18).eq_nbr = 18;
M_.aux_vars(19).endo_index = 82;
M_.aux_vars(19).type = 6;
M_.aux_vars(19).eq_nbr = 19;
M_.aux_vars(20).endo_index = 83;
M_.aux_vars(20).type = 6;
M_.aux_vars(20).eq_nbr = 20;
M_.aux_vars(21).endo_index = 84;
M_.aux_vars(21).type = 6;
M_.aux_vars(21).eq_nbr = 21;
M_.aux_vars(22).endo_index = 85;
M_.aux_vars(22).type = 6;
M_.aux_vars(22).eq_nbr = 22;
M_.aux_vars(23).endo_index = 86;
M_.aux_vars(23).type = 6;
M_.aux_vars(23).eq_nbr = 23;
M_.aux_vars(24).endo_index = 87;
M_.aux_vars(24).type = 6;
M_.aux_vars(24).eq_nbr = 24;
M_.aux_vars(25).endo_index = 88;
M_.aux_vars(25).type = 6;
M_.aux_vars(25).eq_nbr = 25;
M_.aux_vars(26).endo_index = 89;
M_.aux_vars(26).type = 6;
M_.aux_vars(26).eq_nbr = 26;
M_.aux_vars(27).endo_index = 90;
M_.aux_vars(27).type = 6;
M_.aux_vars(27).eq_nbr = 27;
M_.aux_vars(28).endo_index = 91;
M_.aux_vars(28).type = 6;
M_.aux_vars(28).eq_nbr = 28;
M_.aux_vars(29).endo_index = 92;
M_.aux_vars(29).type = 6;
M_.aux_vars(29).eq_nbr = 29;
M_.aux_vars(30).endo_index = 93;
M_.aux_vars(30).type = 6;
M_.aux_vars(30).eq_nbr = 30;
M_.aux_vars(31).endo_index = 94;
M_.aux_vars(31).type = 6;
M_.aux_vars(31).eq_nbr = 31;
M_.aux_vars(32).endo_index = 95;
M_.aux_vars(32).type = 6;
M_.aux_vars(32).eq_nbr = 32;
M_.aux_vars(33).endo_index = 96;
M_.aux_vars(33).type = 6;
M_.aux_vars(33).eq_nbr = 33;
M_.aux_vars(34).endo_index = 97;
M_.aux_vars(34).type = 6;
M_.aux_vars(34).eq_nbr = 34;
M_.aux_vars(35).endo_index = 98;
M_.aux_vars(35).type = 6;
M_.aux_vars(35).eq_nbr = 35;
M_.aux_vars(36).endo_index = 99;
M_.aux_vars(36).type = 6;
M_.aux_vars(36).eq_nbr = 36;
M_.aux_vars(37).endo_index = 100;
M_.aux_vars(37).type = 6;
M_.aux_vars(37).eq_nbr = 37;
M_.aux_vars(38).endo_index = 101;
M_.aux_vars(38).type = 6;
M_.aux_vars(38).eq_nbr = 38;
M_.aux_vars(39).endo_index = 102;
M_.aux_vars(39).type = 6;
M_.aux_vars(39).eq_nbr = 39;
M_.aux_vars(40).endo_index = 103;
M_.aux_vars(40).type = 6;
M_.aux_vars(40).eq_nbr = 40;
M_.aux_vars(41).endo_index = 104;
M_.aux_vars(41).type = 6;
M_.aux_vars(41).eq_nbr = 41;
M_.aux_vars(42).endo_index = 105;
M_.aux_vars(42).type = 6;
M_.aux_vars(42).eq_nbr = 42;
M_.aux_vars(43).endo_index = 106;
M_.aux_vars(43).type = 6;
M_.aux_vars(43).eq_nbr = 43;
M_.aux_vars(44).endo_index = 107;
M_.aux_vars(44).type = 6;
M_.aux_vars(44).eq_nbr = 44;
M_.aux_vars(45).endo_index = 108;
M_.aux_vars(45).type = 6;
M_.aux_vars(45).eq_nbr = 45;
M_.aux_vars(46).endo_index = 109;
M_.aux_vars(46).type = 6;
M_.aux_vars(46).eq_nbr = 46;
M_.aux_vars(47).endo_index = 110;
M_.aux_vars(47).type = 6;
M_.aux_vars(47).eq_nbr = 47;
M_.aux_vars(48).endo_index = 111;
M_.aux_vars(48).type = 6;
M_.aux_vars(48).eq_nbr = 48;
M_.aux_vars(49).endo_index = 112;
M_.aux_vars(49).type = 6;
M_.aux_vars(49).eq_nbr = 49;
M_.aux_vars(50).endo_index = 113;
M_.aux_vars(50).type = 6;
M_.aux_vars(50).eq_nbr = 50;
M_.aux_vars(51).endo_index = 114;
M_.aux_vars(51).type = 6;
M_.aux_vars(51).eq_nbr = 51;
M_.aux_vars(52).endo_index = 115;
M_.aux_vars(52).type = 6;
M_.aux_vars(52).eq_nbr = 52;
M_.aux_vars(53).endo_index = 116;
M_.aux_vars(53).type = 6;
M_.aux_vars(53).eq_nbr = 53;
M_.aux_vars(54).endo_index = 117;
M_.aux_vars(54).type = 6;
M_.aux_vars(54).eq_nbr = 54;
M_.aux_vars(55).endo_index = 118;
M_.aux_vars(55).type = 6;
M_.aux_vars(55).eq_nbr = 55;
M_.aux_vars(56).endo_index = 119;
M_.aux_vars(56).type = 6;
M_.aux_vars(56).eq_nbr = 56;
M_.aux_vars(57).endo_index = 120;
M_.aux_vars(57).type = 6;
M_.aux_vars(57).eq_nbr = 57;
M_.aux_vars(58).endo_index = 121;
M_.aux_vars(58).type = 6;
M_.aux_vars(58).eq_nbr = 58;
M_.aux_vars(59).endo_index = 122;
M_.aux_vars(59).type = 6;
M_.aux_vars(59).eq_nbr = 59;
M_.aux_vars(60).endo_index = 123;
M_.aux_vars(60).type = 6;
M_.aux_vars(60).eq_nbr = 60;
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(2, 2);
M_.Correlation_matrix = eye(2, 2);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 60;
M_.eq_nbr = 123;
M_.ramsey_eq_nbr = 63;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 9 0;
 0 10 0;
 0 11 0;
 0 12 0;
 0 13 0;
 0 14 0;
 0 15 0;
 0 16 0;
 0 17 0;
 0 18 0;
 0 19 0;
 0 20 0;
 0 21 0;
 0 22 0;
 0 23 0;
 0 24 0;
 0 25 0;
 1 26 132;
 2 27 133;
 0 28 134;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 0 36 135;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 136;
 0 49 137;
 0 50 138;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 139;
 0 57 140;
 0 58 141;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 0 86 0;
 3 87 0;
 4 88 0;
 0 89 0;
 0 90 0;
 0 91 0;
 5 92 0;
 6 93 0;
 7 94 0;
 8 95 0;
 0 96 0;
 0 97 0;
 0 98 0;
 0 99 0;
 0 100 0;
 0 101 0;
 0 102 0;
 0 103 0;
 0 104 0;
 0 105 0;
 0 106 0;
 0 107 0;
 0 108 0;
 0 109 0;
 0 110 0;
 0 111 0;
 0 112 0;
 0 113 0;
 0 114 0;
 0 115 0;
 0 116 0;
 0 117 0;
 0 118 0;
 0 119 0;
 0 120 0;
 0 121 0;
 0 122 0;
 0 123 0;
 0 124 0;
 0 125 0;
 0 126 0;
 0 127 0;
 0 128 0;
 0 129 0;
 0 130 142;
 0 131 143;]';
M_.nstatic = 105;
M_.nfwrd   = 10;
M_.npred   = 6;
M_.nboth   = 2;
M_.nsfwrd   = 12;
M_.nspred   = 8;
M_.ndynamic   = 18;
M_.dynamic_tmp_nbr = [7; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  64 , 'name' , 'Home natural marginal cost condition' ;
  65 , 'name' , 'Foreign natural marginal cost condition' ;
  66 , 'name' , 'Home natural good-market clearing condition' ;
  67 , 'name' , 'Foreign natural good-market clearing condition' ;
  68 , 'name' , 'Natural IRS condition' ;
  69 , 'name' , 'Home natural government spending condition' ;
  70 , 'name' , 'Foreign natural government spending condition' ;
  71 , 'name' , 'Home natural consumption of Home-made goods' ;
  72 , 'name' , 'Home natural consumption of Foreign-made goods' ;
  73 , 'name' , 'Foreign natural consumption of Home-made goods' ;
  74 , 'name' , 'Foreign natural consumption of Foreign-made goods' ;
  75 , 'name' , 'n_nat' ;
  76 , 'name' , 'n_nat_starr' ;
  77 , 'name' , 'Home natural fiscal stance definition' ;
  78 , 'name' , 'Foreign natural fiscal stance definition' ;
  79 , 'name' , 'Home natural rate' ;
  80 , 'name' , 'Foreign natural rate' ;
  81 , 'name' , 'y_nat_cu' ;
  82 , 'name' , 'g_nat_cu' ;
  83 , 'name' , 'r_nat_cu' ;
  84 , 'name' , 'Home New Keynesian Phillips Curve' ;
  85 , 'name' , 'Foreign New Keynesian Phillips Curve' ;
  86 , 'name' , 'Home Dynamic IS Curve' ;
  87 , 'name' , 'Foreign Dynamic IS Curve' ;
  88 , 'name' , 'IRS' ;
  89 , 'name' , 'Home production function' ;
  90 , 'name' , 'Foreign production function' ;
  91 , 'name' , 'Home good-market clearing condition' ;
  92 , 'name' , 'Foreign good-market clearing condition' ;
  93 , 'name' , 'Home fiscal stance definition' ;
  94 , 'name' , 'Foreign fiscal stance definition' ;
  95 , 'name' , 'Home consumption of Home-made goods' ;
  96 , 'name' , 'Home consumption of Foreign-made goods' ;
  97 , 'name' , 'Foreign consumption of Home-made goods' ;
  98 , 'name' , 'Foreign consumption of Foreign-made goods' ;
  99 , 'name' , 'Home interest rate' ;
  100 , 'name' , 'Foreign interest rate' ;
  101 , 'name' , 'Union inflation' ;
  102 , 'name' , 'Union output' ;
  103 , 'name' , 'Union government spending' ;
  104 , 'name' , 'Union consumption' ;
  105 , 'name' , 'Home output gap definition' ;
  106 , 'name' , 'Home governmpent spending gap definition' ;
  107 , 'name' , 'Home consumption gap definition' ;
  108 , 'name' , 'Foreign labor gap definition' ;
  109 , 'name' , 'Home fiscal stance gap definition' ;
  110 , 'name' , 'Home interest rate gap definition' ;
  111 , 'name' , 'Home terms of trade gap definition' ;
  112 , 'name' , 'Foreign output gap definition' ;
  113 , 'name' , 'Foreign governmpent spending gap definition' ;
  114 , 'name' , 'Foreign consumption gap definition' ;
  115 , 'name' , 'Foreign labor gap definition' ;
  116 , 'name' , 'Foreign fiscal stance gap definition' ;
  117 , 'name' , 'Foreign interest rate gap definition' ;
  118 , 'name' , 'Union output gap definition' ;
  119 , 'name' , 'Union governmpent spending gap definition' ;
  120 , 'name' , 'Union consumption gap definition' ;
  121 , 'name' , 'Union interest rate gap definition' ;
  122 , 'name' , 'a' ;
  123 , 'name' , 'a_starr' ;
};
M_.mapping.y_gap.eqidx = [1 105 118 ];
M_.mapping.g_gap.eqidx = [2 106 119 ];
M_.mapping.c_gap.eqidx = [3 107 120 ];
M_.mapping.f_gap.eqidx = [109 ];
M_.mapping.n_gap.eqidx = [108 ];
M_.mapping.ii_gap.eqidx = [110 ];
M_.mapping.y_gap_starr.eqidx = [7 112 118 ];
M_.mapping.g_gap_starr.eqidx = [8 113 119 ];
M_.mapping.c_gap_starr.eqidx = [9 114 120 ];
M_.mapping.f_gap_starr.eqidx = [116 ];
M_.mapping.n_gap_starr.eqidx = [115 ];
M_.mapping.ii_gap_starr.eqidx = [117 ];
M_.mapping.s_gap.eqidx = [13 111 ];
M_.mapping.y_gap_cu.eqidx = [118 ];
M_.mapping.g_gap_cu.eqidx = [119 ];
M_.mapping.c_gap_cu.eqidx = [120 ];
M_.mapping.ii_gap_cu.eqidx = [121 ];
M_.mapping.a.eqidx = [64 75 79 84 89 122 ];
M_.mapping.a_starr.eqidx = [65 76 80 85 90 123 ];
M_.mapping.eps_a.eqidx = [122 ];
M_.mapping.eps_a_starr.eqidx = [123 ];
M_.mapping.y_nat.eqidx = [64 66 68 75 77 79 81 105 ];
M_.mapping.g_nat.eqidx = [66 68 69 77 82 106 ];
M_.mapping.c_nat.eqidx = [64 66 69 71 72 107 ];
M_.mapping.n_nat.eqidx = [75 108 ];
M_.mapping.c_H_nat.eqidx = [71 ];
M_.mapping.c_F_nat.eqidx = [72 ];
M_.mapping.r_nat.eqidx = [79 83 110 ];
M_.mapping.f_nat.eqidx = [77 109 ];
M_.mapping.y_nat_starr.eqidx = [65 67 68 76 78 80 81 112 ];
M_.mapping.g_nat_starr.eqidx = [67 68 70 78 82 113 ];
M_.mapping.c_nat_starr.eqidx = [65 67 70 73 74 114 ];
M_.mapping.c_H_nat_starr.eqidx = [73 ];
M_.mapping.c_F_nat_starr.eqidx = [74 ];
M_.mapping.n_nat_starr.eqidx = [76 115 ];
M_.mapping.r_nat_starr.eqidx = [80 83 117 ];
M_.mapping.f_nat_starr.eqidx = [78 116 ];
M_.mapping.s_nat.eqidx = [64 65 66 67 68 69 70 71 72 73 74 111 ];
M_.mapping.y_nat_cu.eqidx = [81 ];
M_.mapping.g_nat_cu.eqidx = [82 ];
M_.mapping.r_nat_cu.eqidx = [83 121 ];
M_.mapping.y.eqidx = [84 85 86 87 88 89 91 93 102 105 ];
M_.mapping.pie.eqidx = [41 84 86 101 ];
M_.mapping.g.eqidx = [84 85 86 87 88 91 93 103 106 ];
M_.mapping.n.eqidx = [89 108 ];
M_.mapping.c.eqidx = [91 95 96 104 107 ];
M_.mapping.c_H.eqidx = [95 ];
M_.mapping.c_F.eqidx = [96 ];
M_.mapping.f.eqidx = [93 109 ];
M_.mapping.y_starr.eqidx = [84 85 86 87 88 90 92 94 102 112 ];
M_.mapping.pie_starr.eqidx = [49 85 87 101 ];
M_.mapping.g_starr.eqidx = [84 85 86 87 88 92 94 103 113 ];
M_.mapping.n_starr.eqidx = [90 115 ];
M_.mapping.c_starr.eqidx = [92 97 98 104 114 ];
M_.mapping.c_H_starr.eqidx = [97 ];
M_.mapping.c_F_starr.eqidx = [98 ];
M_.mapping.f_starr.eqidx = [94 116 ];
M_.mapping.ii.eqidx = [86 99 110 121 ];
M_.mapping.ii_starr.eqidx = [87 100 117 ];
M_.mapping.ii_cu.eqidx = [99 100 ];
M_.mapping.s.eqidx = [88 91 92 95 96 97 98 111 ];
M_.mapping.pie_cu.eqidx = [101 ];
M_.mapping.y_cu.eqidx = [102 ];
M_.mapping.g_cu.eqidx = [103 ];
M_.mapping.c_cu.eqidx = [104 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [18 19 79 80 84 85 86 87 ];
M_.exo_names_orig_ord = [1:2];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(123, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = NaN(31, 1);
M_.endo_trends = struct('deflator', cell(123, 1), 'log_deflator', cell(123, 1), 'growth_factor', cell(123, 1), 'log_growth_factor', cell(123, 1));
M_.NNZDerivatives = [435; 0; -1; ];
M_.static_tmp_nbr = [7; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
M_.Sigma_e(2, 2) = 1;
M_.params(1) = 0.98;
BETA = M_.params(1);
M_.params(2) = 3;
SIGMA = M_.params(2);
M_.params(3) = 1;
PHI = M_.params(3);
M_.params(4) = 1;
GAMMA = M_.params(4);
M_.params(5) = 4.5;
ETA = M_.params(5);
M_.params(6) = 6;
EPSILON = M_.params(6);
M_.params(7) = 0.5;
h = M_.params(7);
M_.params(8) = 0.01;
ALPHA_bar = M_.params(8);
M_.params(9) = 0.55;
THETA = M_.params(9);
M_.params(10) = 0.75;
THETA_starr = M_.params(10);
M_.params(11) = 0.3;
DELTA = M_.params(11);
M_.params(12) = (1-M_.params(11))^M_.params(2);
CHI_C = M_.params(12);
M_.params(13) = M_.params(11)^M_.params(4);
CHI_G = M_.params(13);
M_.params(20) = M_.params(8)*(1-M_.params(7));
ALPHA = M_.params(20);
M_.params(21) = M_.params(8)*M_.params(7);
ALPHA_starr = M_.params(21);
M_.params(22) = (1-M_.params(9))*(1-M_.params(9)*M_.params(1))/M_.params(9);
LAMBDA = M_.params(22);
M_.params(23) = (1-M_.params(10))*(1-M_.params(1)*M_.params(10))/M_.params(10);
LAMBDA_starr = M_.params(23);
M_.params(24) = 1+(2-M_.params(8))*(M_.params(2)*M_.params(5)-1);
W_ALPHA_bar = M_.params(24);
M_.params(25) = M_.params(2)/(1-M_.params(11));
SIGMA_tilde = M_.params(25);
M_.params(26) = M_.params(24)-1;
THETA_ALPHA_bar = M_.params(26);
M_.params(27) = M_.params(25)/(1+M_.params(8)*M_.params(26));
SIGMA_tilde_ALPHA_bar = M_.params(27);
M_.params(28) = 1+M_.params(8)*M_.params(7)*M_.params(26);
OMEGA = M_.params(28);
M_.params(29) = 1+M_.params(8)*(1-M_.params(7))*M_.params(26);
OMEGA_starr = M_.params(29);
M_.params(14) = M_.params(7);
N0 = M_.params(14);
M_.params(15) = 1-M_.params(7);
N0_starr = M_.params(15);
M_.params(16) = (1-M_.params(11))*M_.params(14);
C0 = M_.params(16);
M_.params(17) = (1-M_.params(11))*M_.params(15);
C0_starr = M_.params(17);
M_.params(18) = M_.params(11)*M_.params(14);
G0 = M_.params(18);
M_.params(19) = M_.params(11)*M_.params(15);
G0_starr = M_.params(19);
M_.params(30) = 0.85;
RHOA = M_.params(30);
M_.NNZDerivatives_objective = [9;9;0;];
M_.objective_tmp_nbr = [1; 0; 0; 0; ];
M_.params(31) = M_.params(1);
optimal_policy_discount_factor = M_.params(31);
options_.ramsey_policy = true;
options_.instruments = {'ii_cu';'g_gap';'g_gap_starr'};
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 200;
options_.nograph = true;
options_.order = 2;
options_.irf_shocks = {'eps_a_starr'};
var_list_ = {};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
pol_name="RAMSEY - EQUAL_WEIGHT"
calibration_name="h_"+h*100+" - ALPHA_bar_"+ALPHA_bar*100+" - THETA_"+THETA*100+" - THETA_starr_"+THETA_starr*100+" - DELTA_"+DELTA*100
folder_name = "OUTPUT/"+pol_name+"/"+calibration_name
file_name = pol_name + " - " + calibration_name
mkdir(folder_name)
T_irf=options_.irf
T_plot=40
t = 1:1:T_plot;
zeroline = ones(T_plot,1)*0;
figure('NumberTitle', 'off','visible','off') 
subplot(3,3,1); 
Home=plot(t,c_eps_a_starr(1:T_plot),'LineWidth',1.5,'DisplayName','Home'); hold on
Foreign=plot(t,c_starr_eps_a_starr(1:T_plot),'LineWidth',1.5,'DisplayName','Foreign'); hold on
plot(t,zeroline,'LineWidth',0.5,'Color','Black')
title('Consumption : $$\hat c_t$$ and $$\hat c_t^*$$','interpreter','latex','FontSize',10);
legend([Home,Foreign],{'Home','Foreign'},'location','southeast');
subplot(3,3,4); 
plot(t,c_nat_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,c_nat_starr_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,zeroline,'LineWidth',0.5,'Color','Black')
title('Natural Consumption : $$\hat{\bar c}_t$$ and $$\hat{\bar c}_t^*$$','interpreter','latex','FontSize',10);
subplot(3,3,7); 
plot(t,c_gap_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,c_gap_starr_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,zeroline,'LineWidth',0.5,'Color','Black')
title('Consumption Gap : $$\tilde c_t$$ and $$\tilde c_t^*$$','interpreter','latex','FontSize',10);
subplot(3,3,2); 
plot(t,y_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,y_starr_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,zeroline,'LineWidth',0.5,'Color','Black')
title('Output : $$\hat y_t$$ and $$\hat y_t^*$$','interpreter','latex','FontSize',10);
subplot(3,3,5); 
plot(t,y_nat_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,y_nat_starr_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,zeroline,'LineWidth',0.5,'Color','Black')
title('Natural Output : $$\hat{\bar y}_t$$ and $$\hat{\bar y}_t^*$$','interpreter','latex','FontSize',10);
subplot(3,3,8); 
plot(t,y_gap_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,y_gap_starr_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,zeroline,'LineWidth',0.5,'Color','Black')
title('Output Gap : $$\tilde y_t$$ and $$\tilde y_t^*$$','interpreter','latex','FontSize',10);
subplot(3,3,3); 
plot(t,g_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,g_starr_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,zeroline,'LineWidth',0.5,'Color','Black')
title('Government Consumption : $$\hat g_t$$ and $$\hat g_t^*$$','interpreter','latex','FontSize',10);
subplot(3,3,6); 
plot(t,g_nat_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,g_nat_starr_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,zeroline,'LineWidth',0.5,'Color','Black')
title('Natural Government Consumption : $$\hat{\bar g}_t$$ and $$\hat{\bar g}_t^*$$','interpreter','latex','FontSize',10);
subplot(3,3,9); 
plot(t,g_gap_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,g_gap_starr_eps_a_starr(1:T_plot),'LineWidth',1.5); hold on
plot(t,zeroline,'LineWidth',0.5,'Color','Black');
title('Government Consumption Gap : $$\tilde g_t$$ and $$\tilde g_t^*$$','interpreter','latex','FontSize',10);
test="RAMSEY,EQUAL WEIGHT"
annotation('textbox', [0, 0.05, 1, 0],'interpreter','latex','string',[char(strrep(strrep(pol_name," - ",", "),"_"," ")) ', $$h$$ = ' num2str(h) ', $$\bar{\alpha}$$ =' num2str(ALPHA_bar) ', $$\theta$$ = ' num2str(THETA) ', $$\theta^*$$ = ' num2str(THETA_starr) ', $$\delta$$ = ' num2str(DELTA)],'FontSize',10)
figure_name = "y_c_g"
set(gcf,'Position',[1 1 1366 691])
saveas(gcf,folder_name+"/"+figure_name+".png")
sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE(h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)))
sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE(h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,C0*(c_eps_a_starr+1)/h,N0*(n_eps_a_starr+1)/h,G0*(g_eps_a_starr+1)/h,C0_starr*(c_starr_eps_a_starr+1)/(1-h), N0_starr*(n_starr_eps_a_starr+1)/(1-h),G0_starr*(g_starr_eps_a_starr+1)/(1-h)))
W_000 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(1.00,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_005 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.995,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_010 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.990,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_015 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.985,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_020 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.980,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_025 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.975,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_030 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.970,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_035 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.965,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_040 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.960,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_045 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.955,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_050 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.950,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_055 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.945,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_060 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.940,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_065 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.935,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_070 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.930,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_075 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.925,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_080 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.920,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_085 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.915,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_090 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.910,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_095 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.905,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_100 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(0.900,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_000_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(1.00,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_005_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.995,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_010_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.990,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_015_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.985,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_020_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.980,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_025_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.975,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_030_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.970,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_035_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.965,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_040_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.960,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_045_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.955,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_050_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.950,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_055_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.945,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_060_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.940,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_065_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.935,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_070_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.930,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_075_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.925,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_080_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.920,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_085_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.915,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_090_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.910,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_095_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.905,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
W_100_2 = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_ConsGov(0.900,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_eps_a_starr+log(C0))/h,exp(n_eps_a_starr+log(N0))/h,exp(g_eps_a_starr+log(G0))/h,exp(c_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_starr_eps_a_starr+log(G0_starr))/(1-h)));
CEV_table=table([W_000;W_005;W_010;W_015;W_020;W_025;W_030;W_035;W_040;W_045;W_050;W_055;W_060;W_065;W_070;W_075;W_080;W_085;W_090;W_095;W_100],[W_000_2;W_005_2;W_010_2;W_015_2;W_020_2;W_025_2;W_030_2;W_035_2;W_040_2;W_045_2;W_050_2;W_055_2;W_060_2;W_065_2;W_070_2;W_075_2;W_080_2;W_085_2;W_090_2;W_095_2;W_100_2],'VariableNames',{'CEV_Cons','CEV_ConsGov'},'RowNames',{'0.0%','0.5%','1.0%','1.5%','2.0%','2.5%','3.0%','3.5%','4.0%','4.5%','5.0%','5.5%','6.0%','6.5%','7.0%','7.5%','8.0%','8.5%','9.0%','9.5%','10.0%'})
writetable(CEV_table, "my_table"+extension_name+".txt")
W_000_nat = sum(cumprod(ones(1,T_irf)*BETA)'.*WELFARE_CEV_Cons(1.00,h,CHI_C,CHI_G,SIGMA,PHI,GAMMA,exp(c_nat_eps_a_starr+log(C0))/h,exp(n_nat_eps_a_starr+log(N0))/h,exp(g_nat_eps_a_starr+log(G0))/h,exp(c_nat_starr_eps_a_starr+log(C0_starr))/(1-h), exp(n_nat_starr_eps_a_starr+log(N0_starr))/(1-h),exp(g_nat_starr_eps_a_starr+log(G0_starr))/(1-h)))


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_4_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_4_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_4_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_4_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_4_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_4_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_4_results.mat'], 'oo_recursive_', '-append');
end
disp('Note: 2 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
