%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'MODEL_MAIN_2';
M_.dynare_version = '5.0';
oo_.dynare_version = '5.0';
options_.dynare_version = '5.0';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(2,1);
M_.exo_names_tex = cell(2,1);
M_.exo_names_long = cell(2,1);
M_.exo_names(1) = {'eps_a'};
M_.exo_names_tex(1) = {'{\epsilon_a}'};
M_.exo_names_long(1) = {'Home technology shock'};
M_.exo_names(2) = {'eps_a_starr'};
M_.exo_names_tex(2) = {'{\epsilon_a^*}'};
M_.exo_names_long(2) = {'Foreign technology shock'};
M_.endo_names = cell(89,1);
M_.endo_names_tex = cell(89,1);
M_.endo_names_long = cell(89,1);
M_.endo_names(1) = {'y_gap'};
M_.endo_names_tex(1) = {'{\tilde y_t}'};
M_.endo_names_long(1) = {'Home output gap (log dev ss)'};
M_.endo_names(2) = {'g_gap'};
M_.endo_names_tex(2) = {'{\tilde g_t}'};
M_.endo_names_long(2) = {'Home government spending gap (log dev ss)'};
M_.endo_names(3) = {'c_gap'};
M_.endo_names_tex(3) = {'{\tilde c_t}'};
M_.endo_names_long(3) = {'Home consumption gap (log dev ss)'};
M_.endo_names(4) = {'f_gap'};
M_.endo_names_tex(4) = {'{\tilde f_t}'};
M_.endo_names_long(4) = {'f_gap'};
M_.endo_names(5) = {'y_gap_starr'};
M_.endo_names_tex(5) = {'{\tilde y_t^*}'};
M_.endo_names_long(5) = {'Foreign output gap (log dev ss)'};
M_.endo_names(6) = {'g_gap_starr'};
M_.endo_names_tex(6) = {'{\tilde g_t^*}'};
M_.endo_names_long(6) = {'Foreign government spending gap (log dev ss)'};
M_.endo_names(7) = {'c_gap_starr'};
M_.endo_names_tex(7) = {'{\tilde c_t^*}'};
M_.endo_names_long(7) = {'Foreign consumption gap (log dev ss)'};
M_.endo_names(8) = {'f_gap_starr'};
M_.endo_names_tex(8) = {'{\tilde f_t^*}'};
M_.endo_names_long(8) = {'f_gap_starr'};
M_.endo_names(9) = {'s_gap'};
M_.endo_names_tex(9) = {'{\tilde s_t}'};
M_.endo_names_long(9) = {'Home terms of trade gap (log dev ss)'};
M_.endo_names(10) = {'y_gap_cu'};
M_.endo_names_tex(10) = {'{\tilde y_t^{cu}}'};
M_.endo_names_long(10) = {'Union output gap (log dev ss)'};
M_.endo_names(11) = {'g_gap_cu'};
M_.endo_names_tex(11) = {'{\tilde g_t^{cu}}'};
M_.endo_names_long(11) = {'Union government spending gap (log dev ss)'};
M_.endo_names(12) = {'c_gap_cu'};
M_.endo_names_tex(12) = {'{\tilde c_t^{cu}}'};
M_.endo_names_long(12) = {'Union government spending gap (log dev ss)'};
M_.endo_names(13) = {'a'};
M_.endo_names_tex(13) = {'{a_t}'};
M_.endo_names_long(13) = {'Home productivity (log dev ss)'};
M_.endo_names(14) = {'a_starr'};
M_.endo_names_tex(14) = {'{a_t^*}'};
M_.endo_names_long(14) = {'Foreign productivity (log dev ss)'};
M_.endo_names(15) = {'y_nat'};
M_.endo_names_tex(15) = {'{\hat {\bar y}_t}'};
M_.endo_names_long(15) = {'Home natural output (log dev ss)'};
M_.endo_names(16) = {'g_nat'};
M_.endo_names_tex(16) = {'{\hat {\bar g}_t}'};
M_.endo_names_long(16) = {'Home natural government spending (log dev ss)'};
M_.endo_names(17) = {'c_nat'};
M_.endo_names_tex(17) = {'{\hat {\bar c}_t}'};
M_.endo_names_long(17) = {'Home natural consumption (log dev ss)'};
M_.endo_names(18) = {'c_H_nat'};
M_.endo_names_tex(18) = {'{\hat {\bar c}_{H,t}}'};
M_.endo_names_long(18) = {'Home natural consumption of Home-made goods (log dev ss)'};
M_.endo_names(19) = {'c_F_nat'};
M_.endo_names_tex(19) = {'{\hat {\bar c}_{F,t}}'};
M_.endo_names_long(19) = {'Home natural consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(20) = {'y_nat_starr'};
M_.endo_names_tex(20) = {'{\hat {\bar y}_t^*}'};
M_.endo_names_long(20) = {'Foreign natural output (log dev ss)'};
M_.endo_names(21) = {'g_nat_starr'};
M_.endo_names_tex(21) = {'{\hat {\bar g}_t^*}'};
M_.endo_names_long(21) = {'Foreign natural government spending (log dev ss)'};
M_.endo_names(22) = {'c_nat_starr'};
M_.endo_names_tex(22) = {'{\hat {\bar c}_t^*}'};
M_.endo_names_long(22) = {'Foreign natural consumption (log dev ss)'};
M_.endo_names(23) = {'c_H_nat_starr'};
M_.endo_names_tex(23) = {'{\hat {\bar c}_{H,t}^*}'};
M_.endo_names_long(23) = {'Foreign natural consumption of Home-made goods (log dev ss)'};
M_.endo_names(24) = {'c_F_nat_starr'};
M_.endo_names_tex(24) = {'{\hat {\bar c}_{F,t}^*}'};
M_.endo_names_long(24) = {'Foreign natural consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(25) = {'s_nat'};
M_.endo_names_tex(25) = {'{\bar s_t}'};
M_.endo_names_long(25) = {'Home natural terms of trade (log dev ss)'};
M_.endo_names(26) = {'y'};
M_.endo_names_tex(26) = {'{\hat y_t}'};
M_.endo_names_long(26) = {'Home output (log dev ss)'};
M_.endo_names(27) = {'pie'};
M_.endo_names_tex(27) = {'{\pi_{H,t}}'};
M_.endo_names_long(27) = {'Home inflation (log dev ss)'};
M_.endo_names(28) = {'g'};
M_.endo_names_tex(28) = {'{\hat g_t}'};
M_.endo_names_long(28) = {'Home government consumption (log dev ss)'};
M_.endo_names(29) = {'n'};
M_.endo_names_tex(29) = {'{\hat n_t}'};
M_.endo_names_long(29) = {'Home labor supply (log dev ss)'};
M_.endo_names(30) = {'c'};
M_.endo_names_tex(30) = {'{\hat c_t}'};
M_.endo_names_long(30) = {'Home consumption (log dev ss)'};
M_.endo_names(31) = {'c_H'};
M_.endo_names_tex(31) = {'{\hat c_{H,t}}'};
M_.endo_names_long(31) = {'Home consumption of Home-made goods (log dev ss)'};
M_.endo_names(32) = {'c_F'};
M_.endo_names_tex(32) = {'{\hat c_{F,t}}'};
M_.endo_names_long(32) = {'Home consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(33) = {'y_starr'};
M_.endo_names_tex(33) = {'{\hat y_t^*}'};
M_.endo_names_long(33) = {'Foreign output (log dev ss)'};
M_.endo_names(34) = {'pie_starr'};
M_.endo_names_tex(34) = {'{\pi_{F,t}^*}'};
M_.endo_names_long(34) = {'Foreign inflation (log dev ss)'};
M_.endo_names(35) = {'g_starr'};
M_.endo_names_tex(35) = {'{\hat g_t^*}'};
M_.endo_names_long(35) = {'Foreign government consumption (log dev ss)'};
M_.endo_names(36) = {'n_starr'};
M_.endo_names_tex(36) = {'{\hat n_t^*}'};
M_.endo_names_long(36) = {'Foreign labor supply (log dev ss)'};
M_.endo_names(37) = {'c_starr'};
M_.endo_names_tex(37) = {'{\hat c_t^*}'};
M_.endo_names_long(37) = {'Foreign consumption (log dev ss)'};
M_.endo_names(38) = {'c_H_starr'};
M_.endo_names_tex(38) = {'{\hat c_{H,t}^*}'};
M_.endo_names_long(38) = {'Foreign consumption of Home-made goods (log dev ss)'};
M_.endo_names(39) = {'c_F_starr'};
M_.endo_names_tex(39) = {'{\hat c_{F,t}^*}'};
M_.endo_names_long(39) = {'Foreign consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(40) = {'ii'};
M_.endo_names_tex(40) = {'{i_t}'};
M_.endo_names_long(40) = {'Currency union nominal interest rate (log dev ss)'};
M_.endo_names(41) = {'s'};
M_.endo_names_tex(41) = {'{s_t}'};
M_.endo_names_long(41) = {'Home terms of trade (log dev ss)'};
M_.endo_names(42) = {'pie_cu'};
M_.endo_names_tex(42) = {'{\pi_{cu,t}}'};
M_.endo_names_long(42) = {'Union inflation (log dev ss)'};
M_.endo_names(43) = {'y_cu'};
M_.endo_names_tex(43) = {'{\hat y_t^{cu}}'};
M_.endo_names_long(43) = {'Union output (log dev ss)'};
M_.endo_names(44) = {'g_cu'};
M_.endo_names_tex(44) = {'{\hat g_t^{cu}}'};
M_.endo_names_long(44) = {'Union government spending (log dev ss)'};
M_.endo_names(45) = {'c_cu'};
M_.endo_names_tex(45) = {'{\hat c_t^{cu}}'};
M_.endo_names_long(45) = {'Union consumption (log dev ss)'};
M_.endo_names(46) = {'MULT_1'};
M_.endo_names_tex(46) = {'MULT\_1'};
M_.endo_names_long(46) = {'MULT_1'};
M_.endo_names(47) = {'MULT_2'};
M_.endo_names_tex(47) = {'MULT\_2'};
M_.endo_names_long(47) = {'MULT_2'};
M_.endo_names(48) = {'MULT_3'};
M_.endo_names_tex(48) = {'MULT\_3'};
M_.endo_names_long(48) = {'MULT_3'};
M_.endo_names(49) = {'MULT_4'};
M_.endo_names_tex(49) = {'MULT\_4'};
M_.endo_names_long(49) = {'MULT_4'};
M_.endo_names(50) = {'MULT_5'};
M_.endo_names_tex(50) = {'MULT\_5'};
M_.endo_names_long(50) = {'MULT_5'};
M_.endo_names(51) = {'MULT_6'};
M_.endo_names_tex(51) = {'MULT\_6'};
M_.endo_names_long(51) = {'MULT_6'};
M_.endo_names(52) = {'MULT_7'};
M_.endo_names_tex(52) = {'MULT\_7'};
M_.endo_names_long(52) = {'MULT_7'};
M_.endo_names(53) = {'MULT_8'};
M_.endo_names_tex(53) = {'MULT\_8'};
M_.endo_names_long(53) = {'MULT_8'};
M_.endo_names(54) = {'MULT_9'};
M_.endo_names_tex(54) = {'MULT\_9'};
M_.endo_names_long(54) = {'MULT_9'};
M_.endo_names(55) = {'MULT_10'};
M_.endo_names_tex(55) = {'MULT\_10'};
M_.endo_names_long(55) = {'MULT_10'};
M_.endo_names(56) = {'MULT_11'};
M_.endo_names_tex(56) = {'MULT\_11'};
M_.endo_names_long(56) = {'MULT_11'};
M_.endo_names(57) = {'MULT_12'};
M_.endo_names_tex(57) = {'MULT\_12'};
M_.endo_names_long(57) = {'MULT_12'};
M_.endo_names(58) = {'MULT_13'};
M_.endo_names_tex(58) = {'MULT\_13'};
M_.endo_names_long(58) = {'MULT_13'};
M_.endo_names(59) = {'MULT_14'};
M_.endo_names_tex(59) = {'MULT\_14'};
M_.endo_names_long(59) = {'MULT_14'};
M_.endo_names(60) = {'MULT_15'};
M_.endo_names_tex(60) = {'MULT\_15'};
M_.endo_names_long(60) = {'MULT_15'};
M_.endo_names(61) = {'MULT_16'};
M_.endo_names_tex(61) = {'MULT\_16'};
M_.endo_names_long(61) = {'MULT_16'};
M_.endo_names(62) = {'MULT_17'};
M_.endo_names_tex(62) = {'MULT\_17'};
M_.endo_names_long(62) = {'MULT_17'};
M_.endo_names(63) = {'MULT_18'};
M_.endo_names_tex(63) = {'MULT\_18'};
M_.endo_names_long(63) = {'MULT_18'};
M_.endo_names(64) = {'MULT_19'};
M_.endo_names_tex(64) = {'MULT\_19'};
M_.endo_names_long(64) = {'MULT_19'};
M_.endo_names(65) = {'MULT_20'};
M_.endo_names_tex(65) = {'MULT\_20'};
M_.endo_names_long(65) = {'MULT_20'};
M_.endo_names(66) = {'MULT_21'};
M_.endo_names_tex(66) = {'MULT\_21'};
M_.endo_names_long(66) = {'MULT_21'};
M_.endo_names(67) = {'MULT_22'};
M_.endo_names_tex(67) = {'MULT\_22'};
M_.endo_names_long(67) = {'MULT_22'};
M_.endo_names(68) = {'MULT_23'};
M_.endo_names_tex(68) = {'MULT\_23'};
M_.endo_names_long(68) = {'MULT_23'};
M_.endo_names(69) = {'MULT_24'};
M_.endo_names_tex(69) = {'MULT\_24'};
M_.endo_names_long(69) = {'MULT_24'};
M_.endo_names(70) = {'MULT_25'};
M_.endo_names_tex(70) = {'MULT\_25'};
M_.endo_names_long(70) = {'MULT_25'};
M_.endo_names(71) = {'MULT_26'};
M_.endo_names_tex(71) = {'MULT\_26'};
M_.endo_names_long(71) = {'MULT_26'};
M_.endo_names(72) = {'MULT_27'};
M_.endo_names_tex(72) = {'MULT\_27'};
M_.endo_names_long(72) = {'MULT_27'};
M_.endo_names(73) = {'MULT_28'};
M_.endo_names_tex(73) = {'MULT\_28'};
M_.endo_names_long(73) = {'MULT_28'};
M_.endo_names(74) = {'MULT_29'};
M_.endo_names_tex(74) = {'MULT\_29'};
M_.endo_names_long(74) = {'MULT_29'};
M_.endo_names(75) = {'MULT_30'};
M_.endo_names_tex(75) = {'MULT\_30'};
M_.endo_names_long(75) = {'MULT_30'};
M_.endo_names(76) = {'MULT_31'};
M_.endo_names_tex(76) = {'MULT\_31'};
M_.endo_names_long(76) = {'MULT_31'};
M_.endo_names(77) = {'MULT_32'};
M_.endo_names_tex(77) = {'MULT\_32'};
M_.endo_names_long(77) = {'MULT_32'};
M_.endo_names(78) = {'MULT_33'};
M_.endo_names_tex(78) = {'MULT\_33'};
M_.endo_names_long(78) = {'MULT_33'};
M_.endo_names(79) = {'MULT_34'};
M_.endo_names_tex(79) = {'MULT\_34'};
M_.endo_names_long(79) = {'MULT_34'};
M_.endo_names(80) = {'MULT_35'};
M_.endo_names_tex(80) = {'MULT\_35'};
M_.endo_names_long(80) = {'MULT_35'};
M_.endo_names(81) = {'MULT_36'};
M_.endo_names_tex(81) = {'MULT\_36'};
M_.endo_names_long(81) = {'MULT_36'};
M_.endo_names(82) = {'MULT_37'};
M_.endo_names_tex(82) = {'MULT\_37'};
M_.endo_names_long(82) = {'MULT_37'};
M_.endo_names(83) = {'MULT_38'};
M_.endo_names_tex(83) = {'MULT\_38'};
M_.endo_names_long(83) = {'MULT_38'};
M_.endo_names(84) = {'MULT_39'};
M_.endo_names_tex(84) = {'MULT\_39'};
M_.endo_names_long(84) = {'MULT_39'};
M_.endo_names(85) = {'MULT_40'};
M_.endo_names_tex(85) = {'MULT\_40'};
M_.endo_names_long(85) = {'MULT_40'};
M_.endo_names(86) = {'MULT_41'};
M_.endo_names_tex(86) = {'MULT\_41'};
M_.endo_names_long(86) = {'MULT_41'};
M_.endo_names(87) = {'MULT_42'};
M_.endo_names_tex(87) = {'MULT\_42'};
M_.endo_names_long(87) = {'MULT_42'};
M_.endo_names(88) = {'MULT_43'};
M_.endo_names_tex(88) = {'MULT\_43'};
M_.endo_names_long(88) = {'MULT_43'};
M_.endo_names(89) = {'MULT_44'};
M_.endo_names_tex(89) = {'MULT\_44'};
M_.endo_names_long(89) = {'MULT_44'};
M_.endo_partitions = struct();
M_.param_names = cell(33,1);
M_.param_names_tex = cell(33,1);
M_.param_names_long = cell(33,1);
M_.param_names(1) = {'BETA'};
M_.param_names_tex(1) = {'BETA'};
M_.param_names_long(1) = {'BETA'};
M_.param_names(2) = {'SIGMA'};
M_.param_names_tex(2) = {'SIGMA'};
M_.param_names_long(2) = {'SIGMA'};
M_.param_names(3) = {'PHI'};
M_.param_names_tex(3) = {'PHI'};
M_.param_names_long(3) = {'PHI'};
M_.param_names(4) = {'GAMMA'};
M_.param_names_tex(4) = {'GAMMA'};
M_.param_names_long(4) = {'GAMMA'};
M_.param_names(5) = {'ETA'};
M_.param_names_tex(5) = {'ETA'};
M_.param_names_long(5) = {'ETA'};
M_.param_names(6) = {'EPSILON'};
M_.param_names_tex(6) = {'EPSILON'};
M_.param_names_long(6) = {'EPSILON'};
M_.param_names(7) = {'h'};
M_.param_names_tex(7) = {'h'};
M_.param_names_long(7) = {'h'};
M_.param_names(8) = {'ALPHA_bar'};
M_.param_names_tex(8) = {'ALPHA\_bar'};
M_.param_names_long(8) = {'ALPHA_bar'};
M_.param_names(9) = {'THETA'};
M_.param_names_tex(9) = {'THETA'};
M_.param_names_long(9) = {'THETA'};
M_.param_names(10) = {'THETA_starr'};
M_.param_names_tex(10) = {'THETA\_starr'};
M_.param_names_long(10) = {'THETA_starr'};
M_.param_names(11) = {'DELTA'};
M_.param_names_tex(11) = {'DELTA'};
M_.param_names_long(11) = {'DELTA'};
M_.param_names(12) = {'CHI_C'};
M_.param_names_tex(12) = {'CHI\_C'};
M_.param_names_long(12) = {'CHI_C'};
M_.param_names(13) = {'CHI_G'};
M_.param_names_tex(13) = {'CHI\_G'};
M_.param_names_long(13) = {'CHI_G'};
M_.param_names(14) = {'ALPHA'};
M_.param_names_tex(14) = {'ALPHA'};
M_.param_names_long(14) = {'ALPHA'};
M_.param_names(15) = {'ALPHA_starr'};
M_.param_names_tex(15) = {'ALPHA\_starr'};
M_.param_names_long(15) = {'ALPHA_starr'};
M_.param_names(16) = {'LAMBDA'};
M_.param_names_tex(16) = {'LAMBDA'};
M_.param_names_long(16) = {'LAMBDA'};
M_.param_names(17) = {'LAMBDA_starr'};
M_.param_names_tex(17) = {'LAMBDA\_starr'};
M_.param_names_long(17) = {'LAMBDA_starr'};
M_.param_names(18) = {'W_ALPHA_bar'};
M_.param_names_tex(18) = {'W\_ALPHA\_bar'};
M_.param_names_long(18) = {'W_ALPHA_bar'};
M_.param_names(19) = {'SIGMA_tilde'};
M_.param_names_tex(19) = {'SIGMA\_tilde'};
M_.param_names_long(19) = {'SIGMA_tilde'};
M_.param_names(20) = {'THETA_ALPHA_bar'};
M_.param_names_tex(20) = {'THETA\_ALPHA\_bar'};
M_.param_names_long(20) = {'THETA_ALPHA_bar'};
M_.param_names(21) = {'SIGMA_tilde_ALPHA_bar'};
M_.param_names_tex(21) = {'SIGMA\_tilde\_ALPHA\_bar'};
M_.param_names_long(21) = {'SIGMA_tilde_ALPHA_bar'};
M_.param_names(22) = {'OMEGA'};
M_.param_names_tex(22) = {'OMEGA'};
M_.param_names_long(22) = {'OMEGA'};
M_.param_names(23) = {'OMEGA_starr'};
M_.param_names_tex(23) = {'OMEGA\_starr'};
M_.param_names_long(23) = {'OMEGA_starr'};
M_.param_names(24) = {'COEF_y_gapH'};
M_.param_names_tex(24) = {'COEF\_y\_gapH'};
M_.param_names_long(24) = {'COEF_y_gapH'};
M_.param_names(25) = {'COEF_y_gapF'};
M_.param_names_tex(25) = {'COEF\_y\_gapF'};
M_.param_names_long(25) = {'COEF_y_gapF'};
M_.param_names(26) = {'COEF_pieH'};
M_.param_names_tex(26) = {'COEF\_pieH'};
M_.param_names_long(26) = {'COEF_pieH'};
M_.param_names(27) = {'COEF_pieF'};
M_.param_names_tex(27) = {'COEF\_pieF'};
M_.param_names_long(27) = {'COEF_pieF'};
M_.param_names(28) = {'COEF_y_gapH_starr'};
M_.param_names_tex(28) = {'COEF\_y\_gapH\_starr'};
M_.param_names_long(28) = {'COEF_y_gapH_starr'};
M_.param_names(29) = {'COEF_y_gapF_starr'};
M_.param_names_tex(29) = {'COEF\_y\_gapF\_starr'};
M_.param_names_long(29) = {'COEF_y_gapF_starr'};
M_.param_names(30) = {'COEF_pieH_starr'};
M_.param_names_tex(30) = {'COEF\_pieH\_starr'};
M_.param_names_long(30) = {'COEF_pieH_starr'};
M_.param_names(31) = {'COEF_pieF_starr'};
M_.param_names_tex(31) = {'COEF\_pieF\_starr'};
M_.param_names_long(31) = {'COEF_pieF_starr'};
M_.param_names(32) = {'RHOA'};
M_.param_names_tex(32) = {'RHOA'};
M_.param_names_long(32) = {'RHOA'};
M_.param_names(33) = {'optimal_policy_discount_factor'};
M_.param_names_tex(33) = {'optimal\_policy\_discount\_factor'};
M_.param_names_long(33) = {'optimal_policy_discount_factor'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 89;
M_.param_nbr = 33;
M_.orig_endo_nbr = 45;
M_.aux_vars(1).endo_index = 46;
M_.aux_vars(1).type = 6;
M_.aux_vars(1).eq_nbr = 1;
M_.aux_vars(2).endo_index = 47;
M_.aux_vars(2).type = 6;
M_.aux_vars(2).eq_nbr = 2;
M_.aux_vars(3).endo_index = 48;
M_.aux_vars(3).type = 6;
M_.aux_vars(3).eq_nbr = 3;
M_.aux_vars(4).endo_index = 49;
M_.aux_vars(4).type = 6;
M_.aux_vars(4).eq_nbr = 4;
M_.aux_vars(5).endo_index = 50;
M_.aux_vars(5).type = 6;
M_.aux_vars(5).eq_nbr = 5;
M_.aux_vars(6).endo_index = 51;
M_.aux_vars(6).type = 6;
M_.aux_vars(6).eq_nbr = 6;
M_.aux_vars(7).endo_index = 52;
M_.aux_vars(7).type = 6;
M_.aux_vars(7).eq_nbr = 7;
M_.aux_vars(8).endo_index = 53;
M_.aux_vars(8).type = 6;
M_.aux_vars(8).eq_nbr = 8;
M_.aux_vars(9).endo_index = 54;
M_.aux_vars(9).type = 6;
M_.aux_vars(9).eq_nbr = 9;
M_.aux_vars(10).endo_index = 55;
M_.aux_vars(10).type = 6;
M_.aux_vars(10).eq_nbr = 10;
M_.aux_vars(11).endo_index = 56;
M_.aux_vars(11).type = 6;
M_.aux_vars(11).eq_nbr = 11;
M_.aux_vars(12).endo_index = 57;
M_.aux_vars(12).type = 6;
M_.aux_vars(12).eq_nbr = 12;
M_.aux_vars(13).endo_index = 58;
M_.aux_vars(13).type = 6;
M_.aux_vars(13).eq_nbr = 13;
M_.aux_vars(14).endo_index = 59;
M_.aux_vars(14).type = 6;
M_.aux_vars(14).eq_nbr = 14;
M_.aux_vars(15).endo_index = 60;
M_.aux_vars(15).type = 6;
M_.aux_vars(15).eq_nbr = 15;
M_.aux_vars(16).endo_index = 61;
M_.aux_vars(16).type = 6;
M_.aux_vars(16).eq_nbr = 16;
M_.aux_vars(17).endo_index = 62;
M_.aux_vars(17).type = 6;
M_.aux_vars(17).eq_nbr = 17;
M_.aux_vars(18).endo_index = 63;
M_.aux_vars(18).type = 6;
M_.aux_vars(18).eq_nbr = 18;
M_.aux_vars(19).endo_index = 64;
M_.aux_vars(19).type = 6;
M_.aux_vars(19).eq_nbr = 19;
M_.aux_vars(20).endo_index = 65;
M_.aux_vars(20).type = 6;
M_.aux_vars(20).eq_nbr = 20;
M_.aux_vars(21).endo_index = 66;
M_.aux_vars(21).type = 6;
M_.aux_vars(21).eq_nbr = 21;
M_.aux_vars(22).endo_index = 67;
M_.aux_vars(22).type = 6;
M_.aux_vars(22).eq_nbr = 22;
M_.aux_vars(23).endo_index = 68;
M_.aux_vars(23).type = 6;
M_.aux_vars(23).eq_nbr = 23;
M_.aux_vars(24).endo_index = 69;
M_.aux_vars(24).type = 6;
M_.aux_vars(24).eq_nbr = 24;
M_.aux_vars(25).endo_index = 70;
M_.aux_vars(25).type = 6;
M_.aux_vars(25).eq_nbr = 25;
M_.aux_vars(26).endo_index = 71;
M_.aux_vars(26).type = 6;
M_.aux_vars(26).eq_nbr = 26;
M_.aux_vars(27).endo_index = 72;
M_.aux_vars(27).type = 6;
M_.aux_vars(27).eq_nbr = 27;
M_.aux_vars(28).endo_index = 73;
M_.aux_vars(28).type = 6;
M_.aux_vars(28).eq_nbr = 28;
M_.aux_vars(29).endo_index = 74;
M_.aux_vars(29).type = 6;
M_.aux_vars(29).eq_nbr = 29;
M_.aux_vars(30).endo_index = 75;
M_.aux_vars(30).type = 6;
M_.aux_vars(30).eq_nbr = 30;
M_.aux_vars(31).endo_index = 76;
M_.aux_vars(31).type = 6;
M_.aux_vars(31).eq_nbr = 31;
M_.aux_vars(32).endo_index = 77;
M_.aux_vars(32).type = 6;
M_.aux_vars(32).eq_nbr = 32;
M_.aux_vars(33).endo_index = 78;
M_.aux_vars(33).type = 6;
M_.aux_vars(33).eq_nbr = 33;
M_.aux_vars(34).endo_index = 79;
M_.aux_vars(34).type = 6;
M_.aux_vars(34).eq_nbr = 34;
M_.aux_vars(35).endo_index = 80;
M_.aux_vars(35).type = 6;
M_.aux_vars(35).eq_nbr = 35;
M_.aux_vars(36).endo_index = 81;
M_.aux_vars(36).type = 6;
M_.aux_vars(36).eq_nbr = 36;
M_.aux_vars(37).endo_index = 82;
M_.aux_vars(37).type = 6;
M_.aux_vars(37).eq_nbr = 37;
M_.aux_vars(38).endo_index = 83;
M_.aux_vars(38).type = 6;
M_.aux_vars(38).eq_nbr = 38;
M_.aux_vars(39).endo_index = 84;
M_.aux_vars(39).type = 6;
M_.aux_vars(39).eq_nbr = 39;
M_.aux_vars(40).endo_index = 85;
M_.aux_vars(40).type = 6;
M_.aux_vars(40).eq_nbr = 40;
M_.aux_vars(41).endo_index = 86;
M_.aux_vars(41).type = 6;
M_.aux_vars(41).eq_nbr = 41;
M_.aux_vars(42).endo_index = 87;
M_.aux_vars(42).type = 6;
M_.aux_vars(42).eq_nbr = 42;
M_.aux_vars(43).endo_index = 88;
M_.aux_vars(43).type = 6;
M_.aux_vars(43).eq_nbr = 43;
M_.aux_vars(44).endo_index = 89;
M_.aux_vars(44).type = 6;
M_.aux_vars(44).eq_nbr = 44;
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(2, 2);
M_.Correlation_matrix = eye(2, 2);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 44;
M_.eq_nbr = 89;
M_.ramsey_eq_nbr = 45;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 8 0;
 0 9 0;
 0 10 0;
 0 11 0;
 0 12 0;
 0 13 0;
 0 14 0;
 0 15 0;
 0 16 0;
 0 17 0;
 0 18 0;
 0 19 0;
 1 20 0;
 2 21 0;
 0 22 0;
 0 23 0;
 0 24 0;
 0 25 0;
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 97;
 0 34 98;
 0 35 99;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 100;
 0 41 101;
 0 42 102;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 3 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 4 64 0;
 5 65 0;
 6 66 0;
 7 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 103;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 0 86 0;
 0 87 0;
 0 88 0;
 0 89 0;
 0 90 0;
 0 91 0;
 0 92 0;
 0 93 0;
 0 94 0;
 0 95 104;
 0 96 105;]';
M_.nstatic = 73;
M_.nfwrd   = 9;
M_.npred   = 7;
M_.nboth   = 0;
M_.nsfwrd   = 9;
M_.nspred   = 7;
M_.ndynamic   = 16;
M_.dynamic_tmp_nbr = [7; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  46 , 'name' , 'Home natural marginal cost condition' ;
  47 , 'name' , 'Foreign natural marginal cost condition' ;
  48 , 'name' , 'Home natural good-market clearing condition' ;
  49 , 'name' , 'Foreign natural good-market clearing condition' ;
  50 , 'name' , 'Natural IRS condition' ;
  51 , 'name' , 'Home natural government spending condition' ;
  52 , 'name' , 'Foreign natural government spending condition' ;
  53 , 'name' , 'Home natural consumption of Home-made goods' ;
  54 , 'name' , 'Home natural consumption of Foreign-made goods' ;
  55 , 'name' , 'Foreign natural consumption of Home-made goods' ;
  56 , 'name' , 'Foreign natural consumption of Foreign-made goods' ;
  57 , 'name' , 'Home Dynamic IS Curve' ;
  58 , 'name' , 'Home New Keynesian Phillips Curve' ;
  59 , 'name' , 'Foreign Dynamic IS Curve' ;
  60 , 'name' , 'Foreign New Keynesian Phillips Curve' ;
  61 , 'name' , 'IRS' ;
  62 , 'name' , 'Home production function' ;
  63 , 'name' , 'Foreign production function' ;
  64 , 'name' , 'Home good-market clearing condition' ;
  65 , 'name' , 'Home consumption of Home-made goods' ;
  66 , 'name' , 'Home consumption of Foreign-made goods' ;
  67 , 'name' , 'Foreign good-market clearing condition' ;
  68 , 'name' , 'Foreign consumption of Home-made goods' ;
  69 , 'name' , 'Foreign consumption of Foreign-made goods' ;
  70 , 'name' , 'Union inflation' ;
  71 , 'name' , 'Union output' ;
  72 , 'name' , 'Union government spending' ;
  73 , 'name' , 'Union consumption' ;
  74 , 'name' , 'Home government spending rule' ;
  75 , 'name' , 'Foreign government spending rule' ;
  76 , 'name' , 'Home output gap definition' ;
  77 , 'name' , 'Home governmpent spending gap definition' ;
  78 , 'name' , 'Home consumption gap definition' ;
  79 , 'name' , 'f_gap' ;
  80 , 'name' , 'Foreign output gap definition' ;
  81 , 'name' , 'Foreign governmpent spending gap definition' ;
  82 , 'name' , 'Foreign consumption gap definition' ;
  83 , 'name' , 'f_gap_starr' ;
  84 , 'name' , 'Home terms of trade gap definition' ;
  85 , 'name' , 'Union output gap definition' ;
  86 , 'name' , 'Union governmpent spending gap definition' ;
  87 , 'name' , 'Union consumption gap definition' ;
  88 , 'name' , 'a' ;
  89 , 'name' , 'a_starr' ;
};
M_.mapping.y_gap.eqidx = [1 74 75 76 79 85 ];
M_.mapping.g_gap.eqidx = [2 74 77 79 86 ];
M_.mapping.c_gap.eqidx = [3 12 78 87 ];
M_.mapping.f_gap.eqidx = [79 ];
M_.mapping.y_gap_starr.eqidx = [5 74 75 80 83 85 ];
M_.mapping.g_gap_starr.eqidx = [6 75 81 83 86 ];
M_.mapping.c_gap_starr.eqidx = [7 12 82 87 ];
M_.mapping.f_gap_starr.eqidx = [83 ];
M_.mapping.s_gap.eqidx = [84 ];
M_.mapping.y_gap_cu.eqidx = [85 ];
M_.mapping.g_gap_cu.eqidx = [86 ];
M_.mapping.c_gap_cu.eqidx = [3 7 12 87 ];
M_.mapping.a.eqidx = [46 58 62 88 ];
M_.mapping.a_starr.eqidx = [47 60 63 89 ];
M_.mapping.eps_a.eqidx = [88 ];
M_.mapping.eps_a_starr.eqidx = [89 ];
M_.mapping.y_nat.eqidx = [46 48 50 76 ];
M_.mapping.g_nat.eqidx = [48 50 51 77 ];
M_.mapping.c_nat.eqidx = [46 48 51 53 54 78 ];
M_.mapping.c_H_nat.eqidx = [53 ];
M_.mapping.c_F_nat.eqidx = [54 ];
M_.mapping.y_nat_starr.eqidx = [47 49 50 80 ];
M_.mapping.g_nat_starr.eqidx = [49 50 52 81 ];
M_.mapping.c_nat_starr.eqidx = [47 49 52 55 56 82 ];
M_.mapping.c_H_nat_starr.eqidx = [55 ];
M_.mapping.c_F_nat_starr.eqidx = [56 ];
M_.mapping.s_nat.eqidx = [46 47 48 49 50 51 52 53 54 55 56 84 ];
M_.mapping.y.eqidx = [57 58 59 60 61 62 64 71 76 ];
M_.mapping.pie.eqidx = [27 57 58 70 74 75 ];
M_.mapping.g.eqidx = [57 58 59 60 61 64 72 77 ];
M_.mapping.n.eqidx = [62 ];
M_.mapping.c.eqidx = [64 65 66 73 78 ];
M_.mapping.c_H.eqidx = [65 ];
M_.mapping.c_F.eqidx = [66 ];
M_.mapping.y_starr.eqidx = [57 58 59 60 61 63 67 71 80 ];
M_.mapping.pie_starr.eqidx = [34 59 60 74 75 ];
M_.mapping.g_starr.eqidx = [57 58 59 60 61 67 72 81 ];
M_.mapping.n_starr.eqidx = [63 ];
M_.mapping.c_starr.eqidx = [67 68 69 73 82 ];
M_.mapping.c_H_starr.eqidx = [68 ];
M_.mapping.c_F_starr.eqidx = [69 ];
M_.mapping.ii.eqidx = [57 59 ];
M_.mapping.s.eqidx = [61 64 65 66 67 68 69 70 84 ];
M_.mapping.pie_cu.eqidx = [70 ];
M_.mapping.y_cu.eqidx = [71 ];
M_.mapping.g_cu.eqidx = [72 ];
M_.mapping.c_cu.eqidx = [73 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [13 14 41 57 58 59 60 ];
M_.exo_names_orig_ord = [1:2];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(89, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = NaN(33, 1);
M_.endo_trends = struct('deflator', cell(89, 1), 'log_deflator', cell(89, 1), 'growth_factor', cell(89, 1), 'log_growth_factor', cell(89, 1));
M_.NNZDerivatives = [349; 0; -1; ];
M_.static_tmp_nbr = [7; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 0;
M_.Sigma_e(2, 2) = 1;
M_.params(1) = 0.98;
BETA = M_.params(1);
M_.params(2) = 3;
SIGMA = M_.params(2);
M_.params(3) = 1;
PHI = M_.params(3);
M_.params(4) = 1;
GAMMA = M_.params(4);
M_.params(5) = 4.5;
ETA = M_.params(5);
M_.params(6) = 6;
EPSILON = M_.params(6);
M_.params(7) = 0.5;
h = M_.params(7);
M_.params(8) = 0.2;
ALPHA_bar = M_.params(8);
M_.params(9) = 0.75;
THETA = M_.params(9);
M_.params(10) = 0.75;
THETA_starr = M_.params(10);
M_.params(11) = 0.2;
DELTA = M_.params(11);
M_.params(12) = (1-M_.params(11))^M_.params(2);
CHI_C = M_.params(12);
M_.params(13) = M_.params(11)^M_.params(4);
CHI_G = M_.params(13);
M_.params(14) = M_.params(8)*(1-M_.params(7));
ALPHA = M_.params(14);
M_.params(15) = M_.params(8)*M_.params(7);
ALPHA_starr = M_.params(15);
M_.params(16) = (1-M_.params(9))*(1-M_.params(9)*M_.params(1))/M_.params(9);
LAMBDA = M_.params(16);
M_.params(17) = (1-M_.params(10))*(1-M_.params(1)*M_.params(10))/M_.params(10);
LAMBDA_starr = M_.params(17);
M_.params(18) = 1+(2-M_.params(8))*(M_.params(2)*M_.params(5)-1);
W_ALPHA_bar = M_.params(18);
M_.params(19) = M_.params(2)/(1-M_.params(11));
SIGMA_tilde = M_.params(19);
M_.params(20) = M_.params(18)-1;
THETA_ALPHA_bar = M_.params(20);
M_.params(21) = M_.params(19)/(1+M_.params(8)*M_.params(20));
SIGMA_tilde_ALPHA_bar = M_.params(21);
M_.params(22) = 1+M_.params(8)*M_.params(7)*M_.params(20);
OMEGA = M_.params(22);
M_.params(23) = 1+M_.params(8)*(1-M_.params(7))*M_.params(20);
OMEGA_starr = M_.params(23);
M_.params(32) = 0.85;
RHOA = M_.params(32);
M_.NNZDerivatives_objective = [9;13;0;];
M_.objective_tmp_nbr = [2; 0; 0; 0; ];
M_.params(33) = M_.params(1);
optimal_policy_discount_factor = M_.params(33);
options_.ramsey_policy = true;
options_.instruments = {'ii'};
M_.params(24) = 1;
COEF_y_gapH = M_.params(24);
M_.params(25) = 1;
COEF_y_gapF = M_.params(25);
M_.params(26) = 1;
COEF_pieH = M_.params(26);
M_.params(27) = 1;
COEF_pieF = M_.params(27);
M_.params(28) = 1;
COEF_y_gapH_starr = M_.params(28);
M_.params(29) = 1;
COEF_y_gapF_starr = M_.params(29);
M_.params(30) = 1;
COEF_pieH_starr = M_.params(30);
M_.params(31) = 1;
COEF_pieF_starr = M_.params(31);
%
% OPTIM_WEIGHTS
%
M_.osr.variable_weights = sparse(M_.endo_nbr,M_.endo_nbr);
M_.osr.variable_indices = [];

M_.osr.variable_weights(3,3) = M_.params(2)*(1-M_.params(11))*M_.params(7);
M_.osr.variable_indices = [M_.osr.variable_indices; 3];
M_.osr.variable_weights(7,7) = M_.params(2)*(1-M_.params(11))*(1-M_.params(7));
M_.osr.variable_indices = [M_.osr.variable_indices; 7];
M_.osr.variable_weights(2,2) = M_.params(4)*M_.params(11)*M_.params(7);
M_.osr.variable_indices = [M_.osr.variable_indices; 2];
M_.osr.variable_weights(6,6) = M_.params(4)*M_.params(11)*(1-M_.params(7));
M_.osr.variable_indices = [M_.osr.variable_indices; 6];
M_.osr.variable_weights(27,27) = M_.params(7)*M_.params(6)/M_.params(16);
M_.osr.variable_indices = [M_.osr.variable_indices; 27];
M_.osr.variable_weights(34,34) = (1-M_.params(7))*M_.params(6)/M_.params(16);
M_.osr.variable_indices = [M_.osr.variable_indices; 34];
M_.osr.variable_weights(9,9) = 1;
M_.osr.variable_indices = [M_.osr.variable_indices; 9];
M_.osr.variable_weights(1,1) = M_.params(7)*M_.params(3);
M_.osr.variable_indices = [M_.osr.variable_indices; 1];
M_.osr.variable_weights(5,5) = (1-M_.params(7))*M_.params(3);
M_.osr.variable_indices = [M_.osr.variable_indices; 5];
M_.osr.param_names = {'COEF_y_gapH';'COEF_y_gapF';'COEF_pieH';'COEF_pieF';'COEF_y_gapH_starr';'COEF_y_gapF_starr';'COEF_pieH_starr';'COEF_pieF_starr'};
M_.osr.param_names = cellstr(M_.osr.param_names);
M_.osr.param_indices = zeros(length(M_.osr.param_names), 1);
M_.osr.param_indices(1) = 24;
M_.osr.param_indices(2) = 25;
M_.osr.param_indices(3) = 26;
M_.osr.param_indices(4) = 27;
M_.osr.param_indices(5) = 28;
M_.osr.param_indices(6) = 29;
M_.osr.param_indices(7) = 30;
M_.osr.param_indices(8) = 31;
M_.osr.param_bounds = [-inf(length(M_.osr.param_names), 1), inf(length(M_.osr.param_names), 1)];
M_.osr.param_bounds(strcmp(M_.osr.param_names, 'COEF_y_gapH'), :) = [(-10), 10];
M_.osr.param_bounds(strcmp(M_.osr.param_names, 'COEF_y_gapF'), :) = [(-10), 10];
M_.osr.param_bounds(strcmp(M_.osr.param_names, 'COEF_pieH'), :) = [(-10), 10];
M_.osr.param_bounds(strcmp(M_.osr.param_names, 'COEF_pieF'), :) = [(-10), 10];
M_.osr.param_bounds(strcmp(M_.osr.param_names, 'COEF_y_gapH_starr'), :) = [(-10), 10];
M_.osr.param_bounds(strcmp(M_.osr.param_names, 'COEF_y_gapF_starr'), :) = [(-10), 10];
M_.osr.param_bounds(strcmp(M_.osr.param_names, 'COEF_pieH_starr'), :) = [(-10), 10];
M_.osr.param_bounds(strcmp(M_.osr.param_names, 'COEF_pieF_starr'), :) = [(-10), 10];
options_.TeX = true;
options_.irf = 30;
options_.osr.opt_algo = 9;
var_list_ = {'y_gap';'y_nat';'g_gap';'g_nat';'c_gap';'c_nat';'pie';'c_F';'c_H';'y_gap_starr';'y_nat_starr';'g_gap_starr';'g_nat_starr';'c_gap_starr';'c_nat_starr';'pie_starr';'c_F_starr';'c_H_starr';'y_gap_cu';'g_gap_cu';'pie_cu';'s_gap';'s_nat';'ii'};
oo_.osr = osr(var_list_,M_.osr.param_names,M_.osr.variable_indices,M_.osr.variable_weights);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_2_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_2_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_2_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_2_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_2_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_2_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_2_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
