%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'MODEL_MAIN_11';
M_.dynare_version = '5.0';
oo_.dynare_version = '5.0';
options_.dynare_version = '5.0';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(2,1);
M_.exo_names_tex = cell(2,1);
M_.exo_names_long = cell(2,1);
M_.exo_names(1) = {'eps_a'};
M_.exo_names_tex(1) = {'{\epsilon_a}'};
M_.exo_names_long(1) = {'Home technology shock'};
M_.exo_names(2) = {'eps_a_starr'};
M_.exo_names_tex(2) = {'{\epsilon_a^*}'};
M_.exo_names_long(2) = {'Foreign technology shock'};
M_.endo_names = cell(94,1);
M_.endo_names_tex = cell(94,1);
M_.endo_names_long = cell(94,1);
M_.endo_names(1) = {'a'};
M_.endo_names_tex(1) = {'{a}'};
M_.endo_names_long(1) = {'Home productivity (log dev ss)'};
M_.endo_names(2) = {'a_starr'};
M_.endo_names_tex(2) = {'{a^*}'};
M_.endo_names_long(2) = {'Foreign productivity (log dev ss)'};
M_.endo_names(3) = {'a_cu'};
M_.endo_names_tex(3) = {'a\_cu'};
M_.endo_names_long(3) = {'a_cu'};
M_.endo_names(4) = {'y_nat'};
M_.endo_names_tex(4) = {'{\hat {\bar y}}'};
M_.endo_names_long(4) = {'Home natural output (log dev ss)'};
M_.endo_names(5) = {'g_nat'};
M_.endo_names_tex(5) = {'{\hat {\bar g}}'};
M_.endo_names_long(5) = {'Home natural government spending (log dev ss)'};
M_.endo_names(6) = {'c_nat'};
M_.endo_names_tex(6) = {'{\hat {\bar c}}'};
M_.endo_names_long(6) = {'Home natural consumption (log dev ss)'};
M_.endo_names(7) = {'c_H_nat'};
M_.endo_names_tex(7) = {'{\hat {\bar c}^H}'};
M_.endo_names_long(7) = {'Home natural consumption of Home-made goods (log dev ss)'};
M_.endo_names(8) = {'c_F_nat'};
M_.endo_names_tex(8) = {'{\hat {\bar c}^F}'};
M_.endo_names_long(8) = {'Home natural consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(9) = {'n_nat'};
M_.endo_names_tex(9) = {'{\hat {\bar n}}'};
M_.endo_names_long(9) = {'Home natural labor (log dev ss)'};
M_.endo_names(10) = {'f_nat'};
M_.endo_names_tex(10) = {'{\hat {\bar f}}'};
M_.endo_names_long(10) = {'Home natural fiscal stance (log dev ss)'};
M_.endo_names(11) = {'s_nat'};
M_.endo_names_tex(11) = {'{\bar s}'};
M_.endo_names_long(11) = {'Home natural terms of trade (log dev ss)'};
M_.endo_names(12) = {'r_nat'};
M_.endo_names_tex(12) = {'{\bar r}'};
M_.endo_names_long(12) = {'Home natural rate (log dev ss)'};
M_.endo_names(13) = {'nx_nat'};
M_.endo_names_tex(13) = {'{\bar{nx}}'};
M_.endo_names_long(13) = {'nx_nat'};
M_.endo_names(14) = {'y_nat_starr'};
M_.endo_names_tex(14) = {'{\hat {\bar y}^*}'};
M_.endo_names_long(14) = {'Foreign natural output (log dev ss)'};
M_.endo_names(15) = {'g_nat_starr'};
M_.endo_names_tex(15) = {'{\hat {\bar g}^*}'};
M_.endo_names_long(15) = {'Foreign natural government spending (log dev ss)'};
M_.endo_names(16) = {'c_nat_starr'};
M_.endo_names_tex(16) = {'{\hat {\bar c}^*}'};
M_.endo_names_long(16) = {'Foreign natural consumption (log dev ss)'};
M_.endo_names(17) = {'c_H_nat_starr'};
M_.endo_names_tex(17) = {'{\hat {\bar c}^{H*}}'};
M_.endo_names_long(17) = {'Foreign natural consumption of Home-made goods (log dev ss)'};
M_.endo_names(18) = {'c_F_nat_starr'};
M_.endo_names_tex(18) = {'{\hat {\bar c}^{F*}}'};
M_.endo_names_long(18) = {'Foreign natural consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(19) = {'n_nat_starr'};
M_.endo_names_tex(19) = {'{\hat {\bar n}^*}'};
M_.endo_names_long(19) = {'Foreign natural labor (log dev ss)'};
M_.endo_names(20) = {'f_nat_starr'};
M_.endo_names_tex(20) = {'{\hat {\bar f}^*}'};
M_.endo_names_long(20) = {'Foreign natural fiscal stance (log dev ss)'};
M_.endo_names(21) = {'s_nat_starr'};
M_.endo_names_tex(21) = {'{\bar s^*}'};
M_.endo_names_long(21) = {'Foreign natural terms of trade (log dev ss)'};
M_.endo_names(22) = {'r_nat_starr'};
M_.endo_names_tex(22) = {'{\bar r^*}'};
M_.endo_names_long(22) = {'Foreign natural rate (log dev ss)'};
M_.endo_names(23) = {'nx_nat_starr'};
M_.endo_names_tex(23) = {'{\bar{nx}^*}'};
M_.endo_names_long(23) = {'nx_nat_starr'};
M_.endo_names(24) = {'y_nat_cu'};
M_.endo_names_tex(24) = {'{\hat {\bar y}^{cu}}'};
M_.endo_names_long(24) = {'Union natural output (log dev ss)'};
M_.endo_names(25) = {'g_nat_cu'};
M_.endo_names_tex(25) = {'{\hat {\bar g}^{cu}}'};
M_.endo_names_long(25) = {'Union natural government consumption (log dev ss)'};
M_.endo_names(26) = {'c_nat_cu'};
M_.endo_names_tex(26) = {'{\hat {\bar c}^{cu}}'};
M_.endo_names_long(26) = {'Union natural consumption (log dev ss)'};
M_.endo_names(27) = {'c_H_nat_cu'};
M_.endo_names_tex(27) = {'{\hat {\bar c}^{H,cu}}'};
M_.endo_names_long(27) = {'c_H_nat_cu'};
M_.endo_names(28) = {'c_F_nat_cu'};
M_.endo_names_tex(28) = {'{\hat {\bar c}^{F,cu}}'};
M_.endo_names_long(28) = {'c_F_nat_cu'};
M_.endo_names(29) = {'r_nat_cu'};
M_.endo_names_tex(29) = {'{\hat {\bar r}^{cu}}'};
M_.endo_names_long(29) = {'Union natural rate (log dev ss)'};
M_.endo_names(30) = {'f_nat_cu'};
M_.endo_names_tex(30) = {'{\hat {\bar f}^{H,cu}}'};
M_.endo_names_long(30) = {'f_nat_cu'};
M_.endo_names(31) = {'n_nat_cu'};
M_.endo_names_tex(31) = {'{\hat {\bar n}^{H,cu}}'};
M_.endo_names_long(31) = {'n_nat_cu'};
M_.endo_names(32) = {'nx_nat_cu'};
M_.endo_names_tex(32) = {'{\hat {\bar{nx}}^{H,cu}}'};
M_.endo_names_long(32) = {'nx_nat_cu'};
M_.endo_names(33) = {'y'};
M_.endo_names_tex(33) = {'{\hat y}'};
M_.endo_names_long(33) = {'Home output (log dev ss)'};
M_.endo_names(34) = {'pie'};
M_.endo_names_tex(34) = {'{\pi^H}'};
M_.endo_names_long(34) = {'Home inflation (log dev ss)'};
M_.endo_names(35) = {'g'};
M_.endo_names_tex(35) = {'{\hat g}'};
M_.endo_names_long(35) = {'Home government consumption (log dev ss)'};
M_.endo_names(36) = {'n'};
M_.endo_names_tex(36) = {'{\hat n}'};
M_.endo_names_long(36) = {'Home labor (log dev ss)'};
M_.endo_names(37) = {'c'};
M_.endo_names_tex(37) = {'{\hat c}'};
M_.endo_names_long(37) = {'Home consumption (log dev ss)'};
M_.endo_names(38) = {'c_H'};
M_.endo_names_tex(38) = {'{\hat c^H}'};
M_.endo_names_long(38) = {'Home consumption of Home-made goods (log dev ss)'};
M_.endo_names(39) = {'c_F'};
M_.endo_names_tex(39) = {'{\hat c^F}'};
M_.endo_names_long(39) = {'Home consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(40) = {'f'};
M_.endo_names_tex(40) = {'{\hat f}'};
M_.endo_names_long(40) = {'Home fiscal stance (log dev ss)'};
M_.endo_names(41) = {'s'};
M_.endo_names_tex(41) = {'{s}'};
M_.endo_names_long(41) = {'Home terms of trade (log dev ss)'};
M_.endo_names(42) = {'ii'};
M_.endo_names_tex(42) = {'{i}'};
M_.endo_names_long(42) = {'Home nominal interest rate (log dev ss)'};
M_.endo_names(43) = {'nx'};
M_.endo_names_tex(43) = {'{nx}'};
M_.endo_names_long(43) = {'nx'};
M_.endo_names(44) = {'y_starr'};
M_.endo_names_tex(44) = {'{\hat y^*}'};
M_.endo_names_long(44) = {'Foreign output (log dev ss)'};
M_.endo_names(45) = {'pie_starr'};
M_.endo_names_tex(45) = {'{\pi^{F*}}'};
M_.endo_names_long(45) = {'Foreign inflation (log dev ss)'};
M_.endo_names(46) = {'g_starr'};
M_.endo_names_tex(46) = {'{\hat g^*}'};
M_.endo_names_long(46) = {'Foreign government consumption (log dev ss)'};
M_.endo_names(47) = {'n_starr'};
M_.endo_names_tex(47) = {'{\hat n^*}'};
M_.endo_names_long(47) = {'Foreign labor (log dev ss)'};
M_.endo_names(48) = {'c_starr'};
M_.endo_names_tex(48) = {'{\hat c^*}'};
M_.endo_names_long(48) = {'Foreign consumption (log dev ss)'};
M_.endo_names(49) = {'c_H_starr'};
M_.endo_names_tex(49) = {'{\hat c^{H*}}'};
M_.endo_names_long(49) = {'Foreign consumption of Home-made goods (log dev ss)'};
M_.endo_names(50) = {'c_F_starr'};
M_.endo_names_tex(50) = {'{\hat c^{F*}}'};
M_.endo_names_long(50) = {'Foreign consumption of Foreign-made goods (log dev ss)'};
M_.endo_names(51) = {'f_starr'};
M_.endo_names_tex(51) = {'{\hat f^*}'};
M_.endo_names_long(51) = {'Foreign fiscal stance (log dev ss)'};
M_.endo_names(52) = {'ii_starr'};
M_.endo_names_tex(52) = {'{i^*}'};
M_.endo_names_long(52) = {'Foreign nominal interest rate (log dev ss)'};
M_.endo_names(53) = {'s_starr'};
M_.endo_names_tex(53) = {'{s^*}'};
M_.endo_names_long(53) = {'Foreign terms of trade (log dev ss)'};
M_.endo_names(54) = {'nx_starr'};
M_.endo_names_tex(54) = {'{nx^*}'};
M_.endo_names_long(54) = {'nx_starr'};
M_.endo_names(55) = {'y_cu'};
M_.endo_names_tex(55) = {'{\hat y^{cu}}'};
M_.endo_names_long(55) = {'Union output (log dev ss)'};
M_.endo_names(56) = {'g_cu'};
M_.endo_names_tex(56) = {'{\hat g^{cu}}'};
M_.endo_names_long(56) = {'Union government spending (log dev ss)'};
M_.endo_names(57) = {'c_cu'};
M_.endo_names_tex(57) = {'{\hat c^{cu}}'};
M_.endo_names_long(57) = {'Union consumption (log dev ss)'};
M_.endo_names(58) = {'c_H_cu'};
M_.endo_names_tex(58) = {'{\hat c^{H,cu}}'};
M_.endo_names_long(58) = {'c_H_cu'};
M_.endo_names(59) = {'c_F_cu'};
M_.endo_names_tex(59) = {'{\hat c^{F,cu}}'};
M_.endo_names_long(59) = {'c_F_cu'};
M_.endo_names(60) = {'ii_cu'};
M_.endo_names_tex(60) = {'{i^{cu}}'};
M_.endo_names_long(60) = {'Union nominal interest rate (log dev ss)'};
M_.endo_names(61) = {'pie_cu'};
M_.endo_names_tex(61) = {'{\pi^{cu}}'};
M_.endo_names_long(61) = {'Union inflation (log dev ss)'};
M_.endo_names(62) = {'f_cu'};
M_.endo_names_tex(62) = {'{\hat f^{cu}}'};
M_.endo_names_long(62) = {'f_cu'};
M_.endo_names(63) = {'n_cu'};
M_.endo_names_tex(63) = {'{\hat n^{cu}}'};
M_.endo_names_long(63) = {'n_cu'};
M_.endo_names(64) = {'nx_cu'};
M_.endo_names_tex(64) = {'{\hat{nx}^{cu}}'};
M_.endo_names_long(64) = {'nx_cu'};
M_.endo_names(65) = {'y_gap'};
M_.endo_names_tex(65) = {'{\tilde y}'};
M_.endo_names_long(65) = {'Home output gap (log dev ss)'};
M_.endo_names(66) = {'g_gap'};
M_.endo_names_tex(66) = {'{\tilde g}'};
M_.endo_names_long(66) = {'Home government spending gap (log dev ss)'};
M_.endo_names(67) = {'c_gap'};
M_.endo_names_tex(67) = {'{\tilde c}'};
M_.endo_names_long(67) = {'Home consumption gap (log dev ss)'};
M_.endo_names(68) = {'c_H_gap'};
M_.endo_names_tex(68) = {'{\tilde c^H}'};
M_.endo_names_long(68) = {'Home consumption of Home-made goods gap (log dev ss)'};
M_.endo_names(69) = {'c_F_gap'};
M_.endo_names_tex(69) = {'{\tilde c^F}'};
M_.endo_names_long(69) = {'Home consumption of Foreign-made goods gap (log dev ss)'};
M_.endo_names(70) = {'f_gap'};
M_.endo_names_tex(70) = {'{\tilde f}'};
M_.endo_names_long(70) = {'Home fiscal stance gap (log dev ss)'};
M_.endo_names(71) = {'n_gap'};
M_.endo_names_tex(71) = {'{\tilde n}'};
M_.endo_names_long(71) = {'Home labor gap (log dev ss)'};
M_.endo_names(72) = {'s_gap'};
M_.endo_names_tex(72) = {'{\tilde s}'};
M_.endo_names_long(72) = {'Home terms of trade gap (log dev ss)'};
M_.endo_names(73) = {'ii_gap'};
M_.endo_names_tex(73) = {'{\tilde i}'};
M_.endo_names_long(73) = {'ii_gap'};
M_.endo_names(74) = {'nx_gap'};
M_.endo_names_tex(74) = {'{\tilde{nx}}'};
M_.endo_names_long(74) = {'nx_gap'};
M_.endo_names(75) = {'y_gap_starr'};
M_.endo_names_tex(75) = {'{\tilde y^*}'};
M_.endo_names_long(75) = {'Foreign output gap (log dev ss)'};
M_.endo_names(76) = {'g_gap_starr'};
M_.endo_names_tex(76) = {'{\tilde g^*}'};
M_.endo_names_long(76) = {'Foreign government spending gap (log dev ss)'};
M_.endo_names(77) = {'c_gap_starr'};
M_.endo_names_tex(77) = {'{\tilde c^*}'};
M_.endo_names_long(77) = {'Foreign consumption gap (log dev ss)'};
M_.endo_names(78) = {'c_H_gap_starr'};
M_.endo_names_tex(78) = {'{\tilde c^{H*}}'};
M_.endo_names_long(78) = {'Foreign consumption of Home-made goods gap (log dev ss)'};
M_.endo_names(79) = {'c_F_gap_starr'};
M_.endo_names_tex(79) = {'{\tilde c^{F*}}'};
M_.endo_names_long(79) = {'Foreign consumption of Foreign-made goods gap (log dev ss)'};
M_.endo_names(80) = {'f_gap_starr'};
M_.endo_names_tex(80) = {'{\tilde f^*}'};
M_.endo_names_long(80) = {'Foreign fiscal stance gap (log dev ss)'};
M_.endo_names(81) = {'n_gap_starr'};
M_.endo_names_tex(81) = {'{\tilde n^*}'};
M_.endo_names_long(81) = {'Foreign labor gap (log dev ss)'};
M_.endo_names(82) = {'s_gap_starr'};
M_.endo_names_tex(82) = {'{\tilde s^*}'};
M_.endo_names_long(82) = {'Foreign terms of trade gap (log dev ss)'};
M_.endo_names(83) = {'ii_gap_starr'};
M_.endo_names_tex(83) = {'{\tilde i^*}'};
M_.endo_names_long(83) = {'ii_gap_starr'};
M_.endo_names(84) = {'nx_gap_starr'};
M_.endo_names_tex(84) = {'{\tilde{nx}^*}'};
M_.endo_names_long(84) = {'nx_gap_starr'};
M_.endo_names(85) = {'y_gap_cu'};
M_.endo_names_tex(85) = {'{\tilde y^{cu}}'};
M_.endo_names_long(85) = {'Union output gap (log dev ss)'};
M_.endo_names(86) = {'g_gap_cu'};
M_.endo_names_tex(86) = {'{\tilde g^{cu}}'};
M_.endo_names_long(86) = {'Union government spending gap (log dev ss)'};
M_.endo_names(87) = {'c_gap_cu'};
M_.endo_names_tex(87) = {'{\tilde c^{cu}}'};
M_.endo_names_long(87) = {'Union government spending gap (log dev ss)'};
M_.endo_names(88) = {'c_H_gap_cu'};
M_.endo_names_tex(88) = {'{\tilde c^{H,cu}}'};
M_.endo_names_long(88) = {'c_H_gap_cu'};
M_.endo_names(89) = {'c_F_gap_cu'};
M_.endo_names_tex(89) = {'{\tilde c^{F,cu}}'};
M_.endo_names_long(89) = {'c_F_gap_cu'};
M_.endo_names(90) = {'ii_gap_cu'};
M_.endo_names_tex(90) = {'{\tilde i^{cu}}'};
M_.endo_names_long(90) = {'ii_gap_cu'};
M_.endo_names(91) = {'n_gap_cu'};
M_.endo_names_tex(91) = {'{\tilde n^{cu}}'};
M_.endo_names_long(91) = {'n_gap_cu'};
M_.endo_names(92) = {'f_gap_cu'};
M_.endo_names_tex(92) = {'{\tilde f^{cu}}'};
M_.endo_names_long(92) = {'f_gap_cu'};
M_.endo_names(93) = {'nx_gap_cu'};
M_.endo_names_tex(93) = {'{\tilde{nx}^{cu}}'};
M_.endo_names_long(93) = {'nx_gap_cu'};
M_.endo_names(94) = {'g_gap_r'};
M_.endo_names_tex(94) = {'{\tilde g^{r}}'};
M_.endo_names_long(94) = {'Relative output gap (log dev ss)'};
M_.endo_partitions = struct();
M_.param_names = cell(25,1);
M_.param_names_tex = cell(25,1);
M_.param_names_long = cell(25,1);
M_.param_names(1) = {'BETA'};
M_.param_names_tex(1) = {'{\beta}'};
M_.param_names_long(1) = {'BETA'};
M_.param_names(2) = {'SIGMA'};
M_.param_names_tex(2) = {'{\sigma}'};
M_.param_names_long(2) = {'SIGMA'};
M_.param_names(3) = {'PHI'};
M_.param_names_tex(3) = {'{\varphi}'};
M_.param_names_long(3) = {'PHI'};
M_.param_names(4) = {'GAMMA'};
M_.param_names_tex(4) = {'{\gamma}'};
M_.param_names_long(4) = {'GAMMA'};
M_.param_names(5) = {'ETA'};
M_.param_names_tex(5) = {'{\eta}'};
M_.param_names_long(5) = {'ETA'};
M_.param_names(6) = {'EPSILON'};
M_.param_names_tex(6) = {'{\varepsilon}'};
M_.param_names_long(6) = {'EPSILON'};
M_.param_names(7) = {'h'};
M_.param_names_tex(7) = {'{h}'};
M_.param_names_long(7) = {'h'};
M_.param_names(8) = {'ALPHA_bar'};
M_.param_names_tex(8) = {'{\bar{\alpha}}'};
M_.param_names_long(8) = {'ALPHA_bar'};
M_.param_names(9) = {'THETA'};
M_.param_names_tex(9) = {'\theta'};
M_.param_names_long(9) = {'THETA'};
M_.param_names(10) = {'THETA_starr'};
M_.param_names_tex(10) = {'\theta^*'};
M_.param_names_long(10) = {'THETA_starr'};
M_.param_names(11) = {'DELTA'};
M_.param_names_tex(11) = {'{\delta}'};
M_.param_names_long(11) = {'DELTA'};
M_.param_names(12) = {'CHI_C'};
M_.param_names_tex(12) = {'{\chi_C}'};
M_.param_names_long(12) = {'CHI_C'};
M_.param_names(13) = {'CHI_G'};
M_.param_names_tex(13) = {'{\chi_G}'};
M_.param_names_long(13) = {'CHI_G'};
M_.param_names(14) = {'ALPHA'};
M_.param_names_tex(14) = {'{\alpha}'};
M_.param_names_long(14) = {'ALPHA'};
M_.param_names(15) = {'ALPHA_starr'};
M_.param_names_tex(15) = {'{\alpha^*}'};
M_.param_names_long(15) = {'ALPHA_starr'};
M_.param_names(16) = {'LAMBDA'};
M_.param_names_tex(16) = {'{\lambda}'};
M_.param_names_long(16) = {'LAMBDA'};
M_.param_names(17) = {'LAMBDA_starr'};
M_.param_names_tex(17) = {'{\lambda^*}'};
M_.param_names_long(17) = {'LAMBDA_starr'};
M_.param_names(18) = {'W_ALPHA_bar'};
M_.param_names_tex(18) = {'{w_{\bar{\alpha}}}'};
M_.param_names_long(18) = {'W_ALPHA_bar'};
M_.param_names(19) = {'SIGMA_tilde'};
M_.param_names_tex(19) = {'{\tilde{\sigma}}'};
M_.param_names_long(19) = {'SIGMA_tilde'};
M_.param_names(20) = {'THETA_ALPHA_bar'};
M_.param_names_tex(20) = {'{\Theta{\bar{\alpha}}}'};
M_.param_names_long(20) = {'THETA_ALPHA_bar'};
M_.param_names(21) = {'SIGMA_tilde_ALPHA_bar'};
M_.param_names_tex(21) = {'{\tilde\sigma_{\bar{\alpha}}}'};
M_.param_names_long(21) = {'SIGMA_tilde_ALPHA_bar'};
M_.param_names(22) = {'OMEGA'};
M_.param_names_tex(22) = {'{\Omega_{\bar \alpha,h}}'};
M_.param_names_long(22) = {'OMEGA'};
M_.param_names(23) = {'OMEGA_starr'};
M_.param_names_tex(23) = {'{\Omega_{\bar \alpha,1-h}}'};
M_.param_names_long(23) = {'OMEGA_starr'};
M_.param_names(24) = {'RHOG'};
M_.param_names_tex(24) = {'RHOG'};
M_.param_names_long(24) = {'RHOG'};
M_.param_names(25) = {'RHOA'};
M_.param_names_tex(25) = {'RHOA'};
M_.param_names_long(25) = {'RHOA'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 94;
M_.param_nbr = 25;
M_.orig_endo_nbr = 94;
M_.aux_vars = [];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(2, 2);
M_.Correlation_matrix = eye(2, 2);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 94;
M_.eq_nbr = 94;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 1 5 99;
 2 6 100;
 0 7 0;
 0 8 101;
 0 9 0;
 0 10 0;
 0 11 0;
 0 12 0;
 0 13 0;
 0 14 0;
 0 15 0;
 0 16 0;
 0 17 0;
 0 18 102;
 0 19 0;
 0 20 0;
 0 21 0;
 0 22 0;
 0 23 0;
 0 24 0;
 0 25 0;
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 3 33 0;
 0 34 0;
 0 35 0;
 0 36 0;
 0 37 103;
 0 38 104;
 0 39 0;
 0 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 105;
 0 49 106;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 4 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 0 86 0;
 0 87 0;
 0 88 0;
 0 89 0;
 0 90 0;
 0 91 0;
 0 92 0;
 0 93 0;
 0 94 0;
 0 95 0;
 0 96 0;
 0 97 0;
 0 98 0;]';
M_.nstatic = 84;
M_.nfwrd   = 6;
M_.npred   = 2;
M_.nboth   = 2;
M_.nsfwrd   = 8;
M_.nspred   = 4;
M_.ndynamic   = 10;
M_.dynamic_tmp_nbr = [2; 1; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Home natural marginal cost condition' ;
  2 , 'name' , 'Foreign natural marginal cost condition' ;
  3 , 'name' , 'Home natural good-market clearing condition' ;
  4 , 'name' , 'Foreign natural good-market clearing condition' ;
  5 , 'name' , 'Natural IRS condition' ;
  6 , 'name' , 'Home natural government spending condition' ;
  7 , 'name' , 'Foreign natural government spending condition' ;
  8 , 'name' , 'Natural LOP' ;
  9 , 'name' , 'Home natural consumption of Home-made goods' ;
  10 , 'name' , 'Home natural consumption of Foreign-made goods' ;
  11 , 'name' , 'Foreign natural consumption of Home-made goods' ;
  12 , 'name' , 'Foreign natural consumption of Foreign-made goods' ;
  13 , 'name' , 'Home natural production function' ;
  14 , 'name' , 'Foreign natural production function' ;
  15 , 'name' , 'Home natural fiscal stance definition' ;
  16 , 'name' , 'Foreign natural fiscal stance definition' ;
  17 , 'name' , 'Home natural rate' ;
  18 , 'name' , 'Foreign natural rate' ;
  19 , 'name' , 'Union natural output' ;
  20 , 'name' , 'Union natural government spending' ;
  21 , 'name' , 'Union natural consumption' ;
  22 , 'name' , 'Union natural rate' ;
  23 , 'name' , 'c_H_nat_cu' ;
  24 , 'name' , 'c_F_nat_cu' ;
  25 , 'name' , 'f_nat_cu' ;
  26 , 'name' , 'n_nat_cu' ;
  27 , 'name' , 'nx_nat' ;
  28 , 'name' , 'nx_nat_starr' ;
  29 , 'name' , 'nx_nat_cu' ;
  30 , 'name' , 'Home New Keynesian Phillips Curve' ;
  31 , 'name' , 'Foreign New Keynesian Phillips Curve' ;
  32 , 'name' , 'Home Dynamic IS Curve' ;
  33 , 'name' , 'Foreign Dynamic IS Curve' ;
  34 , 'name' , 'IRS condition' ;
  35 , 'name' , 'LOP' ;
  36 , 'name' , 'Home production function' ;
  37 , 'name' , 'Foreign production function' ;
  38 , 'name' , 'Home good-market clearing condition' ;
  39 , 'name' , 'Foreign good-market clearing condition' ;
  40 , 'name' , 'Home fiscal stance definition' ;
  41 , 'name' , 'Foreign fiscal stance definition' ;
  42 , 'name' , 'Home consumption of Home-made goods' ;
  43 , 'name' , 'Home consumption of Foreign-made goods' ;
  44 , 'name' , 'Foreign consumption of Home-made goods' ;
  45 , 'name' , 'Foreign consumption of Foreign-made goods' ;
  46 , 'name' , 'Home interest rate' ;
  47 , 'name' , 'Foreign interest rate' ;
  48 , 'name' , 'Union inflation' ;
  49 , 'name' , 'Union output' ;
  50 , 'name' , 'Union government spending' ;
  51 , 'name' , 'Union consumption' ;
  52 , 'name' , 'c_H_cu' ;
  53 , 'name' , 'c_F_cu' ;
  54 , 'name' , 'f_cu' ;
  55 , 'name' , 'n_cu' ;
  56 , 'name' , 'nx' ;
  57 , 'name' , 'nx_starr' ;
  58 , 'name' , 'nx_cu' ;
  59 , 'name' , 'Home output gap definition' ;
  60 , 'name' , 'Home governmpent spending gap definition' ;
  61 , 'name' , 'Home consumption gap definition' ;
  62 , 'name' , 'Home consumption of Home_made goods gap definition' ;
  63 , 'name' , 'Home consumption of Foreign_made goods gap definition' ;
  64 , 'name' , 'Foreign labor gap definition' ;
  65 , 'name' , 'Home fiscal stance gap definition' ;
  66 , 'name' , 'Home terms of trade gap definition' ;
  67 , 'name' , 'Home interest rate gap definition' ;
  68 , 'name' , 'Foreign output gap definition' ;
  69 , 'name' , 'Foreign governmpent spending gap definition' ;
  70 , 'name' , 'Foreign consumption gap definition' ;
  71 , 'name' , 'Foreign consumption of Home_made goods gap definition' ;
  72 , 'name' , 'Foreign consumption of Foreign_made goods gap definition' ;
  73 , 'name' , 'Foreign labor gap definition' ;
  74 , 'name' , 'Foreign fiscal stance gap definition' ;
  75 , 'name' , 'Foreign terms of trade gap definition' ;
  76 , 'name' , 'Foreign interest rate gap definition' ;
  77 , 'name' , 'Union output gap definition' ;
  78 , 'name' , 'Union governmpent spending gap definition' ;
  79 , 'name' , 'Union consumption gap definition' ;
  80 , 'name' , 'Union interest rate gap definition' ;
  81 , 'name' , 'g_gap_r' ;
  82 , 'name' , 'n_gap_cu' ;
  83 , 'name' , 'f_gap_cu' ;
  84 , 'name' , 'c_H_gap_cu' ;
  85 , 'name' , 'c_F_gap_cu' ;
  86 , 'name' , 'nx_gap' ;
  87 , 'name' , 'nx_gap_starr' ;
  88 , 'name' , 'nx_gap_cu' ;
  89 , 'name' , '89' ;
  90 , 'name' , 'g' ;
  91 , 'name' , 'g_starr' ;
  92 , 'name' , 'a' ;
  93 , 'name' , 'a_starr' ;
  94 , 'name' , 'a_cu' ;
};
M_.mapping.a.eqidx = [1 13 17 30 36 92 94 ];
M_.mapping.a_starr.eqidx = [2 14 18 31 37 93 94 ];
M_.mapping.a_cu.eqidx = [94 ];
M_.mapping.eps_a.eqidx = [92 ];
M_.mapping.eps_a_starr.eqidx = [93 ];
M_.mapping.y_nat.eqidx = [1 3 5 13 15 17 19 27 59 ];
M_.mapping.g_nat.eqidx = [3 5 6 15 20 27 60 ];
M_.mapping.c_nat.eqidx = [1 3 6 9 10 21 27 61 ];
M_.mapping.c_H_nat.eqidx = [9 23 62 ];
M_.mapping.c_F_nat.eqidx = [10 24 63 ];
M_.mapping.n_nat.eqidx = [13 26 64 ];
M_.mapping.f_nat.eqidx = [15 25 65 ];
M_.mapping.s_nat.eqidx = [1 2 3 4 5 6 7 8 9 10 11 12 27 66 ];
M_.mapping.r_nat.eqidx = [17 22 67 ];
M_.mapping.nx_nat.eqidx = [27 29 86 ];
M_.mapping.y_nat_starr.eqidx = [2 4 5 14 16 18 19 28 68 ];
M_.mapping.g_nat_starr.eqidx = [4 5 7 16 20 28 69 ];
M_.mapping.c_nat_starr.eqidx = [2 4 7 11 12 21 28 70 ];
M_.mapping.c_H_nat_starr.eqidx = [11 23 71 ];
M_.mapping.c_F_nat_starr.eqidx = [12 24 72 ];
M_.mapping.n_nat_starr.eqidx = [14 26 73 ];
M_.mapping.f_nat_starr.eqidx = [16 25 74 ];
M_.mapping.s_nat_starr.eqidx = [8 28 75 ];
M_.mapping.r_nat_starr.eqidx = [18 22 76 ];
M_.mapping.nx_nat_starr.eqidx = [28 29 87 ];
M_.mapping.y_nat_cu.eqidx = [19 ];
M_.mapping.g_nat_cu.eqidx = [20 ];
M_.mapping.c_nat_cu.eqidx = [21 ];
M_.mapping.c_H_nat_cu.eqidx = [23 ];
M_.mapping.c_F_nat_cu.eqidx = [24 ];
M_.mapping.r_nat_cu.eqidx = [22 80 89 ];
M_.mapping.f_nat_cu.eqidx = [25 ];
M_.mapping.n_nat_cu.eqidx = [26 82 ];
M_.mapping.nx_nat_cu.eqidx = [29 ];
M_.mapping.y.eqidx = [30 31 32 33 34 36 38 40 49 56 59 ];
M_.mapping.pie.eqidx = [30 32 48 ];
M_.mapping.g.eqidx = [90 ];
M_.mapping.n.eqidx = [36 55 64 ];
M_.mapping.c.eqidx = [38 42 43 51 56 61 ];
M_.mapping.c_H.eqidx = [42 52 62 ];
M_.mapping.c_F.eqidx = [43 53 63 ];
M_.mapping.f.eqidx = [40 54 65 ];
M_.mapping.s.eqidx = [34 35 38 39 42 43 44 45 56 66 ];
M_.mapping.ii.eqidx = [32 46 67 80 ];
M_.mapping.nx.eqidx = [56 58 86 ];
M_.mapping.y_starr.eqidx = [30 31 32 33 34 37 39 41 49 57 68 ];
M_.mapping.pie_starr.eqidx = [31 33 48 ];
M_.mapping.g_starr.eqidx = [91 ];
M_.mapping.n_starr.eqidx = [37 55 73 ];
M_.mapping.c_starr.eqidx = [39 44 45 51 57 70 ];
M_.mapping.c_H_starr.eqidx = [44 52 71 ];
M_.mapping.c_F_starr.eqidx = [45 53 72 ];
M_.mapping.f_starr.eqidx = [41 54 74 ];
M_.mapping.ii_starr.eqidx = [33 47 76 ];
M_.mapping.s_starr.eqidx = [35 57 75 ];
M_.mapping.nx_starr.eqidx = [57 58 87 ];
M_.mapping.y_cu.eqidx = [49 ];
M_.mapping.g_cu.eqidx = [50 ];
M_.mapping.c_cu.eqidx = [51 ];
M_.mapping.c_H_cu.eqidx = [52 ];
M_.mapping.c_F_cu.eqidx = [53 ];
M_.mapping.ii_cu.eqidx = [46 47 89 ];
M_.mapping.pie_cu.eqidx = [48 89 ];
M_.mapping.f_cu.eqidx = [54 ];
M_.mapping.n_cu.eqidx = [55 82 ];
M_.mapping.nx_cu.eqidx = [58 ];
M_.mapping.y_gap.eqidx = [59 77 ];
M_.mapping.g_gap.eqidx = [60 78 81 ];
M_.mapping.c_gap.eqidx = [61 79 ];
M_.mapping.c_H_gap.eqidx = [62 84 ];
M_.mapping.c_F_gap.eqidx = [63 85 ];
M_.mapping.f_gap.eqidx = [65 83 ];
M_.mapping.n_gap.eqidx = [64 ];
M_.mapping.s_gap.eqidx = [66 ];
M_.mapping.ii_gap.eqidx = [67 ];
M_.mapping.nx_gap.eqidx = [86 88 ];
M_.mapping.y_gap_starr.eqidx = [68 77 ];
M_.mapping.g_gap_starr.eqidx = [69 78 81 ];
M_.mapping.c_gap_starr.eqidx = [70 79 ];
M_.mapping.c_H_gap_starr.eqidx = [71 84 ];
M_.mapping.c_F_gap_starr.eqidx = [72 85 ];
M_.mapping.f_gap_starr.eqidx = [74 83 ];
M_.mapping.n_gap_starr.eqidx = [73 ];
M_.mapping.s_gap_starr.eqidx = [75 ];
M_.mapping.ii_gap_starr.eqidx = [76 ];
M_.mapping.nx_gap_starr.eqidx = [87 88 ];
M_.mapping.y_gap_cu.eqidx = [77 89 ];
M_.mapping.g_gap_cu.eqidx = [78 ];
M_.mapping.c_gap_cu.eqidx = [79 ];
M_.mapping.c_H_gap_cu.eqidx = [84 ];
M_.mapping.c_F_gap_cu.eqidx = [85 ];
M_.mapping.ii_gap_cu.eqidx = [80 ];
M_.mapping.n_gap_cu.eqidx = [82 ];
M_.mapping.f_gap_cu.eqidx = [83 ];
M_.mapping.nx_gap_cu.eqidx = [88 ];
M_.mapping.g_gap_r.eqidx = [81 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [1 2 29 60 ];
M_.exo_names_orig_ord = [1:2];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(94, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = NaN(25, 1);
M_.endo_trends = struct('deflator', cell(94, 1), 'log_deflator', cell(94, 1), 'growth_factor', cell(94, 1), 'log_growth_factor', cell(94, 1));
M_.NNZDerivatives = [297; 0; -1; ];
M_.static_tmp_nbr = [0; 1; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
M_.Sigma_e(2, 2) = 1;
M_.params(1) = 0.99;
BETA = M_.params(1);
M_.params(2) = 3;
SIGMA = M_.params(2);
M_.params(3) = 1;
PHI = M_.params(3);
M_.params(4) = 1;
GAMMA = M_.params(4);
M_.params(5) = 4.5;
ETA = M_.params(5);
M_.params(6) = 6;
EPSILON = M_.params(6);
M_.params(10) = 0.75;
THETA_starr = M_.params(10);
M_.params(11) = 0.25;
DELTA = M_.params(11);
M_.params(25) = 0.95;
RHOA = M_.params(25);
M_.params(24) = 0.92;
RHOG = M_.params(24);
M_.params(17) = (1-M_.params(10))*(1-M_.params(10)*M_.params(1))/M_.params(10);
LAMBDA_starr = M_.params(17);
M_.params(19) = M_.params(2)/(1-M_.params(11));
SIGMA_tilde = M_.params(19);
M_.params(12) = (1-M_.params(11))^M_.params(2);
CHI_C = M_.params(12);
M_.params(13) = M_.params(11)^M_.params(4);
CHI_G = M_.params(13);
M_.params(7) = 0.5;
h = M_.params(7);
M_.params(8) = 0.4;
ALPHA_bar = M_.params(8);
M_.params(9) = 0.5;
THETA = M_.params(9);
M_.params(14) = M_.params(8)*(1-M_.params(7));
ALPHA = M_.params(14);
M_.params(15) = M_.params(8)*M_.params(7);
ALPHA_starr = M_.params(15);
M_.params(16) = (1-M_.params(9))*(1-M_.params(1)*M_.params(9))/M_.params(9);
LAMBDA = M_.params(16);
M_.params(18) = 1+(2-M_.params(8))*(M_.params(2)*M_.params(5)-1);
W_ALPHA_bar = M_.params(18);
M_.params(20) = M_.params(18)-1;
THETA_ALPHA_bar = M_.params(20);
M_.params(21) = M_.params(19)/(1+M_.params(8)*M_.params(20));
SIGMA_tilde_ALPHA_bar = M_.params(21);
M_.params(22) = 1+M_.params(8)*M_.params(7)*M_.params(20);
OMEGA = M_.params(22);
M_.params(23) = 1+M_.params(8)*(1-M_.params(7))*M_.params(20);
OMEGA_starr = M_.params(23);
options_.irf = 200;
options_.nocorr = true;
options_.nodecomposition = true;
options_.nograph = true;
options_.nomoments = true;
options_.order = 2;
options_.irf_shocks = {'eps_a_starr'};
var_list_ = {};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
[pol_name,folder_name,benchmark_folder_name]=get_folder_name("SUBOPTIMAL","EQUAL_WEIGHT","BLANCHARD","NX_GAP_RULE","FOREIGN_UNCONSTRAINED","HOME_UNION_ORIENTED",h,ALPHA_bar,THETA);
mkdir(folder_name)
analyze_welfare(oo_.irfs,options_.irf,"EQUAL_WEIGHT","SUBOPTIMAL",folder_name,benchmark_folder_name,BETA,SIGMA,DELTA,PHI,GAMMA,EPSILON,LAMBDA,LAMBDA_starr,h,ALPHA_bar);
T_plot=100
my_annotation=[char(strrep(strrep("EQUAL_WEIGHT, "+pol_name," - ",", "),"_"," ")) ', $$\Phi_{nx}$$ = $$\Phi_{nx}^*$$ = ' num2str(FP_nx_gapH) ', $$h$$ = ' num2str(h) ', $$\bar{\alpha}$$ =' num2str(ALPHA_bar) ', $$\theta$$ = ' num2str(THETA)]
generate_plot_2(oo_.irfs,T_plot,my_annotation,folder_name)
M_.params(7) = 0.75;
h = M_.params(7);
M_.params(8) = 0.4;
ALPHA_bar = M_.params(8);
M_.params(9) = 0.5;
THETA = M_.params(9);
M_.params(14) = M_.params(8)*(1-M_.params(7));
ALPHA = M_.params(14);
M_.params(15) = M_.params(8)*M_.params(7);
ALPHA_starr = M_.params(15);
M_.params(16) = (1-M_.params(9))*(1-M_.params(1)*M_.params(9))/M_.params(9);
LAMBDA = M_.params(16);
M_.params(18) = 1+(2-M_.params(8))*(M_.params(2)*M_.params(5)-1);
W_ALPHA_bar = M_.params(18);
M_.params(20) = M_.params(18)-1;
THETA_ALPHA_bar = M_.params(20);
M_.params(21) = M_.params(19)/(1+M_.params(8)*M_.params(20));
SIGMA_tilde_ALPHA_bar = M_.params(21);
M_.params(22) = 1+M_.params(8)*M_.params(7)*M_.params(20);
OMEGA = M_.params(22);
M_.params(23) = 1+M_.params(8)*(1-M_.params(7))*M_.params(20);
OMEGA_starr = M_.params(23);
options_.irf = 200;
options_.nocorr = true;
options_.nodecomposition = true;
options_.nograph = true;
options_.nomoments = true;
options_.order = 2;
options_.irf_shocks = {'eps_a_starr'};
var_list_ = {};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
[pol_name,folder_name,benchmark_folder_name]=get_folder_name("SUBOPTIMAL","EQUAL_WEIGHT","BLANCHARD","NX_GAP_RULE","FOREIGN_UNCONSTRAINED","HOME_UNION_ORIENTED",h,ALPHA_bar,THETA);
mkdir(folder_name)
analyze_welfare(oo_.irfs,options_.irf,"EQUAL_WEIGHT","SUBOPTIMAL",folder_name,benchmark_folder_name,BETA,SIGMA,DELTA,PHI,GAMMA,EPSILON,LAMBDA,LAMBDA_starr,h,ALPHA_bar);
T_plot=100
my_annotation=[char(strrep(strrep("EQUAL_WEIGHT, "+pol_name," - ",", "),"_"," ")) ', $$\Phi_{nx}$$ = $$\Phi_{nx}^*$$ = ' num2str(FP_nx_gapH) ', $$h$$ = ' num2str(h) ', $$\bar{\alpha}$$ =' num2str(ALPHA_bar) ', $$\theta$$ = ' num2str(THETA)]
generate_plot_2(oo_.irfs,T_plot,my_annotation,folder_name)


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_11_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_11_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_11_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_11_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_11_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_11_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'MODEL_MAIN_11_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
